### ISSUE TITLE
Sorting items with multiple filters

### ISSUE THREAD

**Issue by tobiasdiez** [patrickkunka/mixitup#109]
Invoking a sort command

   $('#grid').mixItUp('sort',...);

leads to an deactivation of all filter buttons (e.g they loose the 'active' class). However, using buttons while letting mixitup do and manage the sorting itself works. I believe there is a problem in the _updateControls method.

**Comment by patrickkunka** [comment]
https://github.com/patrickkunka/mixitup/releases/tag/v3.0.0
