### ISSUE TITLE
dynamically remove items

### ISSUE THREAD

**Issue by hanssnabilie** [patrickkunka/mixitup#126]
I'm probably blind but I can't seem to find a way to dynamically remove items. Plenty of insert options, what am I missing? :)

**Comment by shockerton** [comment]
Does this still work? unable to get this working...

**Comment by patrickkunka** [comment]
MixItUp 3 now has a `.remove()` method. Check out the Mixer API docs:

https://www.kunkalabs.com/mixitup/docs/api-methods/

**Comment by Radu033** [comment]
@patrickkunka  thanks for adding the `.remove` method, I however get the following error when trying to remove multiple elements. "instruction.command.collection.indexOf is not a function" 

This is how I use the method
```
mixer.remove(document.querySelectorAll('#configurator_tab_1 .hide-on-2tab')).then(function() {
        console.log(tab1Filters.length); // 0
    });
```

Any ideas on that?

**Comment by Radu033** [comment]
@patrickkunka  I'm trying to remove a collection but I get the following error 
`instruction.command.collection.indexOf is not a function`

Here is how I use the method:
```
const test = el.querySelectorAll('.tab1');

mixer.remove(test).then(function() {
        console.log(tab1Filters.length); // 0
    });

If I console.log test before the method call it shows me the nodelist correctly.
```

Any ideas on this one?
