### ISSUE TITLE
All checkbox option with multifilter set to true

### ISSUE THREAD

**Issue by kennycrippen** [patrickkunka/mixitup#133]
Hi there, I implemented Mixitup v. 1.5.5 around a week before the big 2.0 release. I have it set up as a multi-filter. What I need to do is add an "All" checkbox, much like the v. 1.5.5 Parks demo. Would it be possible to get a copy of the Parks demo legacy code, or better yet, would you be able to point me in the right direction using v. 2.0? Thank you!

**Comment by a2exfr** [comment]
Where is possible to find this old docs? for v.1.5.5

**Comment by patrickkunka** [comment]
Hi @a2exfr.

v1.x hasn't been supported for almost 3 years and the old documentation site has now been taken down.

You can find a basic overview in our commit history:

https://github.com/patrickkunka/mixitup/tree/1c149cfbdecdf291094bdda55a50810d9468298d

But if you want to do something else, I would recommend you upgrade to the latest version. Both the v2 and v3 docs are maintained on the GitHub v2 and v3 branches respectively.
