### ISSUE TITLE
MixitUp initialized after Ajax call

### ISSUE THREAD

**Issue by toddca** [patrickkunka/mixitup#149]
So I have a page that makes an ajax call and splices the returning html onto an element in my dom. Included in this html is an element with the id of 'card-container' I then call $('#card-container').mixItUp(...) but nothing happens. If I load this page with a full refresh and build the page with the html already in the dom at startup everything works. I have tested that $('#card-container').length == 1 just after the ajax call and before the call to mixitup.

**Comment by saswatraj** [comment]
Totally solved the problem. Thanks !!

**Comment by roccomuso** [comment]
Problem solved, you should write it on the docs.

**Comment by razaumer** [comment]
Awesome solution Thanks alot @toddca <3
