### ISSUE TITLE
filter displaying filtered elements with all unfiltered elements issues

### ISSUE THREAD

**Issue by udemethegrtman** [patrickkunka/mixitup#180]
**i am using the mixitup  plugin but i am having this issue. the filter shows the filtered file but also shows the unfiltered file too.** 

```
<!-- controls -->
<ul class="inline-list">
      <li><h5 class="text-center filter content-large-text-raleway" data-filter="all">All</h5></li>
      <li><h5 class="text-center filter content-large-text-raleway" data-filter=".web-des">Web Design</h5></li>
      <li><h5 class="text-center filter content-large-text-raleway" data-filter=".eccom">Ecommerce</h5></li>
      <li><h5 class="text-center filter content-large-text-raleway" data-filter=".mob">Mobile</h5></li>
      <li><h5 class="text-center filter content-large-text-raleway" data-filter=".db-des">Database Design</h5></li>
    </ul>

<!-- portfolios -->
    <div id="Container" class="go-down-a-bit-30">
      <div class="port-image-box go-up-a-bit-10 mix web-des" data-my-order="1"> 1 </div>
      <div class="port-image-box go-up-a-bit-10 mix web-des" data-my-order="2"> 2 </div>
      <div class="port-image-box go-up-a-bit-10 mix web-des" data-my-order="3"> 3 </div>
      <div class="port-image-box go-up-a-bit-10 mix eccom" data-my-order="4"> 4 </div>
      <div class="port-image-box go-up-a-bit-10 mix eccom" data-my-order="5"> 5 </div>
      <div class="port-image-box go-up-a-bit-10 mix eccom" data-my-order="6"> 6 </div>
      <div class="port-image-box go-up-a-bit-10 mix mob" data-my-order="7"> 7 </div>
      <div class="port-image-box go-up-a-bit-10 mix mob" data-my-order="8"> 8 </div>
      <div class="port-image-box go-up-a-bit-10 mix mob" data-my-order="9"> 9 </div>
      <div class="port-image-box go-up-a-bit-10 mix db-des" data-my-order="10"> 10 </div>
      <div class="port-image-box go-up-a-bit-10 mix db-des" data-my-order="11"> 11 </div>
      <div class="port-image-box go-up-a-bit-10 mix db-des" data-my-order="12"> 12 </div>
    </div>
```

![screenshot from 2014-12-30 10 34 25](https://cloud.githubusercontent.com/assets/1827768/5577365/2986c356-9010-11e4-8de0-3c8a3128350c.png)

**Comment by ubilli** [comment]
Hi,

I&#39;d like to add you to my professional network on LinkedIn.

- Udeme

Accept: https://www.linkedin.com/blink?simpleRedirect=0OcPgUdP4OdjgTczwQdj0QejARfkh9rCZFt65QqnpKqioTgAVSrCZWk3RVpkJApn9xq7cCt7dBtmtvpnhFtCVFfmJB9C5QoORBt6BSrCAJt7dBtmsJr6RBfmtKqmJzon9Q9ClQqnpKimtBkClOs3Rx9zkNbmRStSZIqjxFbmAUoD5WozRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5994054838898429954_500&markAsRead=


You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=dj4JrnpTrSNFe6AJqjxysnFyfmhFpioTe7tmuz1EsCB9dBZyln12i4tmpl5TgSxHizdpnT9mrRlGk6NAkPsQq5gMljhlljx4jDpjskdduj1zdTh3gBoPrnFjqB18lltkcnlkj3BlnQwJlQF8izxbukV5r651oTAVikVDrmQUmnEUc6Z7s5xQr5BOlR5IcAMMc4Blj3xki3pDqntjsRpfiChxlBxFkDxSsAx5e7lgmDxSt3pOrQRLq5xIumFSjDt9e3lRcP5fs3xVlk51gk4ShRESsRdDdBwRhl51fmhFrSMCt7dBtmtvpnhFtCVFfmJB9B4ScSh5hSxmhD9JhB51fmVBqSZkp6BJ9CVRr3RQ9zkNbmRStSZIqjxFbmAUoD5WozRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I5994054838898429954_500&amp;markAsRead= Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=e3wTd3RAimlIoSBQsC4Ct7dBtmtvpnhFtCVFfmJB9CNOlmlzqnpOpldOpmRLt7dRoPRx9zkNbmRStSZIqjxFbmAUoD5WozRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5994054838898429954_500&markAsRead=
&copy; 2015, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by ubilli** [comment]
Udeme Samuel would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/blink?simpleRedirect=czcQe3sNczkQdP8Ud3kMd3AVdjR4imVLqnhxt6BSrCACdQ9etCVLuB0Zumlbp6lOomxP9DhUpnhvt71BoSdxfndQ9CZOpmwZrioPfmBI9z4MnT9Bp6VFrmlOnThPpnlDnThPsCBCfmJB9ClQqnpKimtBkClOs3Rx9CIRbjBxs7pAsPxFbmAUoD5WozRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5994054838898429954_500&markAsRead=

View Udeme Samuel&#39;s profile: https://www.linkedin.com/blink?simpleRedirect=0VdjgRc38Vcj4Zh4BOpm9JpmQCt7xBt5ZBr6BCrT9MfndQ9CZOpmwZrioQfmBI9z4MnT9Bp6VFrmlOnThPpnlDnThPsCBCfmJB9DpMrzRQ9CIRbjBxs7pAsPxFbmAUoD5WozRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5994054838898429954_500&markAsRead=

You are receiving Reminder emails for pending invitations. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=rmZzhj8BoDlEt6BDhj8BumNMpn8Md2kNd6gQoj8Pc6lzejoNoj8VcmcSdS5yc34Nc30Mc30Mc6pzczByojlBe6gNdz9yd30UdzxCd30Tcj4McClAcPgUdPwSd6gUdC4Uc6oMe68Ppm8Nc312cylVr71BszRIqm5JpioMdz0MczRAqioOcPgUdP4OdjgTczwQdj0QejARfmhFpOoNc5ZOpmhKqmRBsBZQsSlRpRZQsT9FpzRHpipQu6lQnS9RsSVRbjkJoDlPrDkJcj1vsClArCBJpn9vt7dBtmtvt7dOqmoJr6RBfmtKqmJzon9Q9CZLpPRQ9CIRbjBxs7pAsPxFbmAUoD5WozRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5994054838898429954_500&markAsRead=

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=6IRbjBxs7pAsPxFbmAUoD5WozRAqmkCjBlMlCFxqAEQt6YPbm5KkCUPhzAPkzx7ulBGhBFknTBLhSZxglBppA97rkkOc5pRmA9igP1CektSijdOhBxjt6VgmAVhhRd3el9RsC56sjxkjQQQr7FzdTBckz9Td3p6im8TiCBosjd1u4JSgjBzmn0Mumteq45mlAF2tT9SrPhciPxjlAJQempKdmRfsQYQolsVtkJlj4lam3cRpjdvcAJJhmwNind2kjgPqBdDj5xDuBl1gk51gDFAj3xLqDtTkQxhgjRAqmZI9z4MnT9Bp6VFrmlOnThPpnlDnThPsCBCfmJB9B4ScSh5hSxmhD9JhB51fmVBqSZkp6BJ9CVRr3RQ9CIRbjBxs7pAsPxFbmAUoD5WozRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I5994054838898429954_500&amp;markAsRead=This email was intended for patrickkunka/mixitup. Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=3wUdPgZp4BBr6dFt79x9z4MnT9Bp6VFrmlOnThPpnlDnThPsCBCfmJB9CNOlmlzqnpOpldOpmRLt7dRoPRx9CIRbjBxs7pAsPxFbmAUoD5WozRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5994054838898429954_500&markAsRead=
&copy; 2015, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by ubilli** [comment]
Udeme Samuel would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/blink?simpleRedirect=0OcPgUdP4OdjgTczwQdj0QejARfkh9rCZFt65QqnpKqioTgAVSrCZWk3RVpkJApn9xq7cCt7xBt5ZQs6lzoS4ZsTgCrT9Bq3RJ9zcZqmMCcj1vsClArCBJpn9vt7dBtmtvp6VLoSlPfmJB9ClQqnpKimtBkClOs3Rx9CANbmhWenxAczBFbmAUoD5WozRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5994054838898429954_500&markAsRead=

View Udeme Samuel&#39;s profile: https://www.linkedin.com/blink?simpleRedirect=3ARd3kMczANcjR4in9BoCRBripQu6lQnSlIqmpLsD0ZsTgCrT9Bq3RJ9zgZqmMCcj1vsClArCBJpn9vt7dBtmtvp6VLoSlPfmJB9DpMrzRQ9CANbmhWenxAczBFbmAUoD5WozRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5994054838898429954_500&markAsRead=

You are receiving Reminder emails for pending invitations. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=6RLoQkO9m9Rq7hFpQkO9nBIs6lOc3gBcjhAd64OcP1BoPAScm4Oej5zdztxoz0Ncj0Mc30Mc31CoP8VoC4RpjxAcjoOozgMe3oUpzgMdP4Nc39Bp3cQe3sUdzhAe3pxe31Cc3xycSlycj0Mgz8BumNMpn8Zr6BxrmkCc3oMc38Zp6ACczcQe3sNczkQdP8Ud3kMd3AVdjRAqmsCcj1vsClArCBJpn9vt7dBtmtvp6VLoSlPfmJB9DhUpnhvoDlPrDkJdyRytndKtiQNc5ZOpmhKqmRBsBZQsSlRpRZArCZzpncJr6RBfmtKqmJzon9Q9CZLpPRQ9CANbmhWenxAczBFbmAUoD5WozRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5994054838898429954_500&markAsRead=

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=qj4Jp7EVu6gOemAJqjxysnFyfmhFpipau7tjp45Sc55Kl6V5dBlBcTB2p6tQq3BomChydP0Ts6xWjmRDs6xLmzp5ej1nrQdzhSZCkjxMq6Nvr5kOgmllompNsTtAonh8dPhSr51cmjx3c5ZytQVztlBbiSd2jzpecSxMuB5qemNbnRhom6pnhBsMiz8TqABfilh4tk9Dc6xqil8Vj5oTeloPnQNvbn9gj3t9h3dqkT0RdmR5hkZMuAoJpmoUl7BytmNBhSx5rQkMlk51gmtahndcpRd2j6hQhB51fmhFrSMCcj1vsClArCBJpn9vt7dBtmtvp6VLoSlPfmJB9B4ScSh5hSxmhD9JhB51fmVBqSZkp6BJ9CVRr3RQ9CANbmhWenxAczBFbmAUoD5WozRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I5994054838898429954_500&amp;markAsRead=This email was intended for patrickkunka/mixitup. Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=e3wTd3RAimlIoSBQsC4Ccj1vsClArCBJpn9vt7dBtmtvp6VLoSlPfmJB9CNOlmlzqnpOpldOpmRLt7dRoPRx9CANbmhWenxAczBFbmAUoD5WozRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5994054838898429954_500&markAsRead=
&copy; 2015, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA
