### ISSUE TITLE
mixitup.kunkalabs.com is down

### ISSUE THREAD

**Issue by Cleecanth** [patrickkunka/mixitup#181]
Verified by is http://www.isitdownrightnow.com/mixitup.kunkalabs.com.html

Been this way for at least a month now. 
Has this project been abandoned?

**Comment by patrickkunka** [comment]
Hmm thanks for letting me know - its fine here. Will look into it ASAP!

**Comment by patrickkunka** [comment]
I can't seem to find any issues. Have checked it through various international proxies, and seems to be fine. Google analytics is reporting regular traffic as usual over the last month. 

My SSL certificate is renewing this month so could possibly be related to that. I will contact my provider and see if they have any insights. Are you still unable to view the site?

Happy to report the project has not been abandoned - Version 3 is currently in development.

**Comment by Cleecanth** [comment]
Very weird. It appears to be working totally fine now.

Thanks for the quick reply and the continued development. Mixitup has been invaluable in a recent project.

**Comment by patrickkunka** [comment]
No problem - thanks again for the heads up. Will keep a look out for any more issues.
