### ISSUE TITLE
Only fade in - fade out

### ISSUE THREAD

**Issue by nielvrom** [patrickkunka/mixitup#182]
Is it possible to only fade out the images and then fade in the other images? 

I'm using a html/css theme that is not created by me so that's why the mixitup library is used, maybe not the best solution in this case. 

So I was wondering if it's possible to fade out the images and just fade in other images without the other effects?

**Comment by patrickkunka** [comment]
You don't need MixItUp for this, just use jQuery's filter method with fade in/out effects.
