### ISSUE TITLE
sorting sorts randomly instead of asc

### ISSUE THREAD

**Issue by avners** [patrickkunka/mixitup#183]
I have a project in which i applied abc-filter="[sequence number]"
however when i try to
$('.view-id-personas').mixItUp('sort', 'abc-filter:desc');
i get a random order in which the first abc-filter is
abc-filter=”7″
then abc-filter=”22″
then abc-filter=”0″
and so on…

am i missing something here?
what can i do to make the script sort ascending or descending and not randomly?

I am using latest 2.1.7 version

**Comment by patrickkunka** [comment]
Hi Avners. 

Are you using data attributes for your sort values? All custom data attributes on html elements should be preceded with "data-" for validity. The sort functionality expects this when looking for sorting values.

Your target elements should look like this:
```html
<div class="mix" data-abc="22"></div>
```

And your JS should look like this:
```js
$('.view-id-personas').mixItUp('sort', 'abc:desc');
```

Hope that helps.

**Comment by avners** [comment]
Very much, thanks!
only outstanding issue is that the default sort when refreshing the page is the random one,
can i apply a different one?

**Comment by patrickkunka** [comment]
When you first instantiate mixItUp, you can set the default sort via the configuration object:

```js
$('.view-id-personas').mixItUp({
  load: {
     sort: 'abc:desc'
  }
});
```
