### ISSUE TITLE
load configuration

### ISSUE THREAD

**Issue by Troikacom** [patrickkunka/mixitup#184]
Hi, 

I used MixItUp by following these instructions : 

http://www.queness.com/post/14577/create-a-simple-responsive-portfolio-page-with-filtering-and-hover-effect

and now I need to use the load:{} configuration. However, I don't understand how, according to this syntax :

$(function () {
		
		var filterList = {
		
			init: function () {
			
				// MixItUp plugin
				// http://mixitup.io
				$('#portfoliolist').mixitup({
					targetSelector: '.portfolio',
				
					
				});				
			
			}
			
			

		};
               filterList.init();
		
		
	});	
	

I would like to define a certain filter on load, and I tried this:

                          filter: 'my-cat',

and this : 

                         filterLoad: 'my-cat',

and many others, but nothing seems to be working.

Thanks,

Troikacom

**Comment by patrickkunka** [comment]
Your code is out of date. Please refer to our website for the V2 documentation. There is a load sub object of the configuration object.
