### ISSUE TITLE
load more button

### ISSUE THREAD

**Issue by sergeaubin2011** [patrickkunka/mixitup#185]
trying to configure a button to load 4 items at a time.  any ideas how?  i have pagination enabled.

url: dev.gsdc.ca/tourismnew/mixtit.php

**Comment by patrickkunka** [comment]
Use the load more button to increment to page limit by four on each click, via the paginate API method.

**Comment by jeffceriello** [comment]
Hi Patrick, I'm also trying to update the pagination limit on click but still no luck. This is what I have so far

```
var pagelimit = 6;
	$loadMore.on('click', function() {
		pagelimit += 6;
		mixer.configure({
			pagination: {
				limit: pagelimit
			}
		});
	});
```

I have a first limit of 6 elements and on click I'd like to show 6 more.

The $loadMore click is fired but the limit doesn't seem to update.

Am I doing it wrong?

Thank you!

**Comment by jeffceriello** [comment]
Sorry, got it!

```
var pagelimit = 6;
	$loadMore.on('click', function() {
		pagelimit += 6;
		mixer.paginate({
		   limit: pagelimit
		});
	});
```

Thank you

**Comment by patrickkunka** [comment]
Yes - perfect.

For anyone else reading this, the `configure()` method only affects persistent configuration settings like animation etc. It can't be used to trigger an operation. Use the operation specific methods for this such as `.filter()`, `sort()`, `paginate()`, `multimix()` etc.
