### ISSUE TITLE
Not working on Chrome while strict mode is on.

### ISSUE THREAD

**Issue by re-enter-rupok** [patrickkunka/mixitup#186]
Google Chrome doesn't show any item while I initialize mixitUp within strict mode. It works fine when I use <pre>    $(function notStrict() {
        $('#portfolio').mixItUp();
    });</pre>

Any solution without <code>notStrict()</code> ?

**Comment by patrickkunka** [comment]
Hi,

Can you tell me how and where you are opting-in to strict mode in relation to the snippet you posted above?
