### ISSUE TITLE
Publish to npm?

### ISSUE THREAD

**Issue by anselmh** [patrickkunka/mixitup#188]
It seems while you have set up a npm `package.json` you didn’t publish the package to npmjs.org registry. Could you please do this for the curent version and all upcoming versions, too?
This would ensure that you can fetch the package not only with bower but also with npm.

**Comment by kisenka** [comment]
+1

**Comment by d9onis** [comment]
+ 1

**Comment by alexspark86** [comment]
+1

**Comment by antonioOrtiz** [comment]
+1

**Comment by arnolali** [comment]
+1

**Comment by chotikarn** [comment]
+1

**Comment by travis1234** [comment]
+2

**Comment by kisenka** [comment]
@patrickkunka are you with us? :)

**Comment by bossanova808** [comment]
+1

**Comment by dominicwhittle** [comment]
+1

**Comment by piotrkulpinski** [comment]
+1

**Comment by patrickkunka** [comment]
I hear you guys, thank you for the interest. This will happen with the release of MixItUp 3 early next year which includes full AMD and CJS module support. I don't plan to put MixItUp 2 on npm without actual module compatibility.

**Comment by sutter** [comment]
+1

**Comment by patrickkunka** [comment]
MixItUp 3 has been published to npm:

https://www.npmjs.com/package/mixitup
