### ISSUE TITLE
Destroy and restart causes filter buttons to require multiple clicks to activate

### ISSUE THREAD

**Issue by amrsh** [patrickkunka/mixitup#189]
For an example see http://codepen.io/anon/pen/ogdXrx.

After a destroy and restart, you have to click on the filter buttons twice to get them to be set with the active class. If you destroy and restart again, you have to click three times.

I am using this in order to refresh mixitup after the mix elements have been updated by angularjs. Please advise if there is a better way to do this; it manually can be accomplished by clicking on a different filter button. Thanks for an awesome plugin!

**Comment by amrsh** [comment]
This issue can be fixed by inserting the following after the destroy call (CodePen updated):

          $.MixItUp.prototype._bound['_filter']['.filter'] = 0;

I found this by looking at the trackClick function in _processClick. The above expression gets incremented each time mixitup is started, and does not get zeroed out during destroy.

**Comment by patrickkunka** [comment]
Thanks for finding this - that makes perfect sense. I've previously only used .destroy() with API controls so I never came across this.

I'll get a patch out in the next few days.

**Comment by amrsh** [comment]
Thanks! Any other options to refresh mixitup after the mix elements have been updated?

**Comment by patrickkunka** [comment]
Sure - are you inserting your new elements manually, or using the MixItUp "insert" API methods?

The later should take care of refreshing MixItUp. There is also a private method called '_refresh' which you can use to update the targets. Call it as follows:

```$('#container').mixItUp('_refresh');```

**Comment by amrsh** [comment]
The mix elements are being updated by AngularJS, both via ng-repeat and routing. I saw the '_refresh' method in the code and tried it, but it doesn't work in either case; the new elements don't get picked up. 

Just FYI on _refresh; the destroy and restart method seems to work fine, the only downside is that it bounces the filter back to 'all'.

**Comment by patrickkunka** [comment]
This is now fixed in v2.1.8
