### ISSUE TITLE
Chrome inline styles

### ISSUE THREAD

**Issue by Sogl** [patrickkunka/mixitup#193]
Hi!

Please, take a look at this issue:
https://github.com/n33/skel-layers/issues/19

Is there a problem caused by mixitup?

**Comment by Sogl** [comment]
Sometimes after a few updates inline css styles disappear and everything works as it should :/

**Comment by Sogl** [comment]
Sometimes after a few updates inline css styles disappear and everything works as it should :/

**Comment by Sogl** [comment]
Sometimes after a few updates inline css styles disappear and everything works as it should :/

**Comment by patrickkunka** [comment]
Sorry Sogl - This attached link does not work or is private. Has this been resolved?

**Comment by Sogl** [comment]
Oops, repository is closed =(
This is the same issue I created earlier:
https://github.com/n33/skel/issues/123

Also take a look at my portfolio site in Chrome and Firefox:
http://mezin.me/

Please, refresh page (F5) and change portfolio filters in Chrome. Sometimes it working sometimes not.
Also not working in IE11.
If i change cols = items than works in Chrome good.

Same styling works well on another site:
http://dev.webdesign-master.ru/_wp_html/
