### ISSUE TITLE
sorting is different while no change is made

### ISSUE THREAD

**Issue by avners** [patrickkunka/mixitup#196]
Hello Patrick,

I have a page in which i implemented a filter (called "data-prof"),
each time i implement the filter+sort the sorting is done differently although no change was made to the values of this filter

Demo page can be found at http://cinemapub.klido.net/ and you can filter by :
1. clicking on the right selectbox and choosing the second options
2. using the below script in your browser's console
```javascript
jQuery('.view-id-personas').mixItUp('multiMix', {
	filter: '.prof',
	sort: 'prof:asc'
});
```
please advise
Avner

**Comment by patrickkunka** [comment]
Hi Avner,

Thanks for the demo.

There are two things to be aware of when sorting by custom attributes.

- Every target element must include every sort attribute, even if you don't intend them to be included in the sort. This enables MixItUp to index them correctly. Therefore, make sure every '.mix' element has a `data-prof` and `data-abc` attribute. You can set the value as something arbitrarily high or low as needed.

- Be sure not to combine letters and numbers in your attribute values, as you may not get the results you're expecting. Either do purely alphabetical or purely numeric, as MixItUp will try to cast any numeric values into integers before comparing. Also - I'm not sure how Javascript will handle the hebrew characters, might be safer to strict to numbers, or the Roman alphabet. If you want to sort by multiple attributes at once, you can use the advanced multi-attribute sorting as described in the docs.

Let me know if that helps.

**Comment by avners** [comment]
thanks for the prompt reply!
i made the change to numeric values only and it seems to be working
Will keep you posted

Avner

**Comment by patrickkunka** [comment]
Great - thanks
