### ISSUE TITLE
Filter by min and max Date Range

### ISSUE THREAD

**Issue by asadalikanwal** [patrickkunka/mixitup#198]
I cant filter by min & max date Range.

I an jquery-ui for Date Filter. I have to Date Filters

- From Date (min)
- To Date (max)

Now i need to search in between these dates selected.

**Comment by asadalikanwal** [comment]
Got Answer:

// assuming you have stored your min and max values already through whatever UI exists, e.g. a range slider:

var min = 20140408, max = 20150101;

// create a jQuery object collection of target elements:

var $targets = $('#Container').find('.mix'); 

// filter the collection by a function, if the function returns true, the element will be added to the $show collection

var $show = $targets.filter(function(){
	var date = $(this).attr('data-date') * 1;
	return date >= min && data <= max;
});

// pass the $show object to MixItUp via its filter method:

$('#Container').mixItUp('filter', $show);

**Comment by asadalikanwal** [comment]
https://mixitup.kunkalabs.com/support/topic/best-way-to-filter-based-on-provided-date-ranges/

**Comment by carlos-widgilabs** [comment]
> 

This is not working... and this link not found https://mixitup.kunkalabs.com/support/topic/best-way-to-filter-based-on-provided-date-ranges/
