### ISSUE TITLE
Strange Sort Behaviour

### ISSUE THREAD

**Issue by iKettles** [patrickkunka/mixitup#202]
Hi,

We're using MixItUp for a small web application. It works great however we've noticed something very strange when using multi sorting. You can see an example here:

http://dev-medialab.hva.nl/toolkit/

If you click Sort by Effort + on the left, then click Sort by Effort - after, an element which should not appear at the start does. So for example 'The Aoki Method' will appear 1st in the list even though the list is sorted A-Z after effort. After diving deeper into it I can see that 'The Aoki Method' and 'Activity Map' have actually been reversed. We thought it was a problem with the name so changed it but the same will happen again with the first item in the list and one at the end.

Any help would be appreciated!

Thanks

**Comment by patrickkunka** [comment]
Please comment if still an issue.
