### ISSUE TITLE
toggleFilterButtons

### ISSUE THREAD

**Issue by HybridSolutions** [patrickkunka/mixitup#207]
Imagine that you have toggleFilterButtons: true and the following filters:

```
<div id="myFilter3" class="filter-group text-center clearfix">
        <span class="filter" data-filter="all">Show All</span>
        <span class="filter" data-filter=".fashion">Fashion</span>
        <span class="filter" data-filter=".portraits">Portraits</span>
        <span class="filter" data-filter=".stills">Stills</span>
        <span class="filter" data-filter=".landscape">Landscape</span>
        <span class="filter" data-filter=".landscape.fashion">Landscape and Fashion</span>
        <span class="filter" data-filter=".landscape, .fashion">Landscape or Fashion</span>
    </div> 
```

When we select "Fashion" or any other filter, nothing happens even if we deselect "All".  We have to deselect "Fashion", and select it again. This behavior is not correct. When we press "Fashion", "All" should automatically be deselected and cleared from filters array. Also, when all the filters are deselected, "All" should be automatically selected.

I know I can have custom filtering controls, but having this built in would be great.

You can see this issue on the example at http://codepen.io/patrickkunka/pen/KisAG. Just replace the javascript code with

```
$(function(){
  $('#Container').mixItUp({
    controls: {
            enable: true,            
            toggleFilterButtons: true,
            toggleLogic: 'or'
        }
});
});
```

Thank you!

**Comment by patrickkunka** [comment]
Hello,

Using "all" with toggling is currently not supported as mixItUp has no way of knowing what all represents in this context. If you are using toggling and you require an "all" button, it is recommended to list out all your filters as the command, rather than using the `all` keyword.

For example:

```<span class="filter" data-filter=".fasion, .portait, .stills, .landscape">Show All</span>```

I appreciate this is not ideal however and I will look into a possible work around for our next major release.

**Comment by patrickkunka** [comment]
https://github.com/patrickkunka/mixitup/commit/26eb888055d0618c2380ce9a5a8a3b3314627de0 - "filter" buttons and "toggle" buttons will be seperated in v3. Also `controls.toggleDefault` option added to determine what the default should be when all toggles are off.

**Comment by patrickkunka** [comment]
https://github.com/patrickkunka/mixitup/releases/tag/v3.0.0
