### ISSUE TITLE
Setting multiple filters as default with toggleFilterButtons and or logic does not work

### ISSUE THREAD

**Issue by phw** [patrickkunka/mixitup#209]
If I have two filter buttons, one filtering for `category-1` and one for `category-2` and I use `toggleFilterButtons: true` I would expect to be able to set a default filter like `.category-1,.category-1`. 

```JavaScript
element.mixItUp({
  load: {
    filter: '.category-1,.category-1'
  },
  controls: {
    toggleFilterButtons: true,
    toggleLogic: 'or'
  }
})
```

However, this does not trigger the two filter buttons to be set as default. It looks like it works correctly when using the `and` operator.

**Comment by patrickkunka** [comment]
Could you post an example? As far as I know, MixItUp already covers this functionality:

http://codepen.io/anon/pen/gpojdm

**Comment by phw** [comment]
Upon further investigation it was actually a timing issue where my call to `multiMix` came too early.

I do something like this:
http://codepen.io/anon/pen/RPxYWV

I have a refresh function that gets called once my data is ready. Sometimes this happened pretty fast, causing some kind of race condition. That it worked for "and" and not for "or" was just some funny coincidence in the timing (probably because https://github.com/patrickkunka/mixitup/blob/master/src/jquery.mixitup.js#L551 has slightly more work to do for "and"). I have now added a timeout to my refresh which is a workaround I can live with. So not really a bug but a usage issue.

Anyway, is there a clean way to call refresh only after the initialization is guaranteed to be finished?

**Comment by patrickkunka** [comment]
Yes - you should use a callback. I don't know how you are pulling in your data but it sounds like you are using an Ajax request of some sort. Most Ajax interfaces will provide an "oncomplete" callback function that you can hook into.

Once your data has downloaded, you can either initialize MixItUp then, or call your custom refresh function.
