### ISSUE TITLE
add event for animation complete

### ISSUE THREAD

**Issue by ChristianSchramm** [patrickkunka/mixitup#210]
Could you include an event, that is callled, each time the whole mixitup animation is completed? The Event onMixEnd calls on each element, so every function i'd like to use on it, is called multiple times.

**Comment by patrickkunka** [comment]
Hi - this is not correct. The 'onMixEnd' callback or 'mixEnd' event is called/fire only when the entire animation is complete. Perhaps you are binding it multiple times?

See this example:

http://codepen.io/patrickkunka/pen/oXOPPX
