### ISSUE TITLE
Remember filter state, on hitting "Back" button

### ISSUE THREAD

**Issue by drawcard** [patrickkunka/mixitup#212]
Hi, 

I was wondering if it's possible for the filter functionality to remember what filter is used when a user navigates away from the page. The scenario I'm facing is:

Default filter view is "All items" with "Featured items" as a filter toggle
1) User clicks the "Featured items" toggle.
2) User selects an item in that filter and is taken to another page
3) User hits Back button in browser
4) The page reloads and "All Items" is active.

What I'd like to do is have item 4) remember the "Featured Items" active state.

**Comment by drawcard** [comment]
Just another thought on this, I wonder if this could be achieved by using anchors:

1) User clicks filter button which has an <a> anchor attribute
2) This adds an anchor to the URL: eg. www.website.com/#featured-items
3) If the user navigates back to the page, it will load the anchor link triggering the view

The advantage to that is that you can also use that anchor to link elsewhere on the site and trigger that view on page load, if desired.

**Comment by patrickkunka** [comment]
Hello,

Yes this is possible using the `load.filter` configuration property. You can set this to be whatever value you wish when you instantiate MixItUp.

You just need to write some custom code to pull that filter value out of the URL before you instantiate MixItUp.

Some example URLs:

www.mywebsite.com/events/#october/
www.mywebsite.com/events/october/

In each of these examples the final segment of the URL is parsed into a the load filter for MixItUp. The first one uses a hash, and the second one would use the HTML5 history API and/or custom server-side route params.

You would first have to write some code to parse the URL to get the hash or final segment, and the prepend a '.' to it:

```
var loadFilter = 'october';
var filterString = '.' + loadFilter; // '.october'

$('#container').MixItUp({
    load: {
        filter: filterString
    }
});
