### ISSUE TITLE
Bootstrap with MixItUp logic checkbox

### ISSUE THREAD

**Issue by Guteloo** [patrickkunka/mixitup#216]
Hi
I’m using the MixItUp multi filter with chekboxes on my website to display bootstrap blocks. My filter working without logic. My pen: http://codepen.io/Gute/pen/EVPJOB/

How do it logic? like this: http://codepen.io/patrickkunka/pen/iwcap

**Comment by patrickkunka** [comment]
You may want to check out the [MultiFilter](https://www.kunkalabs.com/mixitup-multifilter/) extension for MixItUp 3, released today.
