### ISSUE TITLE
Togglable Sort Controller 

### ISSUE THREAD

**Issue by kydells** [patrickkunka/mixitup#217]
I would love to use a single sort div that changes state between ascending and descending on click.
I've tried editing the `data-sort` attr and replacing the entire div with `live = true`, but to no avail.

Thanks for any help you can offer.

**Comment by patrickkunka** [comment]
Hi kydells,

This is something that would have be done through the API, with a little bit of custom code.

Here's an example:

http://codepen.io/patrickkunka/pen/wKWYrP
