### ISSUE TITLE
MixItUp v2.1.10 is not compatible with Apple devices running iOS9

### ISSUE THREAD

**Issue by davelaflam** [patrickkunka/mixitup#219]
I have tested MixItUp v2.1.10 on various Apple devices, iPhone, iPad and iPad Air and MixItUp v2.1.10 is not compatible with the latest iOS9 (v9.0 & v9.0.1) software, however using MixItUp2 v2.1.9 works fine with iOS9. 
It appears that this repo just bumped MixItUp to v2.1.10 within the last month prior to when iOS9 was released about 1-2 weeks ago so you probably need to re-test against all devices to ensure compatibility.
Here's where I found the earlier versions of MixItUp - https://cdnjs.com/libraries/mixitup

**Comment by patrickkunka** [comment]
Thanks for finding this and your thorough testing!

Have just pushed a patch for the issue in https://github.com/patrickkunka/mixitup/releases/tag/v2.1.11

Let me know if this works for you.

**Comment by davelaflam** [comment]
:+1: seems to be working great, Thanks for the quick update!

**Comment by wlanni** [comment]
@davelaflam Can you post what issue you were running into? I'm trying to figure out whether an issue I'm experiencing on an iPad not resetting the width/height of images when their Mix filter is activated is an iOS thing or not.

**Comment by patrickkunka** [comment]
Hello wlanni, this was a fatal error related to Safari's implementation of ES5 strict mode and removing data attributes from DOM elements. Your issue sounds like it is most likely not related to MixItUp as MixItUp by default does not affect the styling of elements other than changing their `display` attribute.
