### ISSUE TITLE
bug report: instance is undefined at line 2036 with 2.1.11

### ISSUE THREAD

**Issue by cipherchien** [patrickkunka/mixitup#220]
Hi, I just include jquery.mixitup.js to my project then got the issue immediately.

in jquery.mixitup.js line: 2036
var data = instance[args[0]](args[1], args[2], args[3]);

![2015-10-09 9 11 44](https://cloud.githubusercontent.com/assets/1157044/10383784/e8a47fc4-6e65-11e5-90d4-e69df9a2c429.png)

mixitup version: 2.1.11
os: mac OS X Yosemite 10.10.5
browser: firefox 41.0.1
jquery version: 2.1.4

**Comment by patrickkunka** [comment]
Hi - Sounds like you might be calling a MixItUp method before you have instantiated MixItUp on a container.

Please checkout the getting started guide:
https://mixitup.kunkalabs.com/learn/tutorial/get-started/

You must call `$('#Container').mixItUp();` before calling any other methods.
