### ISSUE TITLE
MixItUp with Jets.js

### ISSUE THREAD

**Issue by Dylan-Chapman** [patrickkunka/mixitup#225]
I'm using Jets.js for searching (I prefer the performance boost over JS for large lists and I don't mind the lack of animation on searching). Jets.js searches via inline style tags a-la

``` css
#jetsContent > :not([data-jets *= "search_query"]){ display:none; }
```

Obviously, this doesn't work because MixItUp uses inline style tags for setting the display. In Jets, I can therefore request it add !important to its display: none declaration.

However, when doing this, MixItUp stops working. When using the debugger, I see that after searching with Jets, "[MixItUp][element][_cleanUp] The operation completed successfully." no longer fires. I'm guessing MixItUp has some issue with visibility mismatches? 

Is there a way around this?

**Comment by patrickkunka** [comment]
Closing for now as MixItUp 3 no longer requires the setting of `display: none` on elements. Please comment if still an issue.
