### ISSUE TITLE
Disable loading animation

### ISSUE THREAD

**Issue by eablokker** [patrickkunka/mixitup#228]
Can't see a way to disable the initial loading animation. Request to add that feature.

**Comment by sharathdaniel** [comment]
Any update on this?

**Comment by patrickkunka** [comment]
You can just disable animations and reactivate them using the onMixLoad callback

**Comment by hemant2586** [comment]
You can disable animations for loading, and then enable for subsequent operations as below

```
$('#Container').mixItUp({
    animation: {
        enable: false
    },
    callbacks: {
        onMixLoad: function(){
            $(this).mixItUp('setOptions', {
                animation: {
                    enable: true
                }
            });
        }
    }
});
```

**Comment by patrickkunka** [comment]
FYI - the above snippet applies to v2. In v3 there are no loading animations by default as the factory API is now synchronous.

A loading animation may be added as per this demo.
https://demos.kunkalabs.com/mixitup/loading-animation/
