### ISSUE TITLE
Adding Flexbox Vendor Prefixes

### ISSUE THREAD

**Issue by Skinwalker** [patrickkunka/mixitup#230]
Is it possible to add the Vendor Prefixes for the Flexbox Layout?

The Script only adds **block: flex** to the elements.

I tried to add the prefixes via jQuery's css methods but that doesn't work.

**Comment by patrickkunka** [comment]
MixItUp doesn't add anything to your elements other that what you specify via the `layout.display` configuration option.

However, you can then use modernizr or similar to feature detect what prefix (if any) is needed for the user's browser and set that as the `layout.display` value.
