### ISSUE TITLE
Animation positions slightly off when browser window height tall enough to not have scroll bar

### ISSUE THREAD

**Issue by eablokker** [patrickkunka/mixitup#231]
This is a weird one, but I believe it is related to how the window width is calculated depending on if a scroll bar is present or not. If I shrink my browser height to where it has a scroll bar, the items animate perfectly into the right locations. When my browser window is taller, and there is no scroll bar, the items sometimes animate into positions that might be 5-10px off from where they should be, and then snap into the right place a second later.

Just checked, and it also happens on the MixItUp home page demo in Chrome when you switch from blue to green filters. Because the MixItUp page is very long, it always has a scroll bar. If you delete all the content below in Chrome inspector, so there is no scroll bar, you will start to see it at certain window widths, especially in a mobile width.

Here's a gif of what I mean.
![giphy](https://cloud.githubusercontent.com/assets/2616961/11825634/0e74d2ea-a335-11e5-82ad-4e60a266b9c9.gif)

**Comment by patrickkunka** [comment]
Unfortunately the change in viewport width as a result of in-chrome scroll bars being added/removed is not something we can control or detect easily, and as you have shown can cause animation paths to be miscalculated. I recommend avoiding any sort of above-the-fold layout that could result in a dramatic height change this reason.
