### ISSUE TITLE
Remove jQuery dependency

### ISSUE THREAD

**Issue by igregson** [patrickkunka/mixitup#232]
I'd love to be able to use MixItUp on projects that aren't using jQuery. Any others interested in this? 

Such would no doubt require quite a refactor, so I'm not sure if it would ever be considered. Still seemed worth a mention.

**Comment by patrickkunka** [comment]
MixItUp 3 will be released early next year which is jQuery free.

You can already check out the v3 branch, but unfortunately there is no documentation yet (obviously the api is different).

Thanks

**Comment by igregson** [comment]
Great news! Look forward to v3!

**Comment by patrickkunka** [comment]
Just letting you know that v3 is now live.

https://github.com/patrickkunka/mixitup/
