### ISSUE TITLE
how to remove an element dynamically?

### ISSUE THREAD

**Issue by apfz** [patrickkunka/mixitup#233]
how do I remove an element, and update the layout in a dynamic way? 

right now, I am just calling .remove() on the element I want to remove, but there is no animation effect like is the case with mixItUp('insert', 0, new_element);

**Comment by patrickkunka** [comment]
Hello Apfz,

Good question -

In v2 the best way to do this is to firstly filter out the element in question by using a :not(#uniqueId) selector or similar, and then delete it from the DOM on callback, and finally refresh the MixItUp instance, to reindex the remaining targets.

In our upcoming v3 release, this functionality is significantly improved and will be the default behavior of the .remove() API method.

**Comment by apfz** [comment]
Hi Patrick.

Thanks, that does the trick.

btw, great work on the plugin. Looking forward to v3.
