### ISSUE TITLE
Change thumbs movement to fade animation

### ISSUE THREAD

**Issue by mariusin** [patrickkunka/mixitup#239]
Thanks for superb script. 

Is it posible to remove thumbs movement and change it to fade animation?

I found some workaround by using:

```
animation: {
    enable: false,
}
```

And added this for main container on callbacks:

```
onMixStart: function(){
  $('ul.Filtered').fadeTo( "fast" , 0.0);
},
onMixEnd: function(){
  $('ul.Filtered').fadeTo( "slow" , 1.0);
}
```

It works, BUT if you are changing filter too fast usually it fails and doesn't fades. Any help?

**Comment by patrickkunka** [comment]
setting the new `animation.nudge` congiruation option to false can prevent unwanted lateral movement, but target translation is a core feature of MixItUp. If you don't require this sort of animation, you can simply filter your targets with querySelectorAll and apply styling classes to fade elements out as needed.
