### ISSUE TITLE
'and' logic with buttons and dropdown

### ISSUE THREAD

**Issue by sistercylon** [patrickkunka/mixitup#240]
This is almost working for me, but not quite. The buttons are acting up in that they start to filter properly, and then they reset. The reset button reveals all items like it’s supposed to, then it undoes that. All the buttons seem to do this and I can’t figure out why. The way this is supposed to work is that any filters can be combined and if nothing matches, then an alert is shown (I’ll change the alert to a page-level object later). This was working successfully until I tried to integrate my code with the js of [this codepen](http://codepen.io/patrickkunka/pen/hueKl/). Here is my codepen with the messed up functionality I just described. Any help would be appreciated!

<a href="http://codepen.io/sistercylon/pen/mPRXZY" rel="nofollow">http://codepen.io/sistercylon/pen/mPRXZY</a>

**Comment by patrickkunka** [comment]
A bit late, but you may wish to check out the [MultiFilter](https://www.kunkalabs.com/mixitup-multifilter/) extension, released today.
