### ISSUE TITLE
Disable click on not matching filters 

### ISSUE THREAD

**Issue by bgolubovic** [patrickkunka/mixitup#241]
Hello all,

I am using this MixItUp script for filtering. I need function, option, that will disable click on filters that not have matched items.
I am using multi filtering option.

` var buttonFilter = {

  // Declare any variables we will need as properties of the object

  $filters: null,
  $reset: null,
  groups: [],
  outputArray: [],
  outputString: ''

  // The "init" method will run on document ready and cache any jQuery objects we will need.

  init: function(){
    var self = this; // As a best practice, in each method we will asign "this" to the variable "self" so that it remains scope-agnostic. We will use it to refer to the parent "buttonFilter" object so that we can share methods and properties between all parts of the object.

```
self.$filters = $('#Filters');
self.$reset = $('.reset-drop-filter');
self.$container = $('#Container');

self.$filters.find('.list-group').each(function(){
  self.groups.push({
    $buttons: $(this).find('.filter')
    active: ''
  });
});

self.bindHandlers();
```

  }

  // The "bindHandlers" method will listen for whenever a button is clicked. 

  bindHandlers: function(){
    var self = this;

```
// Handle filter clicks

self.$filters.on('click', '.filter', function(e){
  e.preventDefault();

  var $button = $(this);

  // If the button is active, remove the active class, else make active and deactivate others.

  var liLength = $button.parents('ul').find('li .filter');

  $button.hasClass('active') ? $button.removeClass('active') : _removeActive();
  function _removeActive() {
    $.each(liLength, function(index, value){
        $(value).removeClass('active');
    });
    $button.addClass('active');
  };

  self.parseFilters();
});

// Handle reset click

self.$reset.on('click', function(e){
  e.preventDefault();
  var thisElement = $($(this)[0].previousSibling.previousElementSibling);
  //console.info(thisElement.find('.filter'));

  //self.$filters.find('.filter').removeClass('active');
  thisElement.find('.filter').removeClass('active');

  self.parseFilters();
});
```

  },

  // The parseFilters method checks which filters are active in each group:

  parseFilters: function(){
    var self = this;

```
// loop through each filter group and grap the active filter from each one.

for(var i = 0, group; group = self.groups[i]; i++){
  group.active = group.$buttons.filter('.active').attr('data-filter') || '';
}

self.concatenate();
```

  },

  // The "concatenate" method will crawl through each group, concatenating filters as desired:

  concatenate: function(){
    var self = this;

```
self.outputString = ''; // Reset output string

for(var i = 0, group; group = self.groups[i]; i++){
  self.outputString += group.active;
}

// If the output string is empty, show all rather than none:

!self.outputString.length && (self.outputString = 'all'); 

//console.log(self.outputString); 

// ^ we can check the console here to take a look at the filter string that is produced

// Send the output string to MixItUp via the 'filter' method:

  if(self.$container.mixItUp('isLoaded')){
    self.$container.mixItUp('filter', self.outputString);
  }
```

  }
};

// On document ready, initialise our code.

$(function(){

  // Initialize buttonFilter code

  buttonFilter.init();

  // Instantiate MixItUp

  $('#Container').mixItUp({
    controls: {
      enable: false // we won't be needing these
    },
    callbacks: {
        onMixEnd: function(state){
            alert('No elements found matching '+ state.fail);
        }
    }
  });  
}); ` 

I need it like when you select one filter, if other filters don't have matched items to be unclickable.

Thank you.

**Comment by patrickkunka** [comment]
This kind of functionality is out of the scope of MixItUp. You can build your own custom UI to implement this behavior and interface with MixItUp via its API.
