### ISSUE TITLE
mixitup failed on initialization

### ISSUE THREAD

**Issue by ejlocop** [patrickkunka/mixitup#242]
Hi, why is `mixItUp` always fail when i just instantiated it? 
here's my code
```html
<ul class="wow" id="wow">
 <li class="One">One</li>
 <li class="Two">Two</li>
 <li class="Three">Three</li>
 <li class="Four">Four</li>
 <li class="Five">Five</li>
 <li class="Six">Six</li>
</ul>
```
```javascript
$('#wow').mixItUp();
// fails, and also when i tried to filter one item
$('#wow').mixItUp('filter', '.One');
// not working also, 
```

can you help me how to properly use this? i dont know what cause mixItUp not to work properly.
thanks!

**Comment by patrickkunka** [comment]
Hi,

Your syntax all looks good but your target elements (in your case the `<li>`s), need to have the class `"mix"` in addition to your other classes for MixItUp to index them correctly.

**Comment by ejlocop** [comment]
@patrickkunka thanks, it worked,

just a question, is there a way i can filter `mixItUp` without using `id` or `class` selectors? 
can i use my custom data-attribute ?

**Comment by patrickkunka** [comment]
Yes - you can use any valid selector you want.

A data attribute would look like this:

$('[data-foo="bar"]').mixItUp();

Or if you have multiple values in your attribute:

$('[data-foo~="bar"]').mixItUp();

**Comment by ejlocop** [comment]
@patrickkunka i'm sorry, i think you didnt get my question.
what i mean is, if i can use data-attribute in my filter search?

like this.
instead of using
```javascript
$('#Container').mixItUp('filter', '.category1');
```
can i use 
```javascript
$('#Container').mixItUp('filter', '[data-category1=1][data-category2=5]');
```

**Comment by patrickkunka** [comment]
Ah OK,

Yes - just make sure you're using the correct syntax which is:

`$('#Container').mixItUp('filter', '[data-foo="bar"]');`

I believe the double quotes around the attribute value are necessary for it to be a valid attribute selector. You can also filter on the presence of an attribute alone (regardless of value) like this:

`$('#Container').mixItUp('filter', '[data-foo]');`

And as per your example above, you can also combine attribute selectors to create AND or OR logic:

`$('#Container').mixItUp('filter', '[data-foo][data-bar]'); // AND logic`
`$('#Container').mixItUp('filter', '[data-foo], [data-bar]'); // OR logic`

**Comment by ejlocop** [comment]
thank you @patrickkunka !
i dont want to mess up my `class=""` attr :smile: 


also, just thinking, it would be nice if mixItUp has a function that will filter search through a json string like this
```html
<div id="container">
 <div class="mix" data-filtering="{some json data here}"></div>
 <div class="mix" data-filtering="{some json data here}"></div>
 <div class="mix" data-filtering="{some json data here}"></div>
</div>
```
so we dont have to mess up our mix item,
what do you think? :smile: 

btw, :+1: for your `mixItUp` 
thanks!
