### ISSUE TITLE
user agent detection fails if Random Agent Spoofer is active

### ISSUE THREAD

**Issue by c33s** [patrickkunka/mixitup#243]
having [RAS](https://github.com/dillbyrne/random-agent-spoofer) active, breaks the mixitup user agent detection. [Random Agent Spoofer](https://addons.mozilla.org/en-US/firefox/addon/random-agent-spoofer/) is a firefox extension for randomize the useragent.

```
TypeError: window.navigator.userAgent.match(...) is null
a.MixItUp.prototype._platformDetect()
 dep.min.js:1
a.MixItUp.prototype._init()
 dep.min.js:1
a.fn.mixItUp/f()
 dep.min.js:2
a.fn.mixItUp/c<()
 dep.min.js:2
.each()
 jquery.min.js:2
n.prototype.each()
 jquery.min.js:2
a.fn.
```

also opend an issue there: https://github.com/dillbyrne/random-agent-spoofer/issues/395

**Comment by patrickkunka** [comment]
Thanks for the heads up. Our upcoming v3 release no longer uses user agent sniffing so hopefully this will soon no longer be an issue.

**Comment by patrickkunka** [comment]
https://github.com/patrickkunka/mixitup/releases/tag/v3.0.0
