### ISSUE TITLE
Exclude/hide filtering on view all

### ISSUE THREAD

**Issue by candyshien** [patrickkunka/mixitup#244]
I would like to ask, I Define Filter on Load... Show the filter category I want, If I click on view all how could I not showing a filter of the category.

Meaning, I have ".category_1" ".category_2" ".category_3" ".category_4"

Define Filter on Load, show All category ".category_1,.category_2,.category_3,.category_4",

after click on "View All" show All category and  hide / not showing only ".category_4"

**Comment by patrickkunka** [comment]
Hi there - would you be able to post a codepen or jsfiddle example, showing the issue?

**Comment by candyshien** [comment]
I solve it with :not(.category_4)

**Comment by xkoozoo** [comment]
@candyshien can you provide some example how you did it please?

**Comment by patrickkunka** [comment]
```html
<button type="button" data-filter=".mix:not(.category_4)">View All</button>
```

.. I presume

**Comment by xkoozoo** [comment]
@patrickkunka omg so simple after 2 days of experimenting with jQuery. Thank you!

**Comment by syedsimanta03** [comment]
@patrickkunka   what if I want to hide more than one category cat4,cat2,

**Comment by patrickkunka** [comment]
I think it should be:
```html
<button type="button" data-filter=".mix:not(.category_4, .category_3)">View All</button>
```
Or, if not,
```html
<button type="button" data-filter=".mix:not(.category_4):not(.category_3)">View All</button>
```
