### ISSUE TITLE
Doesn't work in IE9

### ISSUE THREAD

**Issue by emilygreenaway** [patrickkunka/mixitup#245]
The website says "Functional in IE8+ with animations disabled, fully functional IE10+" but I can't get any example to work in IE9.

Does it work in IE8 and IE9? If so can someone link me to an example that I can view in IE9.

Codepen and your website don't work in IE9.

**Comment by patrickkunka** [comment]
Hi,

Yes MixItUp does work in IE8 and IE9, but all actions are performed instantly/synchronously as these browsers do not support CSS transitions.

Please view the getting started codepen in IE9 as an example:
http://codepen.io/patrickkunka/full/KisAG/

Note the "full" view URL must be used as the codepen app only works in IE10+, as does our marketing website (as you mentioned)
