### ISSUE TITLE
Active filter Null when clicking on a button with data‑filter attribute

### ISSUE THREAD

**Issue by hartey11** [patrickkunka/mixitup#246]
Hi,

I've gone through the get started tutorial and the filtering is working on load. However, when I click one of my filter button its not getting the value from the button.

I need the month filters but I dont need any ordering, is this required?

the page im trying to get it to work on is here:
http://jazz-cafe.kotadev.co.uk/whats-on

and the jquery that initializes it is:

`$('#events-list').mixItUp({
        controls: {
            activeClass: 'on'
        },
        load: {
            filter: '.highlight'
	    },
        callbacks: {
		onMixEnd: function(state){
			console.log(state)
		}
	}
    });`

**Comment by patrickkunka** [comment]
Hi there,

I think the issue might be the structure of your filter button markup. Could you try making the buttons siblings (rather than each one nested in its own <li> element) and let me know if that makes a difference?

**Comment by hartey11** [comment]
That's helped a bit. The on class is now being added to the buttons but it's still returning null in activeFilter

**Comment by patrickkunka** [comment]
I've had another look. I haven't seen this before so I'm not quite sure what's going on - but I don't think MixItUp is the issue. For some reason the data attributes you've added to your buttons aren't valid.

You can test with a standard jQuery `data` call -

`$('.filter').eq(2).data('filter')` and you'll see it returns `undefined`

If you edit/delete/re-add the attributes in Chrome web inspector, you'll see that they then start to work. Not sure what could be causing it but perhaps some sort of character encoding or html compression? It could also be another script on the page interfering. I would recommend building a working, stripped down version if you can, and then re-add other elements until you can identify the issue.

**Comment by hartey11** [comment]
Hi, yes it was the encoding of "data-filter" in my HTML. When i ran it through a hardcoder it returned " data&#8209;filter". I copied this from the documentation, just so you're aware.

**Comment by patrickkunka** [comment]
Cool - glad you got it working. New documentation site on the way with v3, so I'll make sure all the code snippets are encoded correctly.
