### ISSUE TITLE
Ensure container height larger than items

### ISSUE THREAD

**Issue by CupOfTea696** [patrickkunka/mixitup#248]
When hiding / showing items it happens sometimes that the container's height changes faster than the items' opacities. This causes items to get "cut off" at the bottom. I removed the `fade` effect to make this issue more visible.

I'm using a flexbox layout.

My Configuration:

``` js
{
    animation: {
        effects: 'stagger(50ms) scale(0.5)',
        duration: 40000,
        easing: 'ease',
        perspectiveOrigin: '50% 0',
        animateChangeLayout: true,
        animateResizeTargets: true
    },
    controls: {
        enable: false
    },
    layout: {
        display: 'block',
        containerClassFail: 'empty'
    },
    selectors: {
        target: '.feed-item'
    }
}
```

![screen shot 2016-06-29 at 11 21 12](https://cloud.githubusercontent.com/assets/7327050/16448895/e8b7e806-3deb-11e6-8d2e-3d6896731d5d.png)

**Comment by patrickkunka** [comment]
The best solution to this problem is to apply a min-height to your container to ensure that elements are never "cut off"

**Comment by CupOfTea696** [comment]
I can't really do that, this page has dynamic content. This would cause the page to on occasions have a way larger height than necessary, and on other occasions the min-height might not be enough and I'd still have this issue. I hope you can consider reopening this issue.

**Comment by patrickkunka** [comment]
Thanks for the additional information - that's very useful. Does your project require `overflow: hidden;` on your container?

**Comment by CupOfTea696** [comment]
It does, yeah.

**Comment by patrickkunka** [comment]
Would you mind sending me a link to the page (if its live)?

**Comment by CupOfTea696** [comment]
Unfortunately I can't, this was client work for a campaign site, and the campaign has ended so we took the site down.

**Comment by tsawitzki** [comment]
@CupOfTea696 Would be curious to find out what you did to overcome the problem …?

**Comment by CupOfTea696** [comment]
@tsawitzki I don't have a solution. The site went live with the bug.

**Comment by Kwapi** [comment]
I might have a similar issue. When I change the page on my news section the whole mixitup container seems to disappear for a split second. I tried adding min-height to both the mixitup container and the parent div but nothing works.

Here's the video of the issue:
[Google drive link ](https://drive.google.com/open?id=0ByCOhROBhow9UHNmTWk5S2hRUk0)

**Comment by tsawitzki** [comment]
@Kwapi can you give some information on how you specified the min-height? Did you use % or vh units? Maybe in case of % there is no relation as to what the min-height refers to?
Maybe you need to wrap something around the whole mixitup container and specify the min-height there? In your video even the whole footer moves up, so I was thinking there is some issue with the general html/css architecture maybe?

**Comment by patrickkunka** [comment]
Hi @Kwapi - this isn't related to the issue above, but is more likely a markup structure issue. Would you be able to share a link to your project? (also if you could open a new issue for it that would be great). Thanks.

**Comment by Kwapi** [comment]
@tsawitzki @patrickkunka 
I answered your questions and moved the issue to [here](https://github.com/patrickkunka/mixitup/issues/369)
