### ISSUE TITLE
IE10 + display: flex - I need a fallback

### ISSUE THREAD

**Issue by MartinMuzatko** [patrickkunka/mixitup#249]
Hello there!

I discovered, that, while flex works perfectly in Chrome it doesn't work in IE10, and if I use `display: -ms-flexbox` it works in IE10, but - you guessed it - nowhere else :)

So, I can't pass something like 

```js
$('#mixitup').mixItUp({
    layout: {
        display: ['flex', '-ms-flexbox']
    }
})
```

As a workaround, can I somehow add a class when items are visible or not? At least then I can provide the fallback myself.

TY in advance

**Comment by patrickkunka** [comment]
Hi Martin - 

You can feature detect IE10 in your project's JavaScript and then use a variable to define the display value.

```js
var display = isIE10? '-ms-flexbox' : 'flex';

$('#mixitup').mixItUp({
    layout: {
        display: display
    }
})
```
