### ISSUE TITLE
Several lists with pagination are paginated all at once

### ISSUE THREAD

**Issue by fschwahn** [patrickkunka/mixitup#250]
If I have a page where I have two lists with mixitup, and both of them have pagination, clicking a pager link on one of the lists changes the page on that list, as well as on the other list.

I'd expect the pagination links only to apply to the list they belong to.

Versions used:
MixItUp Pagination v1.1.0
mixitup 2.1.11

**Comment by fschwahn** [comment]
Ok, same solution as with #49 - though the behavior is pretty surprising - I wonder why the selectors are not scoped to the parent element?

**Comment by patrickkunka** [comment]
This is to allow's the freedom to place your pager UI wherever you want in the document, but appreciate it's not intuitive. They will be locally scoped in the pagination extension for the upcoming MixItUp v3 - with a config option to make them global.

**Comment by fschwahn** [comment]
Ah, I understand - same should be true for all selectors (target, filter, sort, ...), right? I think the config option is the right way to go - I now have a weird workaround in place where I generate the class-names, so I'm looking forward to the new version.
