### ISSUE TITLE
broken links at plugins.jquery.com

### ISSUE THREAD

**Issue by trevorsammis** [patrickkunka/mixitup#252]
The "View Homepage" and "Read The Docs" links at http://plugins.jquery.com/mixitup/ point to mixitup.io, which is no longer.

**Comment by patrickkunka** [comment]
Thanks for letting me know. Looks like the jQuery plugins register is in "read-only" mode now and no longer maintained. Since we've just dropped jQuery, hopefully no longer relevant.
