### ISSUE TITLE
I need to use webpack... How to import??

### ISSUE THREAD

**Issue by WriterLuo** [patrickkunka/mixitup#253]
I need to use webpack... How to import??  
Thinks

**Comment by patrickkunka** [comment]
Hi,

Please see this issue for an explanation of why MixItUp hasn't been added to NPM yet.

https://github.com/patrickkunka/mixitup/issues/188

Unfortunately MixItUp 3 has been delayed quite a bit, but I'm aiming for a beta release at the end of this month.

Thanks
