### ISSUE TITLE
Static/Fixed elements (stay in place)

### ISSUE THREAD

**Issue by MartinMuzatko** [patrickkunka/mixitup#256]
Hello there!

I'd love to add an item to my mixitup that stays in place - no matter which filters are applied.
I can accomplish, that it is always shown, but not that it stays in the same place (say 2. place)

It would easily work, if it had to be the first or last item, but in this case, it has to be the second.
So sometimes when the first item gets filtered away - the second item slides to position 1.

Is there currently a workaround/option to have fixed/static positioned elements? (as in order, not css position: fixed; )

Update: I think I could achieve it, by dynamically assigning a sort data attribute.

Thank you a lot in advance!

**Comment by patrickkunka** [comment]
Hi Martin,

Your solution of dynamically changing the sort attribute could definitely work (if you haven't already implemented it). You could also use your own sorting algorithm to sort elements into the desired order (ensuring target x is always at index 1) before sending to the sort API as an element collection/list.

You'll see the .sort() API method now accepts an element collection as an argument:

https://www.kunkalabs.com/mixitup/docs/api-methods/
