### ISSUE TITLE
data-filter should work with other data (request)

### ISSUE THREAD

**Issue by Nic787** [patrickkunka/mixitup#258]
Hi,

that's very weird that data-filter is working with categories. What about something like : 

data-filter="cat:Categorie1, Categorie2" (for multiple categories)

and instead of using class="Categorie1" for your block, you could use data-cat="Categorie1, Categorie2"

It will be helpfull instead of creating multiple class for a single item.

Thank you

**Comment by patrickkunka** [comment]
You may use any combination of classnames or attribute selectors to achieve multi-category filtering. Please check out the [Filtering with MixItUp](https://www.kunkalabs.com/tutorials/filtering-with-mixitup/) tutorial for more information.
