### ISSUE TITLE
Multiple dropdown select filter issue on firefox

### ISSUE THREAD

**Issue by Asato-Gorilla** [patrickkunka/mixitup#259]
Hi,

I have integrated mixitup in to WordPress and filtering with a three select menu generated from categories, This actual action of filtering works fine but once the animation has finished the filtered items fade away. It works fine in Chrome, Safari and Opera. I have noticed that a class of fail is added to the container.

Link to the page where i'm using mixitup : 
http://www.beta-otc.fr/fouilleul/wp/?post_type=matiere_premiere

thank you

**Comment by scallahan-dev** [comment]
I noticed the same issue. Here is a link to it on our page:

http://www.cybernetman.com/en/all-in-one-pc

**Comment by scallahan-dev** [comment]
@Asato-Gorilla Found the solution here:

https://mixitup.kunkalabs.com/support/topic/dropdown-filter-not-working/

This solved my problem!

**Comment by Asato-Gorilla** [comment]
@scallahanCybernet thanks a lot, but I can't use this solution, I have 3 dropdowns that must be combined to filter my results and this solution does not allow to do so. I tried anyway to use this technique but it does not change my problem, the results disappear after sorting on firefox.

@patrickkunka Any idea ?

**Comment by patrickkunka** [comment]
The multi select codepen solutions from MixItUp 2 have now been superseded with the MultiFilter extension for MixItUp 3, released today.

Check out https://www.kunkalabs.com/mixitup-mulfitiler/ for more information.
