### ISSUE TITLE
After animation, elements disappear in IE

### ISSUE THREAD

**Issue by scallahan-dev** [patrickkunka/mixitup#260]
Hi,

It looks like after selecting a filter in IE (V10 tested), all of the elements disappear after the animations complete. Here is the page:

http://www.cybernetman.com/en/all-in-one-pc

Thanks,
Sean

**Comment by scallahan-dev** [comment]
This issue actually occurs in Firefox as well.

**Comment by scallahan-dev** [comment]
Duplicate of Issue #259

**Comment by scallahan-dev** [comment]
Found the solution here:

https://mixitup.kunkalabs.com/support/topic/dropdown-filter-not-working/

This solved my problem!

**Comment by paulmist** [comment]
What was the solution? The URL above no longer works

**Comment by patrickkunka** [comment]
Hi @paulmist,

Which version of MixItUp are you using? Unfortunately our old support forums are no longer available, but anything found there refers to v2 only.

I'd be happy to help you if want to open a new issue with a link to your project or a JSFiddle reproducing the issue.

**Comment by paulmist** [comment]
It is for an older 2.x version.

We're looking into updating in order to fix this.

Thank you, @patrickkunka

**Comment by patrickkunka** [comment]
OK - hopefully that fixes it. Let me know if otherwise.
