### ISSUE TITLE
Display elements filtered out at the end with a given opacity

### ISSUE THREAD

**Issue by gaborka6** [patrickkunka/mixitup#261]
Hi!
This plugin is awesome!
Im wondering how could I display elements filtered out, but arranging them at the end with opacity 0.4?
So basically everything remains visible, but order and opacity changes.
Example: if im filtering apples they go to the beginning and bananas oranges etc to the end with 0.4 opcaity.

**Comment by patrickkunka** [comment]
I would suggest the following:

- Use MixItUp only to sort the container
- Use the sort API with an element collection to move the elements you want to fade out to the end of the list.
- On completion, query the DOM again for those elements, and apply a styling class via JavaScript to each of them which results in a reduced opacity.
- At the start of any subsequent operations, remove this styling class from all elements.
