### ISSUE TITLE
Having multiple mixItUps on the same page

### ISSUE THREAD

**Issue by halukkaramete** [patrickkunka/mixitup#262]
In MixItUp v2.1.6, on line 34, target is hardcoded to be '.mix' 

Is there a way to pass this target from the initiator call?
$('#portfolio-1-items').mixItUp(  _pass_that_target_class_name_somehow_from_here_ );  

I want to place 2 filter based implementations on the same page. I'm almost there, but when I click on the filter buttons on the 1st implementation, the 2nd ones' items also get filtered. That's not surprising cause both implementations have their div items coded to have the  'mix' class. I can change the mix class to something else but then the code would break due to line 34. 

I thought, if I can make the implementation 1's class as mix-1 and the other one as mix-2, and for each, use  
$('#portfolio-1-items').mixItUp( pass mix-1 here  );  
$('#portfolio-2-items').mixItUp( pass mix-2 here);  respectively, it should work. 

But is that possible?

**Comment by patrickkunka** [comment]
Hello, 

Yes it is possible and that is the correct approach. Please check out the configuration object documentation. The property you'll need is "selectors.target".

**Comment by patrickkunka** [comment]
Actually just re-reading your question. The issue is not your target selectors, but both MixItUp instances binding to the same filter controls.

This codepen demonstrates how to approach this problem.

 https://codepen.io/patrickkunka/pen/YyrmwM

**Comment by halukkaramete** [comment]
Thank you Patrick for the demonstration. That will lead the way.

**Comment by halukkaramete** [comment]
Hey, can you sign this petition? https://chn.ge/2OLbsRq

Thanks! - Karamete
