### ISSUE TITLE
Feature Request: Conditional Filters

### ISSUE THREAD

**Issue by tellstevens** [patrickkunka/mixitup#263]
This might be possible but I haven't seen any examples of this anywhere and I'm not a great coder. Ideally what I'd like to do is create conditional filters so that if I select option A on the first filter I'd get the second set of filters that relate to it. 

**Example**
Shape: Square, Circle, Diamond

if Square
Color: red, blue, green

if Circle:
Color: orange, white, black

if Diamond
Color: teal, pink, yellow

Any direction?

**Comment by patrickkunka** [comment]
Sorry but this is out of the scope of MixItUp. You can always build your own custom UI with this behavior which can interterface with MixItUp via its API.
