### ISSUE TITLE
will v3 have ability to drag and drop reorder? 

### ISSUE THREAD

**Issue by builtbylane** [patrickkunka/mixitup#265]

**Comment by patrickkunka** [comment]
Hi Lane,

Yes - it won't be part of the core in order to keep filesize down, but there will be a Drag & Drop extension, which I hope to launch shortly after the MixItUp 3 core.

Thanks

**Comment by patrickkunka** [comment]
Let me know if you'd be interested in beta testing it and I'll be sure to let you know when its ready.

**Comment by kevincampanella** [comment]
@patrickkunka I would be interested in beta testing the drag & drop extension when it is ready. Thanks!

**Comment by patrickkunka** [comment]
@kevincampanella sure - will do, thanks.
