### ISSUE TITLE
Problem with initializing on layout

### ISSUE THREAD

**Issue by minde281** [patrickkunka/mixitup#266]
It seems that if you initialize MixItUp with a spesific layout:
```
mixer = mixitup('#files-list', {
            layout:{
                containerClassName: "layout-list"
            }
        });
```

The state does not get that layout.
`console.log(mixer.getState().activeContainerClassName; // Gives: ""`

The MixItUp itself however does have the correct class "layout-list". This becomes a problem the first time you change a layout after page load, as the currently active layout is not removed.

As an example i have two types of layout: "layout-grid" and "layout-list".
Lets say i use "layout-list" in the init like above.
When i change to the "layout-grid" my MixItUp has both the "layout-grid" and the "layout-list"-class.

Also hopefully this can be fixed (or someone can help me understand what I'm doing wrong)

**Comment by patrickkunka** [comment]
Hi thanks for posting this. Confirmed and test added.

It's now been fixed in 3.0.1

https://github.com/patrickkunka/mixitup/releases/tag/v3.0.1

Let me know if it works for you.

**Comment by minde281** [comment]
Works like a charm. Thank you for the fast reply and fix!

**Comment by patrickkunka** [comment]
Excellent, thanks.
