### ISSUE TITLE
Bootstrap / MixItUp "data-toggle" Attribute Interference

### ISSUE THREAD

**Issue by UnrulyNatives** [patrickkunka/mixitup#268]
Immediate children of An element in DOM which has a ` data-toggle="buttons"` become activated and toggle visibility of the mixer's items. 
Just to give more details, the frontend framework used by me is Bootstrap 4 alpha 5.

I attempted to add 

    controls: {
        scope: 'local'
    }

to the initiating code, but the mixer didn't initialize with these lines. 

I also tried to paste some code from MixItUp 2:

,
        selectors: {

            filter: '.filter-btn',
            sort: '.sort-btn'
        }

but it didn't do any good either.

**Comment by patrickkunka** [comment]
Hi,

I came across this issue a few days ago with another bootstrap user. Bootstrap uses the attribute `data-toggle` internally, which interferes with MixItUp.

Use the `selectors.control` configuration option to specify an additional selector by which to restrict MixItUp controls. This can be a class name or attribute etc.

e.g.

```js
mixitup(container, {
    selectors: {
        control: '[data-mixitup-control]'
    }
}
```

```html
<button type="button" data-mixitup-control data-filter=".red">Red</button>
<button type="button" data-mixitup-control data-toggle=".blue">Blue</button>
<button type="button" data-mixitup-control data-sort="default:desc">Sort Desc</button>
```

FYI - this option was added in 3.1.0

**Comment by patrickkunka** [comment]
Assuming this fix has worked for you, let me know if otherwise and will reopen.

**Comment by hannahmwool** [comment]
This fixes the issue but makes the MixItUp pagination buttons not work and since they're auto-generated I can't add the "data-mixitup-control" to each one. Is there a config option to add to that or should I use jQuery to add "data-mixitup-control" to each button after load?

Thanks

**Comment by patrickkunka** [comment]
Hi Molly,

Can you try the following? Haven't tried it but it should in theory work:

```js
const mixer = mixitup({
    ...,
    templates: {
        pager: '<button type="button" class="${classNames}" data-page="${pageNumber}" data-mixitup-control>${pageNumber}</button>',
        pagerPrev: '<button type="button" class="${classNames}" data-page="prev" data-mixitup-control>&laquo;</button>',
        pagerNext: '<button type="button" class="${classNames}" data-page="next" data-mixitup-control>&raquo;</button>'
    }
});
```

**Comment by hannahmwool** [comment]
Worked perfect! Thank you.

**Comment by Camran** [comment]
Hi @patrickkunka issue is not solve, please help me. 
   var containerEl = document.querySelector('[data-ref~="mixitup-container"]');

            var mixer = mixitup(containerEl, {
                selectors: {
                    target: '[data-ref~="mixitup-target"]'
                }
            });
             var mixer = mixitup(containerE1, {
             selectors: {
                control: '[data-mixitup-control]'
              }
         });

**Comment by patrickkunka** [comment]
Hi @Camran,

I don't understand what your question is. But you should only need to create one mixitup instance. You can merge all your configuration options together into a single configuration object.

```js
var mixer = mixitup('[data-ref~="mixitup-container"]', {
    selectors: {
        target: '[data-ref~="mixitup-target"]',
        control: '[data-mixitup-control]'
    }
});
```
  

Does this help?

**Comment by Camran** [comment]
Thanks, it works :)

**Comment by Karsp** [comment]
Hello @patrickkunka!
First of all thanks for all your help, I was trying all the solutions but I don't know where I'm making the mistake.
Becaus of the structure of my website this is the structure I made, and it's the only one that I could make works. I changed the name container for mixcontainer to avoid problems with bootstrap but even when the MixItUp works perfect, when I use the principal navbar it takes the styles and function of Mixit controls.
I had tried with the scope local, but when i used it it doesn't work.
I'll write a little bit of the code, tell me if it's better if I send  you the files.
Many thanks!!

                       `<ul class="mixcontrols controls">
                       <li class="control" data-mixitup-control data-filter=".dexterior">Diseño Exterior</li>
                       <li class="control" data-mixitup-control data-filter=".dinterior">Diseño Interior</li>
                       <li class="control" data-mixitup-control data-filter=".tecno">Tecnología</li>
  </ul>
                
                 <div `class="mixcontainer">
 <div class="mix dexterior"><img class="img-responsive" src="img/showroom/corolla/presentacion/de-001.jpg"> 
                            	<p>Nuevo diseño exterior.</p></div>
                            <div class="mix dexterior"><img class="img-responsive" src="img/showroom/corolla/presentacion/de-002.jpg"> 
                            	<p>Parrilla delantera cromada.</p></div>
/*More items*/

<div class="gap"></div>
                            <div class="gap"></div>
                            <div class="gap"></div>
                 </div>
               </div>


/*Works with this script but with the navbar problem`*/

            var containerEl = document.querySelector('.mixcontainer');
            var mixer = mixitup(containerEl);

**Comment by leonel-ai** [comment]
Ran into the same issue. This (first suggestion) was exactly the solution I needed. Thanks @patrickkunka!
