### ISSUE TITLE
.append not working with fragments

### ISSUE THREAD

**Issue by garygreen** [patrickkunka/mixitup#270]
It's pretty common to use a [fragment element](https://developer.mozilla.org/en/docs/Web/API/Document/createDocumentFragment) to store the elements before adding them to the DOM. If you pass such an array of such fragments to `.append`  it'll fail with:

> /gm/public_html/dist/js/site.js?1482410501:10413 Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.

**Comment by patrickkunka** [comment]
Hi Gary,

All MixItUp insert methods (`.insert()`, `.prepend()`, `.append()`, `.insertBefore()`, and `.insertAfter()`) accept document fragments, array-like collections of elements, single elements and HTML strings.

https://github.com/patrickkunka/mixitup/blob/v3/tests/unit/mixer-insert.js#L83

Could you post a JSFiddle demonstrating the problem? Are you trying to insert an array of fragments or a single fragment containing one or more children? The former would be less common.

**Comment by garygreen** [comment]
https://jsfiddle.net/fpcy2b7m/

It seems to work fine when I pass jQuery object instead of calling `.get()` to get the flat array - didn't realise it accepted jQuery object as docs said only element, array of elements or html.

Maybe `.get()` affects something

**Comment by patrickkunka** [comment]
Ah looks like you are using MixItUp 2 - I was referring to v3 in my initial response, which is what the docs pertain to.

FYI, both the MixItUp 2 and 3 insert APIs also accept jQuery objects as they are implementations of an array-like collection of elements.

Will close for now - but happy to reopen if this is still an issue for you in v3.

**Comment by garygreen** [comment]
I could only find a cdn for v2 but I'm actually using v3 and get the same problem...

**Comment by patrickkunka** [comment]
Ah OK - I'm still waiting for CDNJS to get the v3 up on the their CDN. In the meantime you can use this: 

https://demos.kunkalabs.com/mixitup/mixitup.min.js

**Comment by garygreen** [comment]
Not a problem anyway as can use jQuery like objects as you say. Just that the docs say you can use an array of elements and it doesn't look like you can -- maybe a HTMLCollection but not a plain array?

**Comment by patrickkunka** [comment]
Should be able to - any kind of array-like object of elements, jQuery, HTMLCollection or plain array:

https://github.com/patrickkunka/mixitup/blob/v3/tests/unit/mixer-insert.js#L99

I'll take a closer look anyway, if you could update your fiddle with the above script that would be great.

**Comment by patrickkunka** [comment]
Here's a working example, based on your fiddle:

https://jsfiddle.net/fpcy2b7m/1/
