### ISSUE TITLE
.toggleOn() & .toggleOff() Availability

### ISSUE THREAD

**Issue by heychris** [patrickkunka/mixitup#271]
Hi,

Maybe I'm missing something, but it appears to me that `facade.js` should include references to `.toggleOn()` and .`.toggleOff()`. Is there a reason this is not the case? I'm trying to access these publicly, but get a ".toggleOff()' is not a function" error.

Something like this would help :)
```
    mixitup.Facade = function Mixer(mixer) {
        mixitup.Base.call(this);

        this.callActions('beforeConstruct', arguments);

        // All the other API functions
        // ...
        this.toggleOff            = mixer.toggleOff.bind(mixer);
        this.toggleOn            = mixer.toggleOn.bind(mixer);

        this.callActions('afterConstruct', arguments);

        h.freeze(this);
        h.seal(this);
    };
```

Thanks!!

**Comment by patrickkunka** [comment]
Hi Chris,
Yes quite right, looks like these were accidentally left out from the facade. Will get a patch out tomorrow.

In the mean time, you can pass `debug.enable: true` via the config object to return a real mixer instance with all public and private API methods exposed, rather than a facade.

**Comment by heychris** [comment]
Thanks!

**Comment by patrickkunka** [comment]
https://github.com/patrickkunka/mixitup/releases/tag/v3.1.3
