### ISSUE TITLE
Missing ability to return HTML DOM element in 'render' function

### ISSUE THREAD

**Issue by ondrasak** [patrickkunka/mixitup#272]
I miss an ability to return HTML DOM element in "render.target" function when I use the dataset API.
Now is possible to return only "string".

I have list of items. I use angular component to display each Item. The component has its logic.

I need compile that component in 'render' function and return element

```javascript
let template = angular.element("<super-component data-item='item'></super-component>");
return this.$compile(template)(scope);
```

**but its not possible now**
I can return only string

```javascript
let template = angular.element("<super-component data-item='item'></super-component>");
let compiledTemplate = this.$compile(template)(scope);
return $(compiledTemplate).prop("outerHTML");
```

but it is not sufficient -> this way I will lost component functionality

Now I do not see an option to list JS components (at least angular 1.5 components) by the dataset API

**Comment by patrickkunka** [comment]
Hi - thanks for raising this. I will be releasing an update in the next few days that will allow the render function to return a single DOM element.

Hopefully this will be enough for your angular integration, but FYI, I am hoping to build an angular 2 extension in the next few months that will make this process more seamless.

**Comment by patrickkunka** [comment]
The ability to return a DOM element has been added in v3.1.4 - let me know if works for you. Otherwise you may need to wait for the angular extension.

**Comment by ondrasak** [comment]
Thanks a lot for fast response and the update that resolves the issue. Now it works! :)
