### ISSUE TITLE
Filter Based on Multiple Keywords

### ISSUE THREAD

**Issue by barkins** [patrickkunka/mixitup#273]
Looking at this example: http://codepen.io/patrickkunka/pen/KpVPWo

Would it be possible to change this somehow so that if I enter "triangle white" it would return results, without having to use the checkboxes?

Thanks

**Comment by patrickkunka** [comment]
Hi @barkins,

It doesn't solve the issue but FYI - there's a more updated version of that demo here for MixItUp v3:
https://demos.kunkalabs.com/mixitup/filtering-by-text-input/

The behavior is pretty much unchanged. If you take a look at the source code, you'll see that it works by constructing a partially matching attribute selector which looks like the following:

`'[class*="white"]'`

This selector will match `.white` (or partially match smaller chunks of it)

The problem when you try to add multiple space separated values is that you end up with something like this:

`'[class*="white triangle"]'`

which will match only if those values are both present and in that order. What you actually want is:

`'[class*="white"], [class*="triangle"]'` or `'[class*="white"][class*="triangle"]'` depending on the type of logic you want (OR or AND).

The solution therefore would be to write some additional code to break down the text input's value into an array of values (e.g. `values = value.split(' ')`), then iterate through that array building up an selector string consisting of an individual attribute selector for each value, as above.

Hope that helps.
