### ISSUE TITLE
Upgrade to MixItUp 3: Divs with content not showing

### ISSUE THREAD

**Issue by ashraj98** [patrickkunka/mixitup#274]
Here's a JSFiddle with the issue: https://jsfiddle.net/ashraj98/af5L8tuL/2/

I got these same divs and CSS styles to work with the old version of MixItUp, but I can't seem to get this to work on updating to MixItUp 3.

**Comment by patrickkunka** [comment]
Hi @ashraj98,

With v3 you no longer need to set `display: none` on your targets. Here's you're fiddle updated and working:

https://jsfiddle.net/af5L8tuL/3/
