### ISSUE TITLE
conflict with "nav nav-tabs" bootstrap 3

### ISSUE THREAD

**Issue by saghian** [patrickkunka/mixitup#276]
Hi dear Patrick 
when use Mixitup with Nav-tabs bootstrap 3 have a conflict.
after click on tab, mixitup items hiden.
Please tell me how to solve

Nav-tabs controler:

              
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 iast-MainTabNewBox iast-TabNewsBoxFixMobile">

                    
                    <ul class="nav nav-tabs iast-TabNewsFixTabsFixXs" role="tablist">
                        <li role="presentation" class="active"><a href="#tab1" aria-controls="tab1" role="tab" data-toggle="tab">Last News</a></li>
                        <li role="presentation"><a href="#tab3" aria-controls="tab3" role="tab" data-toggle="tab">supports</a></li>
                        <li role="presentation"><a href="#tab2" aria-controls="tab2" role="tab" data-toggle="tab">education News</a></li>

                    </ul>

                    
                    <section class="tab-content iast-PanelContent">

Mixitup controler:

                    <div class="iast-GalleryBtnMixIt">
                        <button class="filter iast-GalleryBtnActive " data-filter="all">all</button>
                        <button class="filter" data-filter=".category-1">category-1</button>
                        <button class="filter" data-filter=".category-2">category-2</button>
                        <button class="filter" data-filter=".category-3">category-3</button>
                        <button class="filter" data-filter=".category-4">category-4</button>
                        <button class="filter" data-filter=".category-5">category-5</button>
                    </div>

Js:

    var iast_MainGallery = document.querySelector('#iast-GalleryMainMix');
    var mixer = mixitup(iast_MainGallery, {
        animation: {
            effects: 'fade scale stagger(50ms)' // Set a 'stagger' effect for the loading animation
        },
        load: {
            filter: 'none' // Ensure all targets start from hidden (i.e. display: none;)
        }
    });

    iast_MainGallery.classList.add('mixitup-ready');
    mixer.show()
        .then(function() {
            // Remove the stagger effect for any subsequent operations

            mixer.configure({
                animation: {
                    effects: 'fade scale'
                }
            });
        });

**Comment by patrickkunka** [comment]
Hi @saghian 

This is caused by the presense of the `data-toggle` attribute on various pieces of Bootstrap UI.

Please see the solution here: https://github.com/patrickkunka/mixitup/issues/268

**Comment by patrickkunka** [comment]
Hello @saghian did solution https://github.com/patrickkunka/mixitup/issues/268 work for you? If not please post a JSFiddle reproducing the issue.

**Comment by saghian** [comment]
Dear Patrick 
Thank you for your solution.
it worked fine
