### ISSUE TITLE
nth-child breaks mixitup layout pt.2

### ISSUE THREAD

**Issue by konsumkuenstler** [patrickkunka/mixitup#280]
Hey,

I´ve read the previous posts according [this issue](https://github.com/patrickkunka/mixitup/issues/97). Now I trying for 2 days now to find a solution based on [this solution](http://stackoverflow.com/questions/32355054/how-to-get-nth-child-selector-to-skip-hidden-divs?answertab=votes#tab-top).

Now I´m struggling getting it work because my JS-knowledge isnt that good at all. But my feeling is, that this can be accomplished by detach() those elements and append them again in the same spot by getting their inditial-index before detaching them. I was looking for a "mixOnBefore" to get it done somehow. All my attemps with append on mixStart didnt work at all :(  

Well, Im hoping that you could give me a hint or maybe tell me if this is even possible the way Im thinking it could be. 

Help would be highly appreciated!

Best

**Comment by patrickkunka** [comment]
HI @konsumkuenstler 

Unfortunately MixItUp (or any client side hide/show filtering solution) is not compatible with nth-child based CSS.

Please see this tutorial for information on compatible CSS layouts, and an explanation of why nth-child is not possible (similar to what is described in the StackOverflow post you linked to)

https://www.kunkalabs.com/tutorials/mixitup-grid-layouts/

**Comment by konsumkuenstler** [comment]
Well, thanks for your quick response - your answer is nothing new according to the last issue. Then why [this demo](https://jsfiddle.net/g7gL5zfb/15/) works with nth-based css, while mixitup not? You dindt really answered my question - nvm

**Comment by patrickkunka** [comment]
Hi @konsumkuenstler 

The demo you referenced is using JavaScript to remove hidden elements from the DOM so they are not included in CSS's indexing. This works in a static design, but will not work with MixItUp as it requires that the elements to be hidden remain in the DOM for the duration of the animation, particularly when new elements are shown. This also does not account for dynamic, animated sorting. Elements must retain their styling throughout the lifecycle of a MixItUp operation (whether showing/hiding/sorting), and with nth-child based styling this is just not possible.

Sorry this isn't the news you are hoping for, but I don't want to create any doubt or confusion about what is and isn't possible with MixItUp.

**Comment by konsumkuenstler** [comment]
Thanks for clarification. Somehow [quicksand](https://razorjack.net/quicksand/) works this way but was last updated 5 years ago. I just was hoping to get it done with mixitup. Thank you anyway!

**Comment by patrickkunka** [comment]
Good point. ~~Quicksand and also Isotope use absolute positioning to create the illusion of sorting the order of DOM elements, so nth-child would be preserved in a sorting context. I don't know about filtering however.~~ Isotope is updated regularly so you might want to check that out (if you haven't already)

Correction: Actually I just checked and quicksand does keep the DOM order in sync after animations are completed, so nth-child would not be preserved in a sorting context either.

**Comment by konsumkuenstler** [comment]
Check this out: [filtering with nth-type and quicksand](http://codepen.io/anon/pen/apWYLo)

As you can see, it is possible to keep the nth-type ordering - thats why I was wondering why mixitup isnt able to. Isotop behaves the same way as mixitup.
