### ISSUE TITLE
onMixLoad callback, v3

### ISSUE THREAD

**Issue by jeffceriello** [patrickkunka/mixitup#284]
What happened to onMixLoad callback in version 3? I can't find a way to detect when mixitup has fully loaded

**Comment by patrickkunka** [comment]
Hi @jeffceriello,

With v3, loading animations were removed by default so MixItUp now instantiates synchronously. Therefore, the `onMixLoad` callback and `mixLoad` event are no longer needed.

For example, when you instantiate a mixer (as follows) the mixer is ready to interact with immediately.

```js
var mixer = mixitup(containerEl)
```

If you do wish to add a loading animation (e.g. https://demos.kunkalabs.com/mixitup/loading-animation/) you can use the promise returned from the API to defer further functionality, as is done in the demo to edit the animation configuration.

The code for that demo can be viewed here: https://github.com/patrickkunka/mixitup/blob/v3/demos/loading-animation/index.html

**Comment by jeffceriello** [comment]
Hey @patrickkunka, thank you so much for the great plugin, support and perfect explanation!
All clear now :)

**Comment by patrickkunka** [comment]
You're welcome!
