### ISSUE TITLE
Script hangs in IE-Edge

### ISSUE THREAD

**Issue by dirkschaap** [patrickkunka/mixitup#285]
Hi,

I implemented the script on http://cnbnewplants.nl/our-assortment/?lang=en
In every browser it seems to work well except for **IE-Edge.** Does anyone have any ideas because I'm running out of options.
It's a Wordpress environment with several plugins but with a self-build template. Even with only the WPML Multilingual CMS and  the Advanced Custom Fields PRO plugin (needed by the template) enabled, the script 'hangs' in IE. 
Anyone any suggestions??

Kind regards,
Dirk

**Comment by patrickkunka** [comment]
Hi @dirkschaap,

Sorry to hear about that – nothing worse than debugging IE. However, MixItUp has been tested in Edge and I have just double checked that all our demos (demos.kunkalabs.com/mixitup/) are still functioning correctly in Edge 14, which they are.

I think the issue may be related to your implementation. One possible cause may be the fact you have a opacity transition rule applied to directly to your target elements, which can cause issues with animations hanging.

More info here: https://github.com/patrickkunka/mixitup/issues/281

I would recommend experimenting with a working reduced test case in Edge and gradually adding in your project's features/implementation until you can identify the issue.

If you can narrow it down to a specific MixItUp issue in Edge (in a JSFiddle), I'd be happy to look into this further if its something that could be a bug.

**Comment by dirkschaap** [comment]
Thanks for you quick response. One other question: when we limit the number of items to show to 150, everything seems to work fine in Edge. Is there a limit in MixItUp?

**Comment by patrickkunka** [comment]
Hi Dirk,

MixItUp doesn't enforce a particular limit but I wouldn't recommend more than 1500 items, as the UI will start to become unusable across all browsers (combination of a slow/heavy DOM and MixItUp's algorithms). How many do you have?

**Comment by dirkschaap** [comment]
Hi Patrick,
Not that much. We have around 250 items.
FYI: It looks like we've solved the problem by changing some code on our side. Although IE/Edge is not as fast as FF or Chrome, it will do for now! Thanks again for your help!

**Comment by patrickkunka** [comment]
OK sounds good. Let me know if want me to reopen.
