### ISSUE TITLE
[Question] large data set / virtualization ?

### ISSUE THREAD

**Issue by MarcMagnin** [patrickkunka/mixitup#289]
Hi,

I was wondering if that could be possible to intergrate mixitup with some virtualization such as:
https://bvaughn.github.io/react-virtualized/#/components/Collection

The idea would be to present a lot of items (let say 30K images to represent) and been able to virtualize them (not renderer outside of the view) and add the nice and smooth filtering animations of your library.

Or do you already have a nice way to handle such a data set ?
Many thanks!

**Comment by patrickkunka** [comment]
Hi @MarcMagnin,

Have you checked out the MixItUp Dataset API? That would be the best way to approach the handling of a large dataset.

The following tutorials should be of interest:

https://www.kunkalabs.com/tutorials/using-the-dataset-api/
https://www.kunkalabs.com/tutorials/integrating-mixitup-into-your-project/

**Comment by MarcMagnin** [comment]
Thanks for the quick reply. I've check the API already.
I was wondering how this library could handle a lot of items (not infinite loading) to be able to filter on a large virtualized list.

**Comment by patrickkunka** [comment]
Without using a server-side API in conjunction with the MixItUp Dataset API, you would be limited by the speed of the DOM and the DOM selector API, which will not be performant past a few hundred items.

I'm not exactly sure what you mean by "virtualized" in this context, as all items must exist in the DOM (whether hidden or shown). The Dataset API avoids this overhead by only rendering the current dataset, and caching any previously shown items in memory for performance.

**Comment by MarcMagnin** [comment]
Cheers.
I was wondering if we could have a virtualized grid view. Basically only the items in the window are rendered, other items gets rendered when filtering, with animations that simulates existing items (but they were not there at all, they got added to the DOM on the fly). 
The advantage of such thing would be: have up to a million items in the grid with smooth animation of appearance, disappearance on filtering, all client side.

**Comment by patrickkunka** [comment]
Hi Marc,

What you are describing is exactly what the dataset API does. You don't actually need to use it with a server-side API, although that's the most likely use-case.

You could easily just store your items in-memory in a javascript array, but you would need to implement your own system of filtering/sorting that array in the browser (essentially implement a client-side DB). This is exactly what the "Mock API" implementation does in the dataset demos:

https://demos.kunkalabs.com/mixitup/dataset-empty-container/
https://github.com/patrickkunka/mixitup/blob/v3/demos/mock-api.js

**Comment by MarcMagnin** [comment]
Thanks for your reply! The only drawback I can see is that without any filter you will struggle to scroll across a giant list without performance impact such as in a virtualized grid (unless I miss something).
In this component you can easily scroll on a million items list: https://bvaughn.github.io/react-virtualized/#/components/Collection. The big drawback is that is misses the wonderful animations that you provide on appear/disappear of items on filter.

**Comment by patrickkunka** [comment]
Hi @MarcMagnin,

Sorry - forgot to checkout your attached link until now. This is quite a specific piece of functionality and a bit different to how mixitup works. It's possible only because of absolute positioning, within a massively oversized container with vast amounts of empty space used to enable/fake native scrolling.

Unfortunately, MixItUp's entire "raison d'etre" is to work with pure-css flow-based layout, so anything based on absolute positioning wouldn't be possible in its current state. Have you checked out Isotope by @desandro at all? It's another animated filtering library built on top of the masonry library. I could imagine it might be possible to use it for this sort of thing.

**Comment by MarcMagnin** [comment]
Thanks for looking at it! I'll take a look at Isotope.
