### ISSUE TITLE
Multifilter and Bootstrap Select

### ISSUE THREAD

**Issue by juliocorral** [patrickkunka/mixitup#293]
Hi, Patrick

Now is working right. THANK YOU!!!  (Issue #290)

Do you know if is possible to use your fantastic plugin with bootstrap
select? I'm trying to use it but when I try to combine both plugins all the
select options are lost.
You can see this here: http://www.casamytea.com/es/categorias/pagina_1/4/tes-e-infusiones/negro.php

There are two select one is a normal select and second select is using
bootstrap select plugin and his options value are gone.

Thank you in advance.

2017-02-17 22:14 GMT+01:00 Patrick Kunka <notifications@github.com>:

**Comment by patrickkunka** [comment]
Hi Julio,

I can't see any select UI on the link you attached.

**Comment by juliocorral** [comment]
Hi,

Sorry you can see it now.

Thank you

2017-02-20 12:50 GMT+01:00 Patrick Kunka <notifications@github.com>:

**Comment by patrickkunka** [comment]
Hi Julio,

Can you firstly try the solution described in in this issue, and let me know if that helps:

https://github.com/patrickkunka/mixitup/issues/268

**Comment by juliocorral** [comment]
Hi,

Great!!! It's working now. Thank you very much.

**Comment by patrickkunka** [comment]
Great!

**Comment by juliocorral** [comment]
Hi again Patrick,

I have a new problem with this issue.
You can see it at this url: http://www.casamytea.com/es/elige-tu-te.php

When I click the button "CANCELAR" (reset button) only normal filters are
cancelled (BIO, PURO, AROMATIZADO), but Bootstrap Select filters are
cancelled but its values are still visible in the selectors.

Could you help me with this to reset this selector values too.

Thank you in advance.


2017-02-21 16:01 GMT+01:00 Patrick Kunka <notifications@github.com>:

**Comment by patrickkunka** [comment]
Hi @juliocorral 

Did you figure this out? It seems to be working correctly.

**Comment by marioburger** [comment]
Hi @patrickkunka and everyone else coming across this Problem. By code inspection of @juliocorral 's site, I have found out how he got the reset button working. Apparently he did not use the mixitup multifilter reset functionality but the bootstrap select reset, namely:

`
$('button[type="reset"]').click(function(){
    $('.selectpicker').selectpicker('deselectAll');
});
`
