### ISSUE TITLE
o.toLowerCase is not a function Error

### ISSUE THREAD

**Issue by webmdt** [patrickkunka/mixitup#296]
Seeing this console error, that's disabling the ability to filter

```
Uncaught TypeError: o.toLowerCase is not a function
    at e.Mixer.compare (*DOMAIN*mixitup.min.js:17:9602)
    at e.Mixer.compare (*DOMAIN*mixitup.min.js:17:9703)
    at *DOMAIN*mixitup.min.js:17:9318
    at Array.sort (native)
    at e.Mixer.sortOperation (*DOMAIN*mixitup.min.js:17:9290)
    at e.Mixer.getInitialState (*DOMAIN*mixitup.min.js:17:2247)
    at e.Mixer.attach (*DOMAIN*mixitup.min.js:17:640)
    at e (*DOMAIN*mixitup.min.js:16:3315)
```

I'm running the Pagination and MultiFilter ... but even disabling those doesn't solve the issue. The issue seems to be a JQUERY issue, however I do not have JQUERY loaded on the page.

Example Mix:

```html
<div class="mix F" data-age="20" data-name="Sara" data-height="5" data-weight="150">
  <div class="mix-content">
    <h4>Sara Laramie</h4>
    <ul>
      <li><strong>Age: </strong>20</li>
      <li><strong>Height: </strong>5</li>
      <li><strong>Weight: </strong>150</li>
    </ul>
  </div>
</div>
````

JS:

```js
var containerEl = document.querySelector('.container');

var mixer = mixitup(containerEl, {
    load: {
        sort: 'age:desc name:asc',
    },
    multifilter: {
        enable: true
    },
    pagination: {
        limit: 25
    }
});
```

**Comment by patrickkunka** [comment]
Hi Marco,

The issue is related to your sorting attributes, but the code you posted looks fine, so hard to tell what's causing it.

Would you be able create a stripped back jsfiddle reproducing the issue (without multifilter and pagination)?

**Comment by webmdt** [comment]
Hello Patrick,

Thanks for the quick reply. I was able to fix this ... seems MIX is very "fragile" when it comes to content stored in the DATA attributes.

I'm outputting via PHP a list of about 1000 entries ... I did some TRIM and STRIPSLASH commands on all of the data outputting to the page and now everything is working.

Thanks

**Comment by patrickkunka** [comment]
Thanks for the info. I'd like to make it more robust. Can you give me some examples of the kind of values that were breaking it?

**Comment by webmdt** [comment]
I'd have to go back and check, as I just pulled the trigger and cleaned everything (even typeset the INT values).

If I have time, I'll run a test and check for non-string characters and let you know.

Sidenote, I also found (this was an issue I had when I first setup your plugin) that if the DIV's are stacked on the same line MIX doesn't work. I just added a line break to my output and all was well with the world.

**WORKS**
![screen shot 2017-03-06 at 10 37 15 am](https://cloud.githubusercontent.com/assets/14183110/23616598/4709387a-0258-11e7-8651-dd948a579ba8.png)


**FAILS**
![screen shot 2017-03-06 at 10 38 17 am](https://cloud.githubusercontent.com/assets/14183110/23616629/6568aea4-0258-11e7-805b-1296e04c3129.png)


**SOLUTION**
![screen shot 2017-03-06 at 10 37 58 am](https://cloud.githubusercontent.com/assets/14183110/23616632/6964e1b2-0258-11e7-9d9e-cc0b375d5adf.png)

**Comment by patrickkunka** [comment]
Hi Marco,

I take it by "fails", you mean the styling is broken rather than an actual error being thrown? If you're using the 'inline-block' styling from the demo, you will need whitespace between elements to allow elements to line-break naturally and form a grid.

You can also use floats or flex-box, but inline-block is my personal preference. Unfortunately it comes with a bunch of gotchas including this one regarding whitespace between elements. Much more info here if you're interested: https://www.kunkalabs.com/tutorials/mixitup-grid-layouts/
