### ISSUE TITLE
Text Inputs - Specific Cases

### ISSUE THREAD

**Issue by webmdt** [patrickkunka/mixitup#298]
It seems that TEXT INPUTS used as filters only work under the right conditions. The DATA name must be a single name, and all of the values must be lowercase without any spaces. I took your working DEMO, and converted "color" to "last-name" and made some minor changes to the class values ... and the TEXT filtering now no longer works.

`        

            <fieldset data-filter-group class="text-input-wrapper">
                <input type="text" data-search-attribute="data-last-name" placeholder="Search by Last Name"/>
            </fieldset>
        </form>

        <div class="container">
            <div class="mix Grean small square" data-last-name="Grean" data-shape="square" data-size="small"></div>
            <div class="mix Grean medium square" data-last-name="Grean" data-shape="square" data-size="medium"></div>
            <div class="mix Blueee large triangle" data-last-name="green" data-shape="triangle" data-size="large"></div>
            <div class="mix pink large circle" data-last-name="pink" data-shape="circle" data-size="large"></div>
            <div class="mix Grean small circle" data-last-name="Grean" data-shape="circle" data-size="small"></div>
            <div class="mix Blueee medium triangle" data-last-name="Blueee" data-shape="triangle" data-size="medium"></div>
            <div class="mix pink medium square" data-last-name="pink" data-shape="square" data-size="medium"></div>
            <div class="mix Blueee medium triangle" data-last-name="Blueee" data-shape="triangle" data-size="medium"></div>
            <div class="mix pink small circle" data-last-name="pink" data-shape="circle" data-size="small"></div>
            <div class="mix Grean large triangle" data-last-name="Grean" data-shape="triangle" data-size="large"></div>
            <div class="mix Blueee small square" data-last-name="Blueee" data-shape="square" data-size="small"></div>
            <div class="mix pink small square" data-last-name="pink" data-shape="square" data-size="small"></div>
            <div class="mix Grean large square" data-last-name="Grean" data-shape="square" data-size="large"></div>
            <div class="mix Blueee large circle" data-last-name="Blueee" data-shape="circle" data-size="large"></div>

            <div class="gap"></div>
            <div class="gap"></div>
            <div class="gap"></div>
            <div class="gap"></div>
        </div>`

**Comment by patrickkunka** [comment]
Yes that is the desired behavior.

Unfortunately attribute selectors are case sensitive, so the search input is converted to lowercase before querying the DOM. This makes the searching much more robust from the user's perpective, but requires that your classes or attribute values are well prepared. Ideally, lowercased and stripped of special characters. This shouldn't be an issue if you are outputting these values in your markup dynamically server side.

This is not part of MixItUp but part of the demo implementation: https://github.com/patrickkunka/mixitup/blob/v3/demos/filtering-by-text-input/index.html#L72

Worth nothing that a case-insensitive attribute selector has been recently added to the DOM selectors spec, but is not widely implemented yet outside of Chrome, so this is still the most robust way to handle such functionality.

DOM querying for textual search obviously has its limitations but works well in basic scenarios, with a small, finite amount of data. If you require a more "intelligent" search, then you should delegate searching to your back-end via an API. You could return a list of IDs to query the DOM with, or just use the dataset API.
