### ISSUE TITLE
pagination media-queries

### ISSUE THREAD

**Issue by jimblue** [patrickkunka/mixitup#299]
Hello guys,

I'm using your pagination plugin and I having a problem with design.

My grid  of items filtered by mixitup is 3 columns wide on desktop and 2 columns wide on mobile.
I have a total of 20 items and a litem of 9 items per page.

As 9 items is a multiple of 3 columns the first page is completely full on desktop... that's nice!
But on mobile, there is always a 1 item gap as 9  is not multiple of 2...

Is it possible to set max items per page dynamically based on windows width?

Thank you so much

**Comment by patrickkunka** [comment]
Hi Jean-Marie,

Yes good question. In the latest version, which you can download from your account, you'll find a demo detailing exactly how to do this.

Let me know if you have any further questions.

**Comment by jimblue** [comment]
Amazing... didn't notice that =) thanks
