### ISSUE TITLE
pagination plugin : scrolling strangely

### ISSUE THREAD

**Issue by jimblue** [patrickkunka/mixitup#301]
Hello there,

I'm having some issue with the pagination plugin.

While clicking on page it sometime scroll down for no reason.

Can't understand why...

Any idea?

**Comment by patrickkunka** [comment]
Hi - can you post a link to your project, and some steps on how to recreate the problem?

**Comment by jimblue** [comment]
Hi,

Sure, there is a gist of the js file that running my project (mixitup code on line 235)
[gist: project home.js](https://gist.github.com/jmbelloteau/5f89824ef89f37653d4433a779dccb9a)

And here is my project url: www.immersion-pictures.com

Thanks :)

**Comment by patrickkunka** [comment]
Hi @jimblue,

Nice site!

Could you give me some steps I can follow to recreate the problem? I had a click around but everything seems normal so far.

Thanks

**Comment by jimblue** [comment]
Hi @patrickkunka ,

Thanks for the website still a work in progress.

I made a gif to show you how the problem happen:

[scrolling problem GIF](https://gfycat.com/DeterminedFoolishHorsemouse)

But basically, I just switch from page 1, 2, 3, 4 and when going back to 3 the bug happen.

Thanks for your help

**Comment by patrickkunka** [comment]
Great - thanks for the gif that was very helpful. This was actually related to a bug in the MixitUp core which I think I've now fixed.

Could you download the latest version 3.1.9 and let me know if that fixes it?

You'll also need to change your configuration to:

```js
{
    ...,
    animation: {
        ...,
        clampHeight: true
    }
}
```

(Or you can just remove the `animation.clampHeight` setting completely, as it is `true` by default).

**Comment by jimblue** [comment]
Thank you so much @patrickkunka  it's working 😄 !!!
