### ISSUE TITLE
Adding some kind of 'matching' class?

### ISSUE THREAD

**Issue by mattyd2478** [patrickkunka/mixitup#303]
I'm using the multifilter and pagination plugins.

I need to somehow keep track of which items relate to the current filtering regardless of whether they are visible on the current page or not so I was wondering if there was any way of adding an additional class or attribute to items regardless of whether they are currently display:none etc?

**Comment by patrickkunka** [comment]
Hi @mattyd2478,

The MixItUp state object exposes a `matching` property exactly for this purpose. You can hook into it via the lifecycle callbacks, for example:

```js
const mixer = mixitup(container, {
    callbacks: {
        onMixEnd: state => console.log(state.matching)
    }
});
```
This will give you an array of all matching target elements, which you can then iterate over.

So, if you wanted to add a class to these elements at the end of each operation, you could do something like this:

```js
const mixer = mixitup(container, {
    callbacks: {
        onMixEnd: ({targets, matching}) => {       
            targets.forEach(el => {
                const isMatching = matching.indexOf(el) > -1;

                el.classList[isMatching ? 'add' : 'remove']('my-matching-class');
            }
        }
    }
});
```
This example iterates over the `state.targets` array (which contains everything), and checks if that element also appears in the `state.matching` array. If so, the matching class is added, if not, it is removed. This ensures that all previous matching classes will always be cleared between operations.

Hope that helps

**Comment by mattyd2478** [comment]
Thanks Patrick,

Great support as always.
