### ISSUE TITLE
Loses "active layout" aka "activeContainerClassName" when sorting

### ISSUE THREAD

**Issue by minde281** [patrickkunka/mixitup#305]
Hi, think I just found a minor bug.
I'm using MixItUp with two different layouts (_layout-grid_ and _layout-list_).

On the callback "onMixStart" i print both the _state_ and the _futureState_.
The results show that the active layout is lost when changing sort order:
![image](https://cloud.githubusercontent.com/assets/5879965/24240271/39b725c2-0fb1-11e7-90c0-7d753818e26f.png)

Although the class for active layout (_layout-grid_) is still in my html markup, the Mixer no longer recognizes this as a layout state. This becomes a problem when i choose to then change layout, and end up getting both the class _layout-grid_ and _layout-list_.

Hope this is easy to fix.

Best regards,
Marius Minde

**Comment by patrickkunka** [comment]
Thanks for the info Marius that does sound like a bug. I'll try to get a repro together and get back to you.

**Comment by minde281** [comment]
Just downloaded the latest version (3.1.9) to check if the error is still there.

I've made a pastebin that does have this error (you will need to change the path of the mixitup lib to a working path though)

https://pastebin.com/kv9jRr90

The mixitup is initialized with "layout-gird" but this is removed the first time you change the order.
Both _state_ and _futureState_ are printed in the console.

**Comment by patrickkunka** [comment]
Hi @minde281 

Sorry for the delay in response as I've been on vacation.

This should now be fixed in https://github.com/patrickkunka/mixitup/releases/tag/v3.1.10. Let me know if it works for you!

**Comment by minde281** [comment]
Yes, that seemed to do it.
Thank you again 👍
