### ISSUE TITLE
Uncaught TypeError: t.className.match is not a function

### ISSUE THREAD

**Issue by robbertvdzanden** [patrickkunka/mixitup#306]
I keep getting this error:
Uncaught TypeError: t.className.match is not a function

There are multiple instances of Mixitup on one page while using the MultiFilter extension.

**Comment by patrickkunka** [comment]
Can you provide a link?

**Comment by robbertvdzanden** [comment]
groenbezig.lrinternet.nl

Met vriendelijke groet,

Robbert van der Zanden

**Comment by patrickkunka** [comment]
Hi Robbert,

Could you give me some instructions on how to recreate the problem? I had a click around but the only think I could see in the console was a log 'No items could be found matching the requested filter' (no error).

On an unrelated point, (and as I don't understand dutch, I might be misunderstanding the desired functionality), this seems like a use case for 'local' control scoping to prevent the each instance's controls from interfering with the other one.

For example, compare these two demos:
https://demos.kunkalabs.com/mixitup/multiple-instances-global-control-scoping/
https://demos.kunkalabs.com/mixitup/multiple-instances-local-control-scoping/

**Comment by patrickkunka** [comment]
Closing for now. Please let me know if you want me to reopen.

**Comment by no-liver** [comment]
Maybe helpful to someone: Had this issue when I had "data-toggle" and "data-filter" in use on the same page with other components not related to mixitup instance.
