### ISSUE TITLE
Is there a way for the "search" functionality to look through text, instead of looking through the class on each div?

### ISSUE THREAD

**Issue by pmacswebteam** [patrickkunka/mixitup#307]
We require the ability to be able to search a paragraph of text. The way that it seems to work now, is that all searchable text gets added classes on each div.  This poses a problem when searching for a phrase such as "breast cancer". Each word can be search separately, however, phrases seem to be unsearchable.  Is there a way to search phrases/any combination of adjacent words in a paragraph with mix it up?

**Comment by patrickkunka** [comment]
Hi,

Unfortunately DOM-selector-based searching is crude and also not performant. It was a much requested feature in MixItUp 2, so it was built into the MultiFilter extension, but if you want to do anything particular advanced, I would recommend doing it server side over an API.

If this is an option for you, and if each of your items have a unique ID (e.g. a database ID), you could set up an search API that returns a list of IDs matching a given search query, then you can send that to MixItUp using the .filter() API. For example:

```js
var matching ids = [2, 33, 143]; // returned from your API

// Convert array of int IDs into a selector string
var selector = ids.map(id => '#' + id.toString()).join(', '); // '#2, #33, #143'

// Show only the elements with the provided IDs
mixer.filter(selector)
```

This will scale much better, and delegate any complex search functionality to your server.

**Comment by pmacswebteam** [comment]
Thanks for your help!
