### ISSUE TITLE
MixItUp MultiFilter Logic Issues

### ISSUE THREAD

**Issue by tylonius** [patrickkunka/mixitup#310]
I'm having an issue with the MultiFilter. I have a site that lists industrial properties and has multiple filter groups. I need the filter within groups to use "or," and between groups to use "and."

For some reason, I can't get it to work. If I select two property size filters, for example, "Up to 10,000SF" and "10-50,000SF," I should see all properties under 50,000SF. Instead, when I select the 10-50K option, it only shows that option.

Likewise, if I select a size and a region, it only shows me the size option. The region filter works by itself, but not in conjunction with any other filter.

Let's start with my script. Is it configured correctly?

If so, PM me for URL and login credentials for the actual page.

Thanks!

ty

`<script>
            var containerEl = document.querySelector('.container');
            var mixer = mixitup(containerEl, {
                multifilter: {
                    enable: true,
					logicWithinGroup: "or",
					logicBetweenGroups: "and"
                },
                animation: {
                    effects: 'fade translateZ(-100px)'
                }
            });
        </script>`

**Comment by patrickkunka** [comment]
Hi,

I'm  on vacation right now so it might be a little while before I can get to this, but my first instinct would be to look at the format of your size selector strings. Are you aware that attribute values must start with a letter according to the w3c spec? Starting with a number may cause issues.

I would recommend prefixing the numerical class names in your markup with a word. I.e: 

`10-50000sf` could become `size-10-50000sf`. Also make sure any special characters (like commas) are stripped out by whatever is generating your markup.

Let me know if that helps

**Comment by tylonius** [comment]
That's not the issue, but enjoy your vacation and we can explore it when you are back to work. 

Ty

**Comment by tylonius** [comment]
Hi, Patrick!

I hope you enjoyed your vacation.

We are still having this issue, and I have a meeting with the client on Monday to demonstrate this feature. Attached is the template I’m having issues with, and I sent a priavte message with a login to the CMS, so that you can see the site yourself.

Thanks,

ty

**Comment by patrickkunka** [comment]
Hi Ty,

Just looking at this now. The issue is your markup. You need to make sure your filter group elements (in your case the `<ul>` elements), have a `data-filter-group` attribute present.

See the "Filter Group UI" section in this tutorial: https://www.kunkalabs.com/mixitup-multifilter/docs/get-started/

This lets the extension know where each group stops and starts. Without these attributes, MixItUp will just see one single group of controls, and concatenate selectors together according to a single logic (by default, "OR") which is what is happening.

Hope that helps, and again sorry for the delay.

**Comment by tylonius** [comment]
That fixed it! Thanks!

Have a great weekend!

ty



Ty Morton, Principal
ty@tylonius.com <mailto:ty@tylonius.com>
765-749-0652 <http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg4XXLDRW7fsJrs1qg9l6W7fckrM56dvN0f1BQzZT02?si=X-SIG-APPLE-NOKEY&pi=E7BEC0B2-D0C0-46C3-9258-9F2E5435134D&t=tel%3A765%2D749%2D0652>
