### ISSUE TITLE
Pagination not working. There are no changes after click

### ISSUE THREAD

**Issue by dikey94** [patrickkunka/mixitup#314]
I've bought the pagination extension.
The entire mixitup works nice, but I have an issue with pagination. Controls show up, but there are no changes after my clicking in "2".
HTML:
https://pastebin.com/q9isJ4A6

JS:
https://pastebin.com/qukpaPY0

What can be wrong? Thanks.

**Comment by dikey94** [comment]
Demo: https://gyazo.com/a99dc35b2353a8b17f9b73094fb0681e

**Comment by dikey94** [comment]
All right, I know what is wrong.

All because of control: 

> '[data-mixitup-control]'

**Comment by patrickkunka** [comment]
Yes that makes sense. That will restrict any control (including pagination buttons), to only those that match that selector.

If using `data-mixitup-control` is a must (I assume you're using Bootstrap?), you can adjust the pagination templates as needed to include that attribute. See my final comment on the following issue:

https://github.com/patrickkunka/mixitup/issues/268
