### ISSUE TITLE
After changing item props and running mixer.dataset how to update targets in dom?

### ISSUE THREAD

**Issue by anagio** [patrickkunka/mixitup#315]
When I click a sort button on my site, I re order the items in the array and based on a condition I sometimes change an item property value in this case the `item.item_class` value. After I run `mixer.dataset` I don't see the class updated on the site. Using dev tools I saw that render target isn't fired when`mixer.dataset` fires. Part of my render target is `<div class="integration '+item.item_class+'">` Which i'd like to change when I run `mixer.dataset` what's the proper way to do this so the dom updates with the updated items. Thanks

```
item_class = "dimmer";
items[i].item_class = item_class;
result2.push(items[i]);
var result = result1.concat(result2);
```

```
mixer.dataset(result)
    .then(function(state) {
    console.log(state);
});
```

**Comment by patrickkunka** [comment]
Hi @anagio,

Have you tried setting `data.dirtyCheck` to `true` in the config?

**Comment by anagio** [comment]
That works I just needed to load the data set in the config. I was loading into an empty container and didn't seem to work. Thanks!

```
load: {
    dataset: items
 },
```
