### ISSUE TITLE
number in data filter is not working

### ISSUE THREAD

**Issue by luicephillips** [patrickkunka/mixitup#318]
Hello,  
my data-filter=".3ds" not working.
Plz help,
Thanks in advance.

**Comment by patrickkunka** [comment]
Hi @luicephillips,

In HTML5, class attributes may not start with numbers, and querying them with a selector string starting with a number like `'.3ds'` will usually result in a DOM exception being thrown.

This isn't anything related to MixItUp - but actually part of the HTML specification.

The solution I usually recommend is to prefix your category name with some arbitrary text, for example:

``` html
<div class="mix category-3ds"> ... </div>
```
> target element

``` html
<button data-filter=".category-3ds">3DS</button>
```
> control button

Hope that makes sense.
