### ISSUE TITLE
Performance really bad in Safari(?)

### ISSUE THREAD

**Issue by AnInfiniteNumberofMonkeys** [patrickkunka/mixitup#321]
Hi, I've been using MixItUp for a couple years, but I've just upgraded my site to v.3 (including the MultiFilter extension). I've been using Chrome during development and performance of the plugin has seemed fine, but recently as I started testing on Safari I noticed that performance during filtering is much worse. For example, when a filter is selected, it takes anywhere from 2-8 seconds to render the filtered set of elements on Safari! The same operation in Chrome always seems to take well under 1 second. Here is a screenshot showing over 7 seconds for MixItUp to complete:
![mixitup_safari](https://cloud.githubusercontent.com/assets/13838253/25975540/bad35ec2-3663-11e7-8c8a-b1876f9e660b.jpg)

I've traced the problem to lines 716-720 of mixitup.js:
```
    }, e.BaseStatic.call(e.QueueItem), e.QueueItem.prototype = Object.create(e.Base.prototype), e.QueueItem.prototype.constructor = e.QueueItem, e.Mixer = function() {
        e.Base.call(this), this.callActions("beforeConstruct"), this.config = new e.Config, this.id = "", this.isBusy = !1, this.isToggling = !1, this.incPadding = !0, this.controls = [], this.targets = [], this.origOrder = [], this.cache = {}, this.toggleArray = [], this.targetsMoved = 0, this.targetsImmovable = 0, this.targetsBound = 0, this.targetsDone = 0, this.staggerDuration = 0, this.effectsIn = null, this.effectsOut = null, this.transformIn = [], this.transformOut = [], this.queue = [], this.state = null, this.lastOperation = null, this.lastClicked = null, this.userCallback = null, this.userDeferred = null, this.dom = new e.MixerDom,
        this.callActions("afterConstruct"), n.seal(this)
    }, e.BaseStatic.call(e.Mixer), e.Mixer.prototype = Object.create(e.Base.prototype), n.extend(e.Mixer.prototype, {
        constructor: e.Mixer,
```

Specifically line 718 is where it gets hung up for a long time.
`this.callActions("afterConstruct"), n.seal(this)`

Is there anything that could be done to help?

The site URL is staging.fishlodges.com/search

**Comment by patrickkunka** [comment]
Hi,

Could you provide a rough estimate of the number of target elements you're working with in the DOM?

**Comment by AnInfiniteNumberofMonkeys** [comment]
Right now, it's 100 targets.

**Comment by patrickkunka** [comment]
Hi Deralict,

I've had a look at the your staging site and have been able to recreate the issue as you described.

MixItUp uses `requestAnimationFrame` to ensure that its animations are always deferred until after the GPU stack is clear. Unfortunately Safari is nowhere near as efficient at managing when processes should use the GPU as Chrome is.

Looking at the timeline in Safari shows that the requestAnimationFrame request (from mixitup's `moveTargets()` call) is taking several seconds to be fulfilled. As you do have a lot going on in your page including various other libraries, plugins, canvas, images within targets etc, Safari is probably struggling to prioritize GPU calls in logical way.

The easiest fix would just be to disable MixItUp animations in Safari (`{animation: {enable: false}}`). I've tried this on your page and becomes very snappy and responsive again. The pagination extension may be of help in terms of reducing the number of elements that need to be animated at any one time.

Alternatively, you could experiment by starting with just your MixItUp container and no other scripts of dependencies, getting a performance benchmark, then gradually adding back in your other scripts incase there's a particular feature that is causing the issue.

Unfortunately there's not much that can be done within the MixItUp code to improve this, but I hope the above is useful.

**Comment by AnInfiniteNumberofMonkeys** [comment]
Hi Patrick,

Thank you...disabling the animations on Safari would work. Cheers

**Comment by AnInfiniteNumberofMonkeys** [comment]
Incidentally, I MixitUp is an amazing plugin, really excellent work!

**Comment by patrickkunka** [comment]
Thanks!
