### ISSUE TITLE
Can we have a custom lightbox as well?

### ISSUE THREAD

**Issue by praveenscience** [patrickkunka/mixitup#322]
So this is awesome. Can we also have a custom lightbox replacing what I have it in my current [dev website](https://dev.praveen.science)? I am planning to use it on my dev site, so same kind of logic but using MixItUp and not isotope. 😄 

Let me know if there's already an implementation or... ☺

**Comment by patrickkunka** [comment]
Hi Praveen,

As long as your lightbox plugin has a good API you should be able to easily integrate with MixItUp. Looking at the integration on your website - using MixItUp shouldn't be a factor as MixItUp does not dictate your markup or styling in any way. I.e, it should be no different from triggering your lightbox links from any piece of static HTML.

As per our [support guidelines](https://www.kunkalabs.com/guidelines-for-support/) I'm afraid providing custom integrations with third-party plugins is out of scope for our support. But if there's a particular issue related to MixItUp that's preventing your lightbox integration from functioning, I can certainly provide some more specific guidance.

**Comment by praveenscience** [comment]
Excellent... I just wanted to know if there's something similar with Lightbox, if not I can definitely integrate FancyBox or something of that sort. Seriously, I didn't want to use Isotope that uses the `position: absolute` thing... :) Thanks mate. Will let you know if I need any help.

**Comment by patrickkunka** [comment]
Cool - no we don't produce anything anyway, but it should be pretty trivial to integrate whatever sort of lightbox plugin you want.

One thing to be aware of. The grid on your website has some items which are styled larger than others. This is possible because of isotope's `position: absolute`-based layout. As mixitup uses pure CSS layouts, you'd need to have all your items the same size. I hope that's ok.

**Comment by praveenscience** [comment]
That's perfectly fine... I hate that "feature" about Isotope. Thanks mate. I'll keep you in loop if I find anything troublesome... Thanks for you time.

**Comment by praveenscience** [comment]
Hey @patrickkunka... Check out my website now. Had some struggles in implementing it. Because of the version mismatch, I had to spend about 3 hours to identify the issue. LoL. Are the future versions not backward compatible? Hey, temme what do you think about the website... 😄

**Comment by patrickkunka** [comment]
Looks good praveen! Nice to see the columns layout in use.

Sorry to hear about your struggles, not exactly sure what you mean but each major version introduces breaking API changes. The big difference between v2 and v3 was the dropping of jQuery, so the API had to be completely different. There shouldn't be any compatibility issues between the minor versions though.

**Comment by praveenscience** [comment]
Okay, lemme explain what happened. So, when I used the latest version, or any other number other than 2.1.11 (or whatever), the whole items part has `display: none;` applied and nothing works. The crazy part is that, it doesn't even throw any errors. :( If this helps you, coz I have used MixItUp in three projects and all of them broke due to the updates I believe. :(

**Comment by patrickkunka** [comment]
Right - yes, please check out the v3 migration guide if you want to upgrade. Particularly the section on CSS:

https://www.kunkalabs.com/mixitup/migration-guide/

**Comment by praveenscience** [comment]
Thanks mate! 😄 That should help...
