### ISSUE TITLE
Can't make it work along Bootstrap

### ISSUE THREAD

**Issue by Julianoe** [patrickkunka/mixitup#326]
Hi guys ! I'm glad i found this [thread](https://github.com/patrickkunka/mixitup/issues/268) as i have this exact problem. 
I'm using Bootstrap v4 with mixitup v3.1. The whole thing with jQuery too.

I can't make it work though ! 

For example the menu button is using `data-toggle` from Bootstrap and mixitup gives it the `mixitup-control-active` class on toggle.

Here is my init for my mixer : 

```
var config = {
            selectors: {
                control: '.data-mixitup-control'
            }
        };

$('#mixItUpContainer').mixItUp(config);

```

My filters look like this 
`<button class="col-md-2 filter btn-pink btn btn-inverse data-mixitup-control"  data-filter="all" role="button">All</button>`

What am i missing ? Oo
I tried with using [data-mixitup-control] too. Didn't work either.

**Comment by patrickkunka** [comment]
Can you try using the v3 factory API (not the v2 jQuery API)?

E.g:
```html
<button data-mixitup-control data-filter="all" role="button">All</button>
```
```js
var mixer = mixitup('#mixItUpContainer', {
    selectors: {
        control: '[data-mixitup-control]'
    }
});
```

**Comment by Julianoe** [comment]
Way better ! 

Thanks for the quick answer, i didn't get that i was using an outdated factory API.

(i'm using MixItUp in almost all my projects, lovin' it ;) )

**Comment by patrickkunka** [comment]
Great! Yeah v3 is jquery free. The old api is still there for legacy support but best avoided.
