### ISSUE TITLE
dynamically changed order value and sort does not work

### ISSUE THREAD

**Issue by persiandeveloper** [patrickkunka/mixitup#327]
Hi

I sort my list using attribute,  in some cases I change the attribute values, but when I call the sort for the second time, it does not work. 
`
<div class="container">
                <div  class="mix" id="a1"  data-q="1">r</div>
                <div  class="mix" id="a2"  data-q="3">d</div>
                <div  class="mix" id="a3"  data-q="2">w</div> 
 </div>

//first call works and sort as "dwr"
//but when called for second time, it does not change the order to wrd
mixer.sort('q:desc',true,function()
				{
					
				});

//some function that changes the each element value
				 $("#a1").attr('data-q',4);
				 $("#a2").attr('data-q',2);
			         $("#a3").attr('data-q',5);
`

**Comment by patrickkunka** [comment]
Hi,

I actually just pushed a new version to address this issue.

See this thread:

https://github.com/patrickkunka/mixitup/issues/311

**Comment by persiandeveloper** [comment]
Hi
Thanks for replying. But I grab the js version just today. Which file should I replace to solve the issue ? 
Best Regards

**Comment by patrickkunka** [comment]
You may already have the latest version then. If not, you need to update mixitup.min.js or mixitup.js (depending on whether you are using the minified version or not). 

If you have the latest, you will see the version number `v3.1.12` at the top of the mixitup code.

Once you've updated, you'll be able to activate "live sort":

```js
var mixer = mixitup(container, {
    behavior: {
        liveSort: true
    }
});
```
