### ISSUE TITLE
MixItUp Pagination: Add onPaginateStart/onPaginateEnd callbacks

### ISSUE THREAD

**Issue by patrickkunka** [patrickkunka/mixitup#329]
Currently, users are limited to using the catch all `onMixStart`/`onMixEnd` callbacks, and using state checking logic to determine if a pagination operation occurred.

For example:

```js
var activePage = 1;
var activeLimit = 8;

var mixer = mixitup(containerEl, {
    load: {
        page: activePage
    }
    pagination: {
        limit: activeLimmit
    },
    callbacks: {
        onMixEnd: function(state) {
            if (state.activePagination.limit === activeLimit && state.activePagination.page === activePage) return;

            // Pagination state has changed:

            activePage = state.activePagination.page;
            activeLimit = state.activePagination.limit;

            paginationCallback();
        }
    }
});

function paginationCallback() {
    // do something only when pagination state has changed
}
```

Adding two new paginate specific callbacks would make things a lot easier for people wanting to trigger some custom functionality (typically scroll to top of container) on page change etc.

**Comment by rachelmayo** [comment]
This is fine with basic pagination (aka not filtering anything), but once I've selected a filter (I'm using MultiFilter), the action I specified in the paginationCallback function (ie. scrolling up to the top of the gallery) no longer works. Any idea what could be causing the issue? My current code is below:

```js
var containerEl = document.querySelector('.filterable');

var activePage = 1;
var activeLimit = 9;

var mixer = mixitup(containerEl, {
    selectors: {
        control: '[data-mixitup-control]'
    },
    animation: {
        effects: 'fade'
    },
    multifilter: {
        enable: true,
        logicBetweenGroups: 'and'
    },
    load: {
        page: activePage
    },
    pagination: {
        limit: activeLimit,
        hidePageListIfSinglePage: true
    },
    templates : {
        pager: '<button type="button" class="${classNames}" data-page="${pageNumber}" data-mixitup-control>${pageNumber}</button>',
	    pagerPrev: '<button type="button" class="${classNames}" data-page="prev" data-mixitup-control>&#xf124;</button>',
	    pagerNext: '<button type="button" class="${classNames}" data-page="next" data-mixitup-control>&#xf125;</button>'    
    },
    callbacks: {
        onMixStart: state => {
            if (state.activePagination.limit === activeLimit && state.activePagination.page === activePage) return;
            activePage = state.activePagination.page;
            activeLimit = state.activePagination.limit;
            paginationCallback();
        }
    }  
});

function paginationCallback() {
    // do something only when pagination state has changed
    $("body,html").animate({
        scrollTop: $("#filters").offset().top - 140
    }, 800);
}
```

**Comment by patrickkunka** [comment]
Hello,

Do you mean the scrolling code doesn't run when you click a filter, or it doesn't run when changing page while a filter is active?

**Comment by rachelmayo** [comment]
I select a filter, go to the pagination to click a page number, and the pagination takes me to the page I chose, but it doesn't scroll to the top. If I hadn't selected a filter and went straight to the pagination, it scrolls fine!

**Comment by patrickkunka** [comment]
Do you happen to have a link to your project so I can take a look?

**Comment by rachelmayo** [comment]
Unfortunately the staging environment is behind a firewall for work, so you'd have to send me your IP address so I can have IT whitelist it. Feel free to email me (rmayo@topspotims.com) if you don't want to post publicly. :)

**Comment by patrickkunka** [comment]
Hi Rachel,

The code getting called, but it's jumpy / buggy because it's attached to onMixStart (probably the fault of my abstract example above). For this type of scroll to top functionality, you're better attaching to the onMixEnd callback, so that jquery's geometry calculations are done against the final up to date container height and position. 

Let me know if that helps. Have updated my example.

**Comment by rachelmayo** [comment]
@patrickkunka That's what I needed! Thank you!

**Comment by VanWebDev** [comment]
Just a quick question on this. The onMixEnd callback as shown in your examples is causing the interface buttons to be not selectable on older ios devices. (Iphone 4S & ipad Mini 1). Safari console says there's an unexpected > in the following - it would be the one in the onMixEnd line:

`    callbacks: {

        onMixEnd: state => {

            if (state.activePagination.limit === activeLimit && state.activePagination.page === activePage) return;
    
        activePage = state.activePagination.page;
   
         activeLimit = state.activePagination.limit;
   
         paginationCallback();
 
       }

    }    `

Is there something other way to implement this so that filtering works for these devices with back-to-top functionality?

**Comment by patrickkunka** [comment]
The example above is written in ES6 JavaScript (specifically lamda function syntax), and would typically be transpiled to ES5 for production using Babel or similar. 

If you're not running this kind of dev environment, you can just rewrite the example in ES5. See the callback docs for a reference - everything is written in ES5.

**Comment by VanWebDev** [comment]
Thank you. I wasn't aware so much had changed in the new version, or I wouldn't have planned to use it until I had time to read all the new documentation. On a deadline with mobile being a royal pain... appreciate the assist.

**Comment by patrickkunka** [comment]
No problem. FYI – this isn't actually anything to do with MixItUp - its just the latest version of JavaScript, which I had written like that for my own reference. I have now changed the example to ES5.

**Comment by patrickkunka** [comment]
These callbacks are now added in the latest version of Pagination v3.3.0.

**Comment by SINOUS123** [comment]
> Bonjour,
> 
> Voulez-vous dire que le code de défilement ne s'exécute pas lorsque vous cliquez sur un
