### ISSUE TITLE
Implementing Pagination

### ISSUE THREAD

**Issue by ericanafziger** [patrickkunka/mixitup#332]
Hello, 

I am trying to implement pagination with the base MixItUp JS based on this Code Pen example: https://codepen.io/patrickkunka/pen/btCim

I realize this is based on an older example of MixItUp and I DO have the latest version installed as well as the latest version of MixItUp Pagination. MixItUp itself is working in my project, however, despite the various combinations I have tried the pagination is not working. Any help or guidance on where else to look for an example would be appreciated!

Thanks.

**Comment by patrickkunka** [comment]
Hi Erica,

If you could paste your mixitup configuration, and any custom JS event handler code for the selects in here I can take a look.

Also could you describe exactly what you mean by its not working? Are there any errors in the console?

**Comment by ericanafziger** [comment]
Thanks, Patrick. I'm sure I'm missing something obvious, but essentially there are no errors in the console, and I know the MixItUp pagination function is being loaded because I can call the function and see it in the browser console - but no pagination is occurring. Meanwhile, the base MixItUp functionality is working great. Here is the JS code:

```
$(document).foundation();

// To keep our code clean and modular, all custom functionality will be contained inside a single object literal called "dropdownFilter".

var dropdownFilter = {

  // Declare any variables we will need as properties of the object

  $filters: null,
  $reset: null,
  groups: [],
  outputArray: [],
  outputString: '',

  // The "init" method will run on document ready and cache any jQuery objects we will need.

  init: function(){
    var self = this; // As a best practice, in each method we will assign "this" to the variable "self" so that it remains scope-agnostic. We will use it to refer to the parent "dropdownFilter" object so that we can share methods and properties between all parts of the object.

    self.$filters = $('.filter-bar');
    self.$reset = $('#Reset');
    self.$container = $('.container');


    self.$filters.find('fieldset').each(function(){
      self.groups.push({
        $dropdown: $(this).find('select'),
        active: ''
      });
    });

    self.bindHandlers();
  },

  // The "bindHandlers" method will listen for whenever a select is changed.

  bindHandlers: function(){
    var self = this;

    // Handle select change

    self.$filters.on('change', 'select', function(e){
      e.preventDefault();

      self.parseFilters();
    });

    // Handle reset click

    self.$reset.on('click', function(e){
      e.preventDefault();

      self.$filters.find('select').val('');

      self.parseFilters();
    });
  },

  // The parseFilters method pulls the value of each active select option

  parseFilters: function(){
    var self = this;

    // loop through each filter group and grap the value from each one.

    for(var i = 0, group; group = self.groups[i]; i++){
      group.active = group.$dropdown.val();
    }

    self.concatenate();
  },

  // The "concatenate" method will crawl through each group, concatenating filters as desired:

  concatenate: function(){
    var self = this;

    self.outputString = ''; // Reset output string

    for(var i = 0, group; group = self.groups[i]; i++){
      self.outputString += group.active;
    }

    // If the output string is empty, show all rather than none:

    !self.outputString.length && (self.outputString = 'all');

    // ^ we can check the console here to take a look at the filter string that is produced

    // Send the output string to MixItUp via the 'filter' method:

    self.$container.mixItUp('filter', self.outputString);

  }

};

// On document ready, initialize our code.

$(function(){

  dropdownFilter.init();

  // Instantiate MixItUp
  mixItUp.use(mixitupPagination);


  $('.container').mixItUp({
    load: {
	    filter: 'all'
    },
    layout: {
        display: 'block',
        containerClassFail: 'none-found'
    },
    controls: {
      enable: true // we won't be needing these
    },
    classNames: {
      elementPager: 'pager'
    },
    classNames: {
      elementPageList: 'pagination-info'
    },
    pagination: {
      limit: 4
    },
    animation: {
      enable: false
    },
    callbacks: {
      onMixLoad: function(){
        $(this).mixItUp('setOptions', {
          animation: {
            enable: true,
            effects: 'fade scale',
	    duration: 350
          }
        });
      }
    }
  });

});
```

**Comment by ericanafziger** [comment]
![screen shot 2017-06-19 at 8 50 25 am](https://user-images.githubusercontent.com/20483621/27293836-6815fe1a-54cc-11e7-9523-28f4a0a62633.png)

I did notice that the function I am using calls mixItUp() rather than mixitup() and when I change it to the non-camel case version I receive the error: Uncaught TypeError: $(...).mixitup is not a function

**Comment by patrickkunka** [comment]
Hi Erica,

Thanks for the information.

The code you are using above is from an older version of MixItUp, and is not compatible with v3.

It has been superseded by the [MultiFilter extension](https://www.kunkalabs.com/mixitup-multifilter/) which integrates with the Pagination Extension. This extension is specifically for UI where you want to filter by multiple dimensions simultaneously.

The codepen you originally linked to does not use this type of filtering however – it's just an example of using `<select>` elements for UI with basic filtering/sorting.

If this is all you want to do, then you don't need the MultiFilter extension. You will find several demos included in the Pagination zip file that can help you get up and running with Pagination.

In terms of adapting the select option code in the codepen example to work with MixItUp 3, and with pagination, you can do the following:

```js
var filterSelect = document.querySelector('#FilterSelect');
var sortSelect = document.querySelector('#SortSelect');

var mixer = mixitup('#Container', {
    pagination: {
        limit: 8
    }
});

filterSelect.addEventListener('change', function() {
    mixer.filter(filterSelect.value);
});

sortSelect.addEventListener('change', function() {
    mixer.sort(sortSelect.value);
});
```

**Comment by ericanafziger** [comment]
Thank you. Just to clarify, are you saying that if I wish to use Pagination and filter content from several select dropdowns I will need to purchase the MultiFilter extension as well?

**Comment by patrickkunka** [comment]
Only if you need "multidimensional" filtering, as described in this tutorial:

https://www.kunkalabs.com/tutorials/filtering-with-mixitup/

The jQuery code you posted above was an early attempt at multi-dimensional filtering, but unfortunately it is not compatible with v3, or the Pagination Extension (it's about 4 years old).

That has now been improved and generalised considerably and moved into its own extension (MultiFilter).

If you only need basic filtering, you can use the code I included above.

Hopefully the filtering tutorial will help you understand exactly what you need.

**Comment by ericanafziger** [comment]
Thank you! I see that I only need basic filtering to show category matching target A AND target B.

I have now included: 
```

var filterOne = document.querySelector('#filterOne');
var filterTwo = document.querySelector('#filterTwo');

var mixer = mixitup('.container', {
    controls: {
        toggleLogic: 'and'
    }
});

  filterImpact.addEventListener('change', function() {
    mixer.filter(filterVertical.value);
      mixer.filter(filterImpact.value);
  });
  filterVertical.addEventListener('change', function() {
      mixer.filter(filterImpact.value);
      mixer.filter(filterVertical.value);
  });
```
On the front end:

```
<select for="filterOne" data-custom-id="drop-filterVertical" id="filterOne" class="selectpicker" name="optionsList">
              <option data-filter="all" value="all">All</option>
              <option data-toggle=".optionOne" class="filter" value=".optionOne">Option 1</option>
              <option data-toggle=".optionTwo" class="filter" value=".optionTwo">Option 2</option>
              <option data-toggle=".optionThree" class="filter" value=".optionThree">Option 3</option>
</select>

<select for="filterTwo" data-custom-id="drop-filterImpact" id="filterTwo" class="selectpicker" name="optionsList">
              <option data-filter="all" value="all">All</option>
              <option data-toggle=".chooseOne" class="filter" value=".chooseOne">Choose 1</option>
              <option data-toggle=".chooseTwo" class="filter" value=".chooseTwo">Choose 2</option>
              <option data-toggle=".chooseThree" class="filter" value=".chooseOne">Choose 3</option>
</select>
```

Obviously the last mixer.filter() is overriding the first at this point and no toggling functionality is taking place. Do you have a demo of how to chain these together? All the tutorials I am going through don't show any examples with select tags as they are all dealing with buttons for toggling. 

I apologize for all the questions. It would be incredibly helpful to see a few tutorials in the documentation that don't use buttons and show a little more of the backend JS! I appreciate your help!

**Comment by patrickkunka** [comment]
Great! I think you're almost there.

So according to your description, you need to concatenate together with AND logic.

I would suggest the following approach. With this code, you can add as many `<select>` elements as you want.

```html
<select class="select-filter">
    <option value="">All</option>
    <option value=".option-1">Option 1</option>
    <option value=".option-2">Option 2</option>
</select>

<select class="select-filter">
    <option value="">All</option>
    <option value=".category-1">Category 1</option>
    <option value=".catagory-2">Category 2</option>
</select>
```

```js
// Query all <select> elements and cast into an array
var selects = Array.from(document.querySelector('.select-filter'));

function combineSelectors() {
    var selectors = [];

    // Iterate through each <select>, if it has a value, push into selectors array
    selects.forEach(function(select) {
        if (select.value !== '') selectors.push(select.value);
    });

    // Concatenate all selectors in the array using AND logic
    return selectors.join(''); // NB: OR logic would be `join(', ')`
}

// On change of any <select>, obtain the final selector, and filter the mixer
handleChange() {
    var selector = combineSelectors;

    mixer.filter(selector);
}

// Bind the change handler to each <select> element
selects.forEach(function(select) {
    select.addEventListener('change', handleChange);
});

// NB: You could also add a single change handler to a common parent element of all <select> elements.
```

**Comment by ericanafziger** [comment]
Thanks, Patrick! 

I just discovered something similar about 5 minutes ago, although I'll probably give yours a whirl because it seems like a more elegant solution. I wasn't sure if there was something built in with MixItUp or not. 

Thank you so much for all of your help! Hope you have a great rest of your day.

**Comment by franzzco** [comment]
Hello, I know this message is old, but I don't know much about programming and I want to add pagination to that example, it is a simple dropdown like the one in the example but I can't do it because I don't understand the language well. Can it be done or is it with the premium version?
