### ISSUE TITLE
Adding class on filtered item w/o hiding them

### ISSUE THREAD

**Issue by orientis-gourmet** [patrickkunka/mixitup#335]
Hello.
May be I missed somthing... but I didn't find a way to prevent hiding with the online "style='display:none'" on filtered item.
I think it could be usefull let visible filtered items and just identify this items with the mixitup.State (or class).

Thanks about your plugin, it's quite awesome

**Comment by patrickkunka** [comment]
Hello,

I get this question a lot, and I usually tell people that you don't need MixItUp do this. MixItUp is a fairly complex library designed to smoothly animating elements between hidden and shown states. So if you just wanted to add some class names to items matching your selector string (for example), you can just do something like this:

```js
Array.from(container.children).forEach(el => (el.matches('.my-category') ? el.classList.add('matching') : el.classList.remove('matching')));
```

There's a bunch more you could do with this obviously, and you'll hopefully save yourself a lot of KB!

**Comment by orientis-gourmet** [comment]
I understand your point. But I'm using your plugin because it's a powerfull tool to filter and toogleproduct on my product list page. Callbacks are completly usefull too. 
In order to made transformation like styling (w/o modify display of all item) it could be a good a functionnaly no?

**Comment by patrickkunka** [comment]
That's good to hear. I appreciate there's a lot more functionality in MixItUp at this point than there was early on (especially including the extensions), so I'll definitely give it some thought.

I've been thinking about decoupling the filter/toggle/ui functionality from the DOM manipulation/animation functionality in a future refactor, so that would probably be the time to add this kind of thing.

**Comment by EricJammin** [comment]
@patrickkunka - So is there any way to access / target the elements which have been hidden after a filtering option is selected?

I have a unique case where I have limited control over the output HTML structure of the target items. In my case, for the elements which have the correct classes to use for filtering, they are each wrapped inside of a parent div. So while the filtering hides the contents, the parent div of each item is not hidden, so there is blank white space showing.

I can not figure out a workaround for this based on the documentation. Am I SOL here?

In my mind I was trying to figure out how to target the parents of each hidden element using onMixEnd callback, or something similar but I don't see a way to target them.

**Comment by stratboy** [comment]
I personally would need to mark some way filtered elements. That's because I need to alternate-colour them, but without any class to use to get only visible items, I cannot maintain alternate colours upon filtering. Any idea?
