### ISSUE TITLE
Dataset API error during simultaneous filtering/sorting

### ISSUE THREAD

**Issue by ghost** [patrickkunka/mixitup#337]
When using the Dataset API from MixItUp, a NotFoundError occurs within MixItUp. This can be reliably reproduced with [this JSFiddle](https://jsfiddle.net/yas4bxyn/1/):

1. When clicking "Canada", 3 Canadian cities are shown.
2. When clicking "All" afterwards, no cities are shown. (Expected behaviour: All 23 cities are shown.)

The error does _not_ occur when using a different ordering of the cities; for example:
`function canadianCities() {
    setDataset([ "Edmonton", "Victoria", "Ottawa" ]);
}`

Is this maybe a bug within MixItUp? I closely followed the Dataset API Tutorial, but I am stuck at this point. Any help would be appreciated.

**Comment by patrickkunka** [comment]
Hi Markus,

Thanks for reporting this, it does appear to be a bug relating to the order of the common items changing. I'll hopefully take a look at this over the weekend.

**Comment by patrickkunka** [comment]
Review https://github.com/patrickkunka/mixitup/issues/267

**Comment by ghost** [comment]
Hi Patrick,

Thanks for your quick reply. I had a look at #267 but this does not resolve the issue mentioned above. I am not using the dirtyCheck feature (yet) and my JSFiddle already uses **data-ref="item"** as you suggested. Could you please look into this?

**Comment by patrickkunka** [comment]
Apologies, that note was for my own reference and I closed the issue by mistake! I'll still be looking into a fix over the weekend.

**Comment by patrickkunka** [comment]
Hi Markus,

This should be fixed in https://github.com/patrickkunka/mixitup/releases/tag/v3.2.0

Let me know if it works for you.

**Comment by ghost** [comment]
Thanks, Patrick, for looking into this issue. The case with the Canadian cities works now. However, if I use `[ "Berlin", "München", "Hamburg", "Frankfurt", "Düsseldorf", "Dresden" ]` instead of `[ "Ottawa", "Edmonton", "Victoria" ]`, then the NotFoundError occurs again. You can check this out in my [updated JSFiddle](https://jsfiddle.net/yas4bxyn/2/).

**Comment by patrickkunka** [comment]
Thanks for the additional info. The problem was a little more complex than I realised.

This should be fixed in https://github.com/patrickkunka/mixitup/releases/tag/v3.2.1

Again, please test and let me know.

**Comment by ghost** [comment]
Thanks for the new release. My test cases are working now :-)
