### ISSUE TITLE
Mixitup failing and running twice when multifilter is enabled

### ISSUE THREAD

**Issue by ghost** [patrickkunka/mixitup#338]
I'm having an issue only when multi-filter is enabled.

The page loads correctly, but when I click a filter it filters correctly, and then filters again incorrectly using an activeFilter.selector of "on", which doesn't exist anywhere in my markup. I'm console logging the mixer state onMixEnd and onMixFail, and in my console I get 1 successful state, then 1 failed state with hasFailed: true, and the resulting failed state.

I can't figure out why Mixitup is attempting to filter a second time after I click on a filter, and where the "on" selector is coming from.

My multifilter config object: 
```js
{
enable: true,
keyupThrottleDuration: 350,
logicBetweenGroups: "and",
logicWithinGroup: "or",
minSearchLength: 3,
parseOn: "change"
}
```

My mixitup config object:
```js
{
    controls: {
      enable: true,
      live: true
    },
    multifilter: {
      enable: true
    },
    load: {
      filter: 'all'
    },
    callbacks: {
      onMixEnd: function(state, originalEvent) {
        console.info('MIX END',state);
      },
      onMixFail: function(state) {
        console.info('MIX FAIL',state);
      },
      onParseFilterGroups: function(command) {
        console.info('FILTER GROUP PARSE',command);
          return command;
      }
    }
```

I'm not using any additional API methods or events for filters.

**Comment by patrickkunka** [comment]
Hi,

Can you include the markup for you filtering UI?

**Comment by k3j** [comment]
There are 5 of these different filter group blocks but here's one:
`<div class="refinement-sunglass-lens-color filter-accordion-block" style="display: block;">
  <div class="filter-title">
    Lens Color
  </div>
  <ul class="refinement-list" data-filter-group="" data-option="lenscolor">
    <li class="filter-select-wrapper lenscolor-clear">
      <input class="toggle-button checkbox-custom" data-filter-title="clear" data-filter-type="lenscolor" data-toggle=".lenscolor-clear" id="lenscolor-clear" type="checkbox">
      <label class="filter-value checkbox-custom-label" for="lenscolor-clear" title="clear">clear</label>
    </li>
    <li class="filter-select-wrapper lenscolor-gold">
      <input class="toggle-button checkbox-custom" data-filter-title="gold" data-filter-type="lenscolor" data-toggle=".lenscolor-gold" id="lenscolor-gold" type="checkbox">
      <label class="filter-value checkbox-custom-label" for="lenscolor-gold" title="gold">gold</label>
    </li>
    <li class="filter-select-wrapper lenscolor-brown">
      <input class="toggle-button checkbox-custom" data-filter-title="brown" data-filter-type="lenscolor" data-toggle=".lenscolor-brown" id="lenscolor-brown" type="checkbox">
      <label class="filter-value checkbox-custom-label" for="lenscolor-brown" title="brown">brown</label>
    </li>
    <li class="filter-select-wrapper lenscolor-mirror">
      <input class="toggle-button checkbox-custom" data-filter-title="mirror" data-filter-type="lenscolor" data-toggle=".lenscolor-mirror" id="lenscolor-mirror" type="checkbox">
      <label class="filter-value checkbox-custom-label" for="lenscolor-mirror" title="mirror">mirror</label>
    </li>
    <li class="filter-select-wrapper lenscolor-green">
      <input class="toggle-button checkbox-custom" data-filter-title="green" data-filter-type="lenscolor" data-toggle=".lenscolor-green" id="lenscolor-green" type="checkbox">
      <label class="filter-value checkbox-custom-label" for="lenscolor-green" title="green">green</label>
    </li>
    <li class="filter-select-wrapper lenscolor-blue">
      <input class="toggle-button checkbox-custom" data-filter-title="blue" data-filter-type="lenscolor" data-toggle=".lenscolor-blue" id="lenscolor-blue" type="checkbox">
      <label class="filter-value checkbox-custom-label" for="lenscolor-blue" title="blue">blue</label>
    </li>
    <li class="filter-select-wrapper lenscolor-grey">
      <input class="toggle-button checkbox-custom" data-filter-title="grey" data-filter-type="lenscolor" data-toggle=".lenscolor-grey" id="lenscolor-grey" type="checkbox">
      <label class="filter-value checkbox-custom-label" for="lenscolor-grey" title="grey">grey</label>
    </li>
    <li class="filter-select-wrapper lenscolor-rose">
      <input class="toggle-button checkbox-custom" data-filter-title="rose" data-filter-type="lenscolor" data-toggle=".lenscolor-rose" id="lenscolor-rose" type="checkbox">
      <label class="filter-value checkbox-custom-label" for="lenscolor-rose" title="rose">rose</label>
    </li>
    <li class="filter-select-wrapper lenscolor-silver">
      <input class="toggle-button checkbox-custom" data-filter-title="silver" data-filter-type="lenscolor" data-toggle=".lenscolor-silver" id="lenscolor-silver" type="checkbox">
      <label class="filter-value checkbox-custom-label" for="lenscolor-silver" title="silver">silver</label>
    </li>
  </ul>
</div>`

**Comment by k3j** [comment]
There are 5 different filter group blocks but here's one:

<div class="refinement-sunglass-lens-color filter-accordion-block" style="display: block;">
  <div class="filter-title">
    Lens Color
  </div>
  <ul class="refinement-list" data-filter-group="" data-option="lenscolor">
    <li class="filter-select-wrapper lenscolor-clear">
      <input class="toggle-button checkbox-custom" data-filter-title="clear" data-filter-type="lenscolor" data-toggle=".lenscolor-clear" id="lenscolor-clear" type="checkbox">
      <label class="filter-value checkbox-custom-label" for="lenscolor-clear" title="clear">clear</label>
    </li>
    <li class="filter-select-wrapper lenscolor-gold">
      <input class="toggle-button checkbox-custom" data-filter-title="gold" data-filter-type="lenscolor" data-toggle=".lenscolor-gold" id="lenscolor-gold" type="checkbox">
      <label class="filter-value checkbox-custom-label" for="lenscolor-gold" title="gold">gold</label>
    </li>
    <li class="filter-select-wrapper lenscolor-brown">
      <input class="toggle-button checkbox-custom" data-filter-title="brown" data-filter-type="lenscolor" data-toggle=".lenscolor-brown" id="lenscolor-brown" type="checkbox">
      <label class="filter-value checkbox-custom-label" for="lenscolor-brown" title="brown">brown</label>
    </li>
    <li class="filter-select-wrapper lenscolor-mirror">
      <input class="toggle-button checkbox-custom" data-filter-title="mirror" data-filter-type="lenscolor" data-toggle=".lenscolor-mirror" id="lenscolor-mirror" type="checkbox">
      <label class="filter-value checkbox-custom-label" for="lenscolor-mirror" title="mirror">mirror</label>
    </li>
    <li class="filter-select-wrapper lenscolor-green">
      <input class="toggle-button checkbox-custom" data-filter-title="green" data-filter-type="lenscolor" data-toggle=".lenscolor-green" id="lenscolor-green" type="checkbox">
      <label class="filter-value checkbox-custom-label" for="lenscolor-green" title="green">green</label>
    </li>
    <li class="filter-select-wrapper lenscolor-blue">
      <input class="toggle-button checkbox-custom" data-filter-title="blue" data-filter-type="lenscolor" data-toggle=".lenscolor-blue" id="lenscolor-blue" type="checkbox">
      <label class="filter-value checkbox-custom-label" for="lenscolor-blue" title="blue">blue</label>
    </li>
    <li class="filter-select-wrapper lenscolor-grey">
      <input class="toggle-button checkbox-custom" data-filter-title="grey" data-filter-type="lenscolor" data-toggle=".lenscolor-grey" id="lenscolor-grey" type="checkbox">
      <label class="filter-value checkbox-custom-label" for="lenscolor-grey" title="grey">grey</label>
    </li>
    <li class="filter-select-wrapper lenscolor-rose">
      <input class="toggle-button checkbox-custom" data-filter-title="rose" data-filter-type="lenscolor" data-toggle=".lenscolor-rose" id="lenscolor-rose" type="checkbox">
      <label class="filter-value checkbox-custom-label" for="lenscolor-rose" title="rose">rose</label>
    </li>
    <li class="filter-select-wrapper lenscolor-silver">
      <input class="toggle-button checkbox-custom" data-filter-title="silver" data-filter-type="lenscolor" data-toggle=".lenscolor-silver" id="lenscolor-silver" type="checkbox">
      <label class="filter-value checkbox-custom-label" for="lenscolor-silver" title="silver">silver</label>
    </li>
  </ul>
</div>
`<div class="refinement-sunglass-lens-color filter-accordion-block" style="display: block;">
  <div class="filter-title">
    Lens Color
  </div>
  <ul class="refinement-list" data-filter-group="" data-option="lenscolor">
    <li class="filter-select-wrapper lenscolor-clear">
      <input class="toggle-button checkbox-custom" data-filter-title="clear" data-filter-type="lenscolor" data-toggle=".lenscolor-clear" id="lenscolor-clear" type="checkbox">
      <label class="filter-value checkbox-custom-label" for="lenscolor-clear" title="clear">clear</label>
    </li>
    <li class="filter-select-wrapper lenscolor-gold">
      <input class="toggle-button checkbox-custom" data-filter-title="gold" data-filter-type="lenscolor" data-toggle=".lenscolor-gold" id="lenscolor-gold" type="checkbox">
      <label class="filter-value checkbox-custom-label" for="lenscolor-gold" title="gold">gold</label>
    </li>
    <li class="filter-select-wrapper lenscolor-brown">
      <input class="toggle-button checkbox-custom" data-filter-title="brown" data-filter-type="lenscolor" data-toggle=".lenscolor-brown" id="lenscolor-brown" type="checkbox">
      <label class="filter-value checkbox-custom-label" for="lenscolor-brown" title="brown">brown</label>
    </li>
    <li class="filter-select-wrapper lenscolor-mirror">
      <input class="toggle-button checkbox-custom" data-filter-title="mirror" data-filter-type="lenscolor" data-toggle=".lenscolor-mirror" id="lenscolor-mirror" type="checkbox">
      <label class="filter-value checkbox-custom-label" for="lenscolor-mirror" title="mirror">mirror</label>
    </li>
    <li class="filter-select-wrapper lenscolor-green">
      <input class="toggle-button checkbox-custom" data-filter-title="green" data-filter-type="lenscolor" data-toggle=".lenscolor-green" id="lenscolor-green" type="checkbox">
      <label class="filter-value checkbox-custom-label" for="lenscolor-green" title="green">green</label>
    </li>
    <li class="filter-select-wrapper lenscolor-blue">
      <input class="toggle-button checkbox-custom" data-filter-title="blue" data-filter-type="lenscolor" data-toggle=".lenscolor-blue" id="lenscolor-blue" type="checkbox">
      <label class="filter-value checkbox-custom-label" for="lenscolor-blue" title="blue">blue</label>
    </li>
    <li class="filter-select-wrapper lenscolor-grey">
      <input class="toggle-button checkbox-custom" data-filter-title="grey" data-filter-type="lenscolor" data-toggle=".lenscolor-grey" id="lenscolor-grey" type="checkbox">
      <label class="filter-value checkbox-custom-label" for="lenscolor-grey" title="grey">grey</label>
    </li>
    <li class="filter-select-wrapper lenscolor-rose">
      <input class="toggle-button checkbox-custom" data-filter-title="rose" data-filter-type="lenscolor" data-toggle=".lenscolor-rose" id="lenscolor-rose" type="checkbox">
      <label class="filter-value checkbox-custom-label" for="lenscolor-rose" title="rose">rose</label>
    </li>
    <li class="filter-select-wrapper lenscolor-silver">
      <input class="toggle-button checkbox-custom" data-filter-title="silver" data-filter-type="lenscolor" data-toggle=".lenscolor-silver" id="lenscolor-silver" type="checkbox">
      <label class="filter-value checkbox-custom-label" for="lenscolor-silver" title="silver">silver</label>
    </li>
  </ul>
</div>`

**Comment by ghost** [comment]
```
<div class="refinement-sunglass-lens-color filter-accordion-block" style="display: block;">
  <div class="filter-title">
    Lens Color
  </div>
  <ul class="refinement-list" data-filter-group="" data-option="lenscolor">
    <li class="filter-select-wrapper lenscolor-clear">
      <input class="toggle-button checkbox-custom" data-filter-title="clear" data-filter-type="lenscolor" data-toggle=".lenscolor-clear" id="lenscolor-clear" type="checkbox">
      <label class="filter-value checkbox-custom-label" for="lenscolor-clear" title="clear">clear</label>
    </li>
    <li class="filter-select-wrapper lenscolor-gold">
      <input class="toggle-button checkbox-custom" data-filter-title="gold" data-filter-type="lenscolor" data-toggle=".lenscolor-gold" id="lenscolor-gold" type="checkbox">
      <label class="filter-value checkbox-custom-label" for="lenscolor-gold" title="gold">gold</label>
    </li>
    <li class="filter-select-wrapper lenscolor-brown">
      <input class="toggle-button checkbox-custom" data-filter-title="brown" data-filter-type="lenscolor" data-toggle=".lenscolor-brown" id="lenscolor-brown" type="checkbox">
      <label class="filter-value checkbox-custom-label" for="lenscolor-brown" title="brown">brown</label>
    </li>
    <li class="filter-select-wrapper lenscolor-mirror">
      <input class="toggle-button checkbox-custom" data-filter-title="mirror" data-filter-type="lenscolor" data-toggle=".lenscolor-mirror" id="lenscolor-mirror" type="checkbox">
      <label class="filter-value checkbox-custom-label" for="lenscolor-mirror" title="mirror">mirror</label>
    </li>
    <li class="filter-select-wrapper lenscolor-green">
      <input class="toggle-button checkbox-custom" data-filter-title="green" data-filter-type="lenscolor" data-toggle=".lenscolor-green" id="lenscolor-green" type="checkbox">
      <label class="filter-value checkbox-custom-label" for="lenscolor-green" title="green">green</label>
    </li>
    <li class="filter-select-wrapper lenscolor-blue">
      <input class="toggle-button checkbox-custom" data-filter-title="blue" data-filter-type="lenscolor" data-toggle=".lenscolor-blue" id="lenscolor-blue" type="checkbox">
      <label class="filter-value checkbox-custom-label" for="lenscolor-blue" title="blue">blue</label>
    </li>
    <li class="filter-select-wrapper lenscolor-grey">
      <input class="toggle-button checkbox-custom" data-filter-title="grey" data-filter-type="lenscolor" data-toggle=".lenscolor-grey" id="lenscolor-grey" type="checkbox">
      <label class="filter-value checkbox-custom-label" for="lenscolor-grey" title="grey">grey</label>
    </li>
    <li class="filter-select-wrapper lenscolor-rose">
      <input class="toggle-button checkbox-custom" data-filter-title="rose" data-filter-type="lenscolor" data-toggle=".lenscolor-rose" id="lenscolor-rose" type="checkbox">
      <label class="filter-value checkbox-custom-label" for="lenscolor-rose" title="rose">rose</label>
    </li>
    <li class="filter-select-wrapper lenscolor-silver">
      <input class="toggle-button checkbox-custom" data-filter-title="silver" data-filter-type="lenscolor" data-toggle=".lenscolor-silver" id="lenscolor-silver" type="checkbox">
      <label class="filter-value checkbox-custom-label" for="lenscolor-silver" title="silver">silver</label>
    </li>
  </ul>
</div>
```

**Comment by patrickkunka** [comment]
Thanks, the problem is that you are mixing inputs and toggles.

If you are using inputs, you include your selector string as the input's `value` attribute.

You should only use the data-filter or data-toggle attributes for filter and toggle control buttons. Radio and checkbox inputs have this behaviour built in natively, so we dont need to reverse engineer it, which is essentially what filter and toggle controls are doing.

You can check out the markup of the included demos for examples of functioning UI.
