### ISSUE TITLE
Dataset API fails after sorting using JQuery UI

### ISSUE THREAD

**Issue by lesleyauk** [patrickkunka/mixitup#340]
I am using [jQuery UI's sortable()](http://api.jqueryui.com/sortable) to allow the user to sort items added by MixItUp Dataset. I send the new sorting to the server but when I try to refresh the Dataset with that data, MixItUp fails, logging the following error:

> Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node. at e.Mixer.printSort

See it happening in this Fiddle: https://jsfiddle.net/eu9f60ox/

**Comment by patrickkunka** [comment]
Hi and thanks for the reproduction.

It is not possible to use Dataset in this way - if you manipulate the DOM externally, the internal DOM manipulation algorithms will lose track of where items are and future DOM manipulations will fail.

The way to get around this, is to destroy the mixer instance after a sort as taken place, then re-instantiate it using the "Option 2: Pre-rendered Targets" approach described in [this tutorial]( https://www.kunkalabs.com/tutorials/using-the-dataset-api/), as the order returned from your server should match the order of targets in the DOM at this point.

This ensures that the mixer is always in sync with the DOM.

I have made some changes to the JSFiddle to demonstrate.

https://jsfiddle.net/eu9f60ox/1/
