### ISSUE TITLE
API Methods insert()

### ISSUE THREAD

**Issue by delcon** [patrickkunka/mixitup#347]
Inserting a html string with whitespaces and/or newline can cause failure in creating the new element. 

I have not tested if it is whitespace or newline characters, but stripping them both out solved my issues.

Workaround: create a jQuery element from string, then insert jQuery element,

**Comment by patrickkunka** [comment]
Fixed in https://github.com/patrickkunka/mixitup/releases/tag/v3.2.2.

Whitespace is now trimmed from all HTML strings sent to `.insert()`
