### ISSUE TITLE
Multifilter declaration causing js drop-menu to not close on select. 

### ISSUE THREAD

**Issue by VanWebDev** [patrickkunka/mixitup#348]
I have a page that has rather a lot of filters, so am using a dropdown menu for the bottom one.

- If single filtering, the drop menu functions correctly and closes when a menu item is selected.

- When multifilter is enabled, the drop menu stays open once selected and one must manually click outside the menu (or on the trigger item at the top) in order to close it. On mobile devices, which this is intended for, the menu is full width, so it requires excess scrolling and isn't user friendly at all. 

Just wondering where this conflict is coming from. Everything else is working correctly.

**Staging Site:**

Drop menu  displays at screen width of 909px or less. 

Multifilter on, drop menu not closing correctly: [Example A](http://vancouverwebdev.com/devsites/vwf/festival-events-october-2017/)

Multifilter off, drop menu working correctly: [Example B](http://vancouverwebdev.com/devsites/vwf/festival-event-search-demo/)

(It takes a few seconds to load - sorry for that - the client wants too much data pulled for each item - negotiating!)

The code for these two pages is identical. _The only difference is the multifilter enable_. Whether or not pagination is being used has no effect on it at all. I have tried re-ordering, changing the drop script, putting it in the header, everything. It's consistent no matter what I try.

**Comment by patrickkunka** [comment]
Apologies for the delay in response. I'm guessing you found a better solution or gave up on the dropdown as I don't see it on your demo pages. Will close for now, but let me know if you want to reopen.
