### ISSUE TITLE
Pagination doesn't revert to page 1 on filter change

### ISSUE THREAD

**Issue by VanWebDev** [patrickkunka/mixitup#349]
When I use the pagination for mixitup3 and switch between filters, it displays the results of whatever page I was on in the previous filter (or the closest one to it), of the new results list. 

So if I am on page 2 and switch filters, it will show me page 2 of the new filter group when it should go to page 1.

[Demo Here](http://vancouverwebdev.com/devsites/vwf/fest-search-pagination-test/)

- Once the page is loaded, scroll down and go to page 2. 

- Then click any of the date filters (except the 16th which only has one item), and scroll down 

- You'll see that it brought up page 2 instead of loading page 1 of the new results

It will continue loading page 2 whenever you switch filters, unless you go to another results page - then it will load that page of the new results when you switch filters.

**Old version**
If it helps, this was not an issue in the old version of mixitup with pagination. It works correctly. 

Working version with the old mixitup: [Demo Here](http://jengfeller.com/ducks-geese/) 

If you go to page 2, then click on either ducks or geese, it goes back to page one. This is the functionality I want, but with mixitup3.

**Comment by patrickkunka** [comment]
Please check out the `pagination.maintainActivePage` configuration option, added in v3. You can set this to `false` to ensure that changing a filter will return you to page 1.

https://www.kunkalabs.com/mixitup-pagination/docs/configuration-object/

Apologies that some of these options are not fully documented.

**Comment by VanWebDev** [comment]
So many new options, sorry I missed that one somehow. Thanks so much.
