### ISSUE TITLE
Add Class between onMixStart and onMixEnd

### ISSUE THREAD

**Issue by mattpilott** [patrickkunka/mixitup#351]
Hi,

I have a mixitup grid with a masonry style layout, I need to change some classes after the mixitup items have disappeared and before they reappear in the new layout.

How can I do this?

Here's what I have so far which almost works (click green or blue mainly)

https://codepen.io/matt3224/pen/mMWexb?editors=0010

Thank you!

**Comment by mattpilott** [comment]
Okay I've updated that pen with something that works although is not particularly pleasant to look at. Is there a nicer way to do this?

**Comment by patrickkunka** [comment]
Very creative! Have you considered using Isotope?

Sadly, MixItUp isn't really designed to be used like this – so some custom code like you've added would be the best way.

However, since you're not making any use of MixItUp's animation algorithm, that's *a lot* of wasted overhead. You could just as easily achieve this kind of basic out and in filtering with a few lines of JS (and no MixItUp):

```js
function filter(selector) {
  const show = [];
  const hide = [];

  targets.forEach(target => target.matches(selector) ? show.push(target) : hide.push(target));

  // You now have two arrays or targets to show and targets to hide for the provided filter.

  // Add in your custom code to add/remove the appropriate class names etc.
}
```

**Comment by mattpilott** [comment]
cool thanks i'll give it a whirl, it would be super useful if you could add a callback to do something inbetween start and end, as the animations would actually be preferable over what i have, but i cant have them and add my class as it is visually janky.

thanks

**Comment by juliendude** [comment]
In case someone search for this, you can simply add the following in your callback function.
`state.hide` and `state.show` are already arrays.

```
state.hide.forEach((item) => {
  item.classList.add("notFilteredItem");
});
```
or the opposite
```
state.show.forEach((item) => {
  item.classList.add("FilteredItem");
});
```
