### ISSUE TITLE
Cannot read property 'limit' of null (Pagination & Multifilter)

### ISSUE THREAD

**Issue by sophanox** [patrickkunka/mixitup#352]
Hi there,

I'm receiving the error below when attempting to any filtering. I have Pagination and Multifilter enabled. 

![image](https://user-images.githubusercontent.com/19409202/29164601-e2976da4-7db7-11e7-9088-be0e29451eb7.png)

Here's my config:

 ```
mixer = mixitup(container, {
      data: {
        uidKey: 'ID',
      },
             pagination: {
                    limit: 4,
                },
      animation: {
        queueLimit: 7,
      },
      multifilter: {
        enable: true, // enable the multifilter extension for the mixer
      },
      render: {
        target: (item) => {
     // render code
        },
      },
    });
    mixer.dataset(parsedTasks); //parsed tasks is an array of the data used
```

I have implemented it via select2 boxes. Whenever one is changed, it recreates the multifilter and applies it. This error only appears when pagination is enabled. Everything works as expected when it's not enabled.

Any ideas?

Thanks

**Comment by patrickkunka** [comment]
Hello @sophanox,

The first thing I notice is that you are using Multifilter, Pagination and the dataset API at the same time.

Unfortunately, the Multifilter and Pagination extensions are not compatible with the Dataset API.

When using the Dataset API, you would implement your own pagination and filtering logic either on your back-end (e.g. via a JSON API), or using custom JavaScript that prepares your dataset array before you send it to the .dataset() API method, as is done in our dataset demos.

If you want to use the Pagination and Multifilter extensions, you must use the standard DOM selector querying API methods. In this case, all target elements exist in the DOM before you instantiate MixItUp, or you can create them by using one of the .insert() API methods.

**Pagination and MultiFilter both operate on the DOM, whereas Dataset allows you to operate purely on the data model (with a side effect that the DOM will update).**

I'm assuming the error is resulting from attempting to use both the Dataset and DOM approach simultaneously. If you could decide on one approach, then I can hopefully help you more.

**Comment by sophanox** [comment]
Hey Patrick,

Rendering it to the DOM prior to instantiating MixItUp worked :)

Thanks a lot & thanks for the great library!

**Comment by patrickkunka** [comment]
Great, thanks!
