### ISSUE TITLE
Adding .mix destroy my layout

### ISSUE THREAD

**Issue by perffy** [patrickkunka/mixitup#353]
Hi guys,

i am trying to make a first example with mixitup, but for the moment i am experiencing some troubles.
By adding the .mix class to each element, I cannot see normal the layout. It is broken.
I have added the .mix{display: none;} to my css, but it does not help.

Here is my code:

```
<div class="col-md-3 col-sm-3 col-xs-6">
	<select class="form-control" id="select_name" name="name"><option value="" selected="selected">Name</option><option value="rating:asc">Ascending</option><option value="rating:desc">Descending</option></select>
</div>
<div class="toplist__content">
	<div class="toplist__row mix" data-rating="{{ $_brand->rating }}" data-name="{{ $_brand->name }}" data-rate="{{ $_brand->payout }}" data-bonus="{{ $bonus }}">
		<div class="toplist__col"></div>
		<div class="toplist__col">
			<div class="toplist__bonus">{{ $bonus }}</div>
		</div>
		<div class="toplist__col">
			<div class="toplist__payout"><span class="toplist__num">{{ $_brand->payout }}%</span>Win Rate</div>
		</div>
		<div class="toplist__col toplist__col--fourth">
			{{ $_brand->rating }}
		</div>
	</div>
</div>

<script>
    $(function(){
  var $sortSelect1 = $('#select_name'),
      $container = $('.toplist__content');
  
  $container.mixItUp();

  $sortSelect1.on('change', function(){
    $container.mixItUp('sort', this.value);
  });
});
  </script>
```

**Comment by patrickkunka** [comment]
Hello @perffy,

I'm afraid I don't have enough information about your project to tell what the problem might be. If you could provide a link to a staging site or jsfiddle reproduction that would great. However, I would recommend upgrading to MixItUp 3 if possible. With MixItUp 3, you no longer need the `{display: none}` rule, so adding MixItUp to your project should have no effect on your layout whatsoever.

The same `<select>` integration you are using is still possible via the `.sort()` API method.

You can find a migration guide here: https://www.kunkalabs.com/mixitup/migration-guide/

**Comment by perffy** [comment]
Hi @patrickkunka,

unfortunately i am not familiar with jsfiddle, how to use it. I can give you a live link to see:
http://www.casino-ranking.com/en/casinos

Thank you in advice !

**Comment by patrickkunka** [comment]
Hi @perffy,

Apologies for the delay.

I have taken a look at your site and I think I understand the problem.

I looks like your layout should have "full-width" rows for each of your casinos. The default layout mode of MixItUp 2 is "inline-block" which is more suited for grids. To enable a full-width layout, you'll want to override this with "block". You can do this via the configuration object:

```js
$container.mixItUp({
    layout: {
        display: 'block'
    }
});
```

As stated before, this only applies to MixItUp 2. If you upgrade to version 3, you control your layout via CSS only.

**Comment by perffy** [comment]
Hi @patrickkunka 

your solution with MixItUp 2, has worked, but not fully. The display was not as i wanted, so i switched to MixItUp 3, now it works fine, but i do not know how to use the four dropdown menus to sort the results. 
I could not find in your examples and in Google any example with <select> dropdown. Is it possible to change the sorting parameters using dropdown ?

Thanks !
