### ISSUE TITLE
Overriding selector-based results with additional arbitrary filter conditions

### ISSUE THREAD

**Issue by Kwapi** [patrickkunka/mixitup#357]
My container elements use multiple data-attributes as opposed to classes. Unfortunately, I wasn't able to set the text input data-search-attribute to look into multiple data-attributes. Is that possible?
Also, there's quite a few examples of MixItUp 2's search functionality where people specified the conditions for filtering (i.e. looking into titles or other attributes that are not otherwise used in the general filters). Ideally, I'd like to be able to have my search query be run on all specified data-attributes and also on text with the class 'title'.

Could you point me in the right direction? Is there an override mechanism that I could use to provide custom search functionality (I'd like to avoid using APIs and datasets if possible).

**Comment by patrickkunka** [comment]
Yes, you can bind any arbritary JavaScript code to a text input to produce an array of matching elements, which you can then send to the `.filter()` method.

Here's an example from the docs, which searches through all target elements and filters out anything that has a "price" attribute with a value less than or equal to 10.

```js
var collection = Array.from(container.querySelectorAll('.mix'));

console.log(collection.length); // 34

// Filter the collection manually using Array.prototype.filter

var filtered = collection.filter(function(target) {
   return parseInt(target.getAttribute('data-price')) > 10;
});

console.log(filtered.length); // 22

// Pass the filtered collection to MixItUp

mixer.filter(filtered)
   .then(function(state) {
       console.log(state.activeFilter.collection.length === 22); // true
   });
```

You could attach this code to the 'keyup' event of a text input, and search through any arbitrary attribute of each target element to see if it matches the value of your text input.

Unfortunately though, this won't work in combination with other MultiFilter UI, as that can only work using selector concatenation, and sending anything to the `.filter()` method will override the output of the MultiFilter UI. If you want to combine complex text-based filtering with other conditions, you'd be best to do it server side with a database query.

**Comment by Kwapi** [comment]
Thanks for that but is there really no way to manually filter the output o MultiFilter UI? The plugin is a great time-saver but the inability to modify anything after the filters are set seems very limiting

**Comment by patrickkunka** [comment]
Yeah - I can understand what you're saying. The ability to apply additional custom JavaScript "filters" to results more easily is something I'm considering adding.

There is actually a way to do this currently that I might have overlooked in my previous response, but it's not fully documented and (obviously) requires some custom JavaScript. It uses the `onParseFilterGroups` callback, which allows you to arbitrarily transform the mixitup "command" object produced by MultiFilter, before it is sent to the mixer.

```js
var mixer = mixitup(containerEl, {
    multifilter: {
        enable: true
    },
    callbacks: {
        onParseFilterGroups: function(command) {
            // Command is an object containing instructions about the operation.
            // In this case `command.filter.selector` contains the compound
            // selector string generated by multifilter:

            console.log(command.filter.selector); // e.g: '.green.large, '.blue.large'

            // At this point however, we don't want to filter by selector, we want to
            // filter by a reduced element collection.

            // Firstly, use the selector to obtain the equivalent collection of target elements:

            var fullCollection = Array.from(containerEl.querySelectorAll(command.filter.selector));

            // Then reduce the collection by some arbitrary condition (price attribute for example)

            var reducedCollection = fullCollection.filter(function(target) {
                return parseInt(target.getAttribute('data-price')) > 10;
            });

            // Finally, replace the command object to perform a collection-based filter:

            var newFilterCommand = new mixitup.CommandFilter();

            newFilterCommand.collection = reducedCollection;

            return {filter: newFilterCommand};
        }
    }
});
```

Have tried to comment fully, so I hope that all makes sense.

Cleaner ES6 version below if that's an option:

```js
const mixer = mixitup(containerEl, {
    multifilter: {
        enable: true
    },
    callbacks: {
        onParseFilterGroups: handleParseFilterGroups
    }
});

function handleParseFilterGroups({filter}) {
    const newFilterCommand = new mixitup.CommandFilter();
    const fullCollection = [...containerEl.querySelectorAll(filter.selector)];

    newFilterCommand.collection = fullCollection.filter(target => parseInt(target.getAttribute('data-price')) > 10);

    return {filter: newFilterCommand};
}
```

**Comment by mcmanimie** [comment]
Could this be used to conditionally add a filter?  Say, if I always want ".maroon" to be programmatically added when the current filters are ".unitA" and ".red" 

**Edit**: Yup.  Works great.

```js
if (command.filter.selector == ".unitA.red") {
    var combinedCollection = Array.from(containerEl.querySelectorAll(".unitA.red, .maroon"));
    var newFilterCommand = new mixitup.CommandFilter();
    newFilterCommand.collection = combinedCollection;
    return {filter: newFilterCommand};
}
```
