### ISSUE TITLE
Multiple Multifilter Instance / Bootstrap Tabs

### ISSUE THREAD

**Issue by ghost** [patrickkunka/mixitup#358]
Hey Patrick.

Really enjoying Mixitup.

I'm looking for away of using 2 different instances of Multifilter, 2 different set of controls, in two different bootstrap tabs.

I've tried your previous bootstrap tabs / multiple instances answers, but neither could work with Multifilter. I'm guessing it's because we can not use the standard .filter() API method with the extension.

I'm sure theirs something obvious i've missed by naming data-filter-group, but i'm really scratching my head with this one.

**Comment by patrickkunka** [comment]
Hi @spearquit,

As I'm not very familiar with Bootstrap tabs, could you include some example code? Also could you link to the other related github issue/answer that you referenced?

You are correct that the .filter() API cannot be used to control multi filter UI, so that may indeed be the issue.
