### ISSUE TITLE
Resolved: Safari: page crash and reload when library used in WordPress

### ISSUE THREAD

**Issue by s-a-s-k-i-a** [patrickkunka/mixitup#361]
**# FIXED!**
Website, where the issue occurs:
plantbasedkochschule.de

**Environment:**
Wordpress 4.8.2 in a self-hosted installation (not wordpress.com)
Parent Theme &amp;quot;Snaps&amp;quot; (the wpcom version, from wordpress.com theme repo, NOT the.org version!)
Filterable portfolio script: 
~~MixItUp 3~~ - latest script release from Patrick Kunka's Github
I thought maybe there is an incompatiblity with MixItUp 3 and the WordPress includes, so I instead tried out the latest:
**Isotope script** 
BUT, the very same issue happened also with Isotope in Safari.

**Custom coded:**
1 CPT "kochkurse" (which is queried here in front page in the filterable portfolio)
1 custom taxonomy &amp;quot;themen&amp;quot; (which only applies to kochkurse cpt)

**Overall Description:**
I added a nice filterable layout of queried posts to my site via self-written shortcode in front page, and archive customization for cpt archive kochkurse and custom taxonomy term archives (/themen/backen/ , /themen/kochen/ etc.):

plantbasedkochschule.de

It works fine on Desktop (opera, chrome, firefox on Mac OS Sierra)

**Bug/problem description:**
When I visit the site using (MacOS or iOS) Safari AND as soon as the user clicks through the filterable portfolio links (marked with pink arrows in screenshot), it either crashes the browser app in total or Safari returns an error message, reading that safari has encountered a problem on this site and thus reloads it. (not very helpful)
This message gets returned on IOS Safari only. MacOS Safari causes a memory issue I believe, because it kind of freezes for a moment, then loads the filter content.

This problem was not present before I implemented MixItUp 3 (by Patrick Kunka) and it also does not occur until user clicks through the filter links while in Safari.

**Explanation regarding the filterable portfolio setup:**
each post of CPT kochkurse contains an ACF repeater field which offers the possiblity to optionally add one or more occurance dates to the cpt. I wrote a shortcode with a custom query and a foreach loop that checks if the cpt has filled out date fields and if so, then it checks if one of these dates are NOW or in future (this week, next week, this month, next month). If any of the conditions are met for one or more dates, those dates will be put in a variable and output per queried post (within the overlay that appears, when you hover each post within the portfolio layout). 

The filter links allow to filter by those given dates. 
Translation of filter links: 
Alle (all). Diese Woche (this week), Nächste Woche (next week), Diesen Monat (this month), Nächsten Monat (next month)

At this point of time, there are no cooking classes that take place before Nov. 15th. Thus there is no date that matches given filter criteria.

**Screencast:**
[http://youtu.be/ZW649eRkrOo?hd=1](http://youtu.be/ZW649eRkrOo?hd=1)

**Question:**
Do you happen to be able to fix the reason for crashing in Safari, when using the library with WordPress?

**# Answer:**
After investigating the issue on an iMac 27'' 5k from Nov 2016, as well as on my old Macbook Pro from 2009, the iPad Pro, and my iPhone 7, I concluded that there is no relation to Retina display or non-Retina.
Also was I sure, that this issue occurs on any Safari browser.
Finally I was able to find the reason for those massive memory leaks, cause Safari to crash, when a filter link was clicked (with MixItUp 3 as well as latest Isotope script )!
**CSS3 transitions were the culprit.** 
Somehow Safari seems to be unable to properly cope with transitions.
So I did the following:

1. I modified my php code once more and declared a wordpress core built-in global variable called `$is_safari `. 

```
	global $is_safari;
	$noTransitions = "";
	if ( $is_safari ) {
	    // This is desktop & mobile safari browser
	    $noTransitions = " no-transition";
	}
```
After that I simply added this variable to my output string, so the variable's content would serve as a css class:
`echo '<ul id="mixitupcontainer" class="container'.$noTransitions.'">';`

and then I added a little bit of CSS to my theme's style.css:

```
/* disabling Isotope CSS3 transitions */
 
#mixitupcontainer.no-transition,
#mixitupcontainer.no-transition .mix {
  -webkit-transition-duration: 0s !important;
     -moz-transition-duration: 0s !important;
      -ms-transition-duration: 0s !important;
       -o-transition-duration: 0s !important;
          transition-duration: 0s !important;
}
```

That was it. Problem solved.

**Comment by patrickkunka** [comment]
Hello,

The first thing I noticed on desktop Chrome is that your filtering does not work becuase you have styled your target elements as "display: none, opacity: 0". This is not necessary in MixItUp 3, and you should remove these rules from your CSS.

Also you don't need to add the "all" class to your target elements, if you filter my "all", all items are automatically included. Currently, your target elements are missing any kind of category class to enable filtering by the other categories in your menu (they only have "mix" and "all"), so you should add the appropriate classes to each one if you want the menu to work.

Regarding the iOS safari issue, this doesn't sound like it is related to MixItUp. I would suggest removing MixItUp from the page and seeing if the issue still happens. What is the exact error message that you are seeing and what script is coming from?

**Comment by s-a-s-k-i-a** [comment]
Hello Patrick,

thanks so much for your reply.

In the meantime (since I wrote above post) I started rewriting the code, because I noticed that MixItUp is in version 3 now and I had it set up with something like v. 1.5.x
In that set up the html and css worked fine.

But no longer in MixItUp 3.. just as you described. I am in this very moment adjusting the html output of my php code and trying to get it to work 👍 

Also your script no longer depends on jquery, so I had to change the way it gets loaded in comparison to the v. 1.5.x I used before

Thanks again, I should have updated the post above, sorry for that and thanks for taking the time to look at the site


regarding the missing categories comment:
well thats intended :D 
my php code which generates the category classes, checks if the posts loaded in the loop query, contain specific fields filled with start and end dates which are now or in future. And depending on these dates the category filters get applied as class names.
the filters say: Alle (all), Diese Woche (this week), Nächste Woche (next week), Diesen Monat (this month), Nächsten Monat ( next month)

Since there are simply no posts with course starting dates matching the conditions for any of above categories, we only have all or nothing at this current date of today

Best
Saskia

**Comment by patrickkunka** [comment]
No problem - if everything is ok then, may I close this issue?

**Comment by s-a-s-k-i-a** [comment]
Its all set now and seems to work fine. however I am still seeing the weird browser error on ipad.. maybe it is my ipad only?
I cant reproduce this on desktop :(
unfortunately the error message on iOS Safari is not really helpful. It simply reads, that Safari has encountered a problem on this website and thus reloads the current page. (translated from German)

Ok.. I guess I will hook the iPad up on the Desktop Mac to bug fix it.. must be something, because the page wasnt crashing before I added MixItUp script. And it is only then crashing, when the user clicks through the filter controls.

**Comment by s-a-s-k-i-a** [comment]
I found someone else who is having this kind of problem on an ipad using isotope script on his site: https://www.codersclan.net/ticket/24

will check out what they did to solve it

EDIT: seems to be related to CSS3 transitions / I changed issue title and description as I investigated this more

**Comment by s-a-s-k-i-a** [comment]
I thought, ok maybe this is some incompatibility with the mixitup library. So I remodelled the code and integrated isotope instead.
But guess what: very same issue on safari.

So yes, I think it is not the scipt itself, but something else that crashes safari somehow. Or leaks memory.

Does anyone have an idea what that might be?

**Comment by s-a-s-k-i-a** [comment]
@patrickkunka 
I solved this issue and updated my issue post accordingly.
