### ISSUE TITLE
[MultiFilter] Button for filtering and sorting at the same time

### ISSUE THREAD

**Issue by Kwapi** [patrickkunka/mixitup#363]
I'd like to have a button act both as a filter and a sort trigger (i.e. upcoming and past events). I managed to get the functionality working by using a button like this:
`<button type="button" data-sort="filter--date" value="[data-filter--era~='future']">`

Unfortunately, instead of one action, Mixitup first performs the sorting and afterwards the filtering which looks odd. Is there a way to force the calculations to be performed simultaneously and only after they're done the view would update? If that's not possible maybe there's a way to force the filtering to be done first? That way the update would be less jarring.

**Comment by patrickkunka** [comment]
Hi,

"Multimix" buttons are supported in v3. You simply need to add both a `data-sort` and a `data-filter` attribute to the same button. For example:

```html
<button type="button" data-sort="date:asc" data-filter="all">All</button>
```

This is the equivalent of the following `multimix()` API call:

```js
mixer.multimix({
    filter: 'all',
    sort: 'date:asc'
});
```

**Comment by Kwapi** [comment]
Hi,
Thanks for your help but your solution doesn't seem to work for me.

If I set the filtering to be done via the `data-filter` attribute it overrides the sorting ability.

i.e:
`<button type="button" id="radio-forthcoming" data-sort="filter--date:dsc" data-filter='[data-filter--era~="future"]'></button>` 
does only filtering (the ActiveSort attribute in the mixer is not set)


Calling the `multimix()` API using the same values works, though :
```
mixer.multimix({
    filter: '[data-filter--era~="future"]',
    sort: 'filter--date:dsc'
});
```

Do you know what I'm doing wrong?

On the side-note: When I tried swapping the `<button>` for `<input type="radio">` the result is the same but there's also another weird call to the mixitup with the selector `on` which means mixitup performs two sets of filtering and the `on` filtering effectively gets rid of any results.

**Comment by Kwapi** [comment]
Hi again,

I found the solution to my problem. Because I'm using MultiFilter on the same page i still had that button nested under a div with `data-filter-group` which I imagine led to conflicts. Moving the button outside of that div solved it.

Cheers!

**Comment by patrickkunka** [comment]
Hi - yes sorry about that I just realised you were using MultiFilter. MultiFilter controls work a little bit differently to normal MixItUp controls (they aren't 2-way bound, and can only be used for filtering). There are ways you can plug in your own custom functionality before the MultiFilter command is sent to your mixer, but it sounds like you've found a solution. Let me know if you need any more help.
