### ISSUE TITLE
.toggleOff() for a non-active filter removes all current filters

### ISSUE THREAD

**Issue by peter-lyons-kehl** [patrickkunka/mixitup#368]
Hi Patrick,

When I run .toggleOff() for a non-active filter, it seems to remove all current filters. Please change it to ignore the parameter & not to remove any current filters.

Context from a real life scenario: Custom handling of `<select multiple="multiple">`. change handler in jQuery only works on `<select>`, not on its `<option>` children. jQuery event object doesn't indicate which option was un/selected. The obvious way is
1. iterate over `$('option:selected')` tags, use the result for a subfilter `.toggleOn()` - that works
2. iterate over `$('option:not(:selected'))` tags, use the result for a subfilter to `.toggleOff()` - if there are any options that were unselected before the change and are still unselected, then this upsets toggleOff().

A workaround is to generate a full filter string, then use `mixitUpInstance.filter(myConcatenatedFilter)`. But that's more error-prone and less obvious to users.

**Comment by patrickkunka** [comment]
Fixed in https://github.com/patrickkunka/mixitup/releases/tag/v3.2.2
