### ISSUE TITLE
'Show All' option for pagination

### ISSUE THREAD

**Issue by Kwapi** [patrickkunka/mixitup#374]
Is there a way to show all items using the Pagination add-on?

Something akin to `mixer.paginate('all')`?

At the moment I count the maximum number of items and store that value as one of the select options under 'all' which works fine but i was wondering if there's a cleaner approach.

Cheers!

**Comment by patrickkunka** [comment]
Have you tried setting a limit of `Infinity`?

```js
mixer.paginate({limit: Infinity});
```

**Comment by Kwapi** [comment]
Works like a charm, thanks!
