### ISSUE TITLE
data-filter-group add class active with chash

### ISSUE THREAD

**Issue by in-session** [patrickkunka/mixitup#375]
Hi,

first many thanks for the great work.

I have a small question, I have multiple filters whiche works with chash.

The structure is like in your example:

```
<div>
    <form data-filter-group>
       ...
       <button type="reset">Clear filters</button>
    </form>

    <form data-filter-group>
       ...
       <button type="reset">Clear filters</button>
    </form>
</div>
```

But now I need a active class on the current data-filter-group form when a filter is set.
The idear ist to show the reset button first once a filter is set.

Hope you can help me?

Best Regrads Chris

**Comment by patrickkunka** [comment]
Hi Chris,

This functionality isn't built into MixItUp, but you could write some custom JavaScript to query the active filters using a callback function.

Firstly, name your filter groups, so you can query them in via the mixer's API.
```html
<div>
    <form data-filter-group="color">
       ...
       <button type="reset">Clear filters</button>
    </form>

    <form data-filter-group="shape">
       ...
       <button type="reset">Clear filters</button>
    </form>
</div>
```

Then, instantiate mixitup, and specify a custom callback function (`handleMixEnd`).
```js
var mixer = mixitup(container, {
    multifilter: {
        enable: true
    },
    callbacks: {
        onMixEnd: handleMixEnd
    }
});
```

Now create your handler functionality:

```js
// obtain a reference to your groups container element:
var colorGroupContainer = document.querySelector('[data-filter-group="color"]');

function handleMixEnd() {
    // get a list of all filters active for the group
    var activeColorFilters = mixer.getFilterGroupSelectors('color'); // e.g: ['.red', '.blue']

   if (activeColorFilters.length > 0) {
       // If filters are active for the color group, add a styling class

       colorGroupContainer.classList.add('filter-group-active');
   } else {
       // else, remove it

       colorGroupContainer.classList.remove('filter-group-active');
   }
}
```

This works for one group, but you could easily modify or genericise the code to make it work for multiple groups.

Hope that helps,
Patrick

**Comment by in-session** [comment]
Hi Patrick,

great thats helps me, thanks a lot.
Can you tell me also howto add the handleMixEnd if already setHash defined :-)

```
 	callbacks: {
 		onMixEnd: setHash
 	}
```

Additional it would be great to see inside the demo examples a single button for sorting.

As example for sort by title:

```
<button class="toggle-sort" data-mixitup="control" data-sort="title:">Title <i>arrow up and down</i></button>
If data-sort="title:" if emty (<i>arrow up und down</i>)
If data-sort="title:asc" (<i>arrow up</i>)
If data-sort="title:desc" (<i>arrow down</i>)
```

Have a great day,

Cheers Chris

**Comment by patrickkunka** [comment]
Hi Chris,

You could call both your handler functions together like this:

```js
var mixer = mixitup(container, {
    ...,
    callbacks: {
        onMixEnd: function(state) {
            handleMixEnd(state);
            setHash(state);
        }
    }
});
```

As far as having a single button for sorting that cycles through different sorting orders on each click, you would have to create a custom button of your own, and write your own click handler to sort via the API.

Something like this could work.

- Create an array with all possible sorting orders in it (the example below has 2, but you could add as many as you like).
- The first time you click, it will sort by the first item in the array, and then the 2nd, and then 3rd etc. 
- When it reaches the end of the array, it will go back to the start again.

```js
var sortingOrders = ['title:asc', 'title:desc'];
var currentSortingOrderIndex = 0;

handleSortButtonClick() {
    var order = sortingOrders[currentSortingOrderIndex];

    mixer.sort(order);

    if (currentSortingOrderIndex < sortingOrders.length - 1) {
        currentSortingOrderIndex++;
    } else {
        currentSortingOrderIndex = 0;
    }
}
```

**Comment by in-session** [comment]
Hi Patrick,

many thanks, the callbacks works fine.

Programming is a book with 7 seals for me, therefore the handleSortButtonClick is too much for me.
But you still helped me a lot, again.

I wish you a great day.

Cheers Chris
