### ISSUE TITLE
displayed items from browser .

### ISSUE THREAD

**Issue by medabkari** [patrickkunka/mixitup#376]
Hi Patrickkunka ,

I tried to Work with MixitUp Plugin Version 3 but Unfortunately i didn't find The Solution Of many Small problems Like The Console Problems , After I tried to Work With The Version 2 and again i was falling in problems until now which is : when i do for the Mix display:none; , my Latest Section which is the Contact form Disappears from the Browser and i didn't find any Solutions for That , So I Hope you Help Me Out of this small Problem . Thanks For Respond Me .

**Comment by patrickkunka** [comment]
Hello,

Please include a link to your project or a reproduction of the issue on jsfiddle or codepen.

Please explain what your problem is in terms of the expected behaviour vs the resulting behaviour.

Also there is a migration guide from V2 to V3 here which you may find helpful. Display: none is no longer required on your targets in V3.

https://www.kunkalabs.com/mixitup/migration-guide/

**Comment by medabkari** [comment]
Hello , 

I Tried to work with V3 But i Faced A problem Which is the Console don't work Or any plugin of function after the mixitUp plugin in My file Js .

**Comment by patrickkunka** [comment]
Could you include any console errors that you are seeing?

**Comment by patreck-developer** [comment]
Hello, 
Sorry To Disturb You ,

When I Work With The V2 The Console Work But My Latest Section in the Browser Disappears until i get focus on it by Clicking th

**Comment by medabkari** [comment]
Hi ,
Sorry To Disturb you , 

When I Work with The V2 , The Console Work But My Last Section in the Html Domcument which is Contact Form Disappears in The Preview untill I Get focus on it by Clicking her link in the navbar .

This is link of the Preview Screen of what Happened : (https://imgur.com/3q9vDqH) .

This Is link of the preview when i get focus on it : (https://imgur.com/tfcCcjZ) .

**Comment by medabkari** [comment]
That's how i worked with it : https://codepen.io/abcari/pen/MOYdGZ
