### ISSUE TITLE
[MultiFilter/Pagination] Filtering by hash with pagination and filter group data in URL

### ISSUE THREAD

**Issue by in-session** [patrickkunka/mixitup#377]
Hi Patrick,

hello again :-)

after buying the pagination plug, I don't find a solution to add the pagination also on multifilter hash.
After reload or back button on mobile they will lose the current page and springst to page 1.

Do you have any idea?

Cheers Chris

**Comment by patrickkunka** [comment]
Hi,

If you are basing your hash integration off the one included in the MultiFilter extension, you can extend that with pagination data.

I'm afraid its a pretty complicated change, but you'll need to make all of the following edits:

```js
// Add this variable

var newPage = 1;

// Update the following three functions as below (change the filter group names as appropriate):

function getGroupsState() {
    var groupsState = {
        color: mixer.getFilterGroupSelectors('color').map(getValueFromSelector),
        shape: mixer.getFilterGroupSelectors('shape').map(getValueFromSelector),
        size: mixer.getFilterGroupSelectors('size').map(getValueFromSelector),
        page: [mixer.getState().activePagination.page] // NB: page now added
    };

    return groupsState;
}

function filterMixerByGroupsState(groupsState, animate) {
    var color = (groupsState && groupsState.color) ? groupsState.color : [];
    var size = (groupsState && groupsState.size) ? groupsState.size : [];
    var shape = (groupsState && groupsState.shape) ? groupsState.shape : [];
    var page = (groupsState && groupsState.page) ? groupsState.page[0] : 1;

    mixer.setFilterGroupSelectors('color', color.map(getSelectorFromValue));
    mixer.setFilterGroupSelectors('size', size.map(getSelectorFromValue));
    mixer.setFilterGroupSelectors('shape', shape.map(getSelectorFromValue));

    newPage = page;  // NB: newPage variable sent on load and hash change via handleParseFilterGroups

    return mixer.parseFilterGroups(animate ? true : false);
}

function setHash(state) {
    var selector = state.activeFilter.selector;
    var page     = state.activePagination.page;

    var groupsState = getGroupsState();

    var newHash = '#' + serializeGroupsState(groupsState);

    if (selector === targetSelector && window.location.hash && page === 1) { // check if on page 1
        activeHash = '';

        history.pushState(null, document.title, window.location.pathname);
    } else if (newHash !== window.location.hash && (selector !== targetSelector || page !== 1)) { // if not page 1
        activeHash = newHash;

        history.pushState(null, document.title, window.location.pathname + newHash);
    }
}

// Add the following callback function:

function handleParseFilterGroups(command) {
    var newPaginateCommand = new mixitup.CommandPaginate();
    
    newPaginateCommand.page = newPage;

    return {
        filter: command.filter,
        paginate: newPaginateCommand
    };
}

// Add this new callback to the configuration object

var mixer = mixitup(containerEl, {
    ...,
    callbacks: {
        ...,
        onParseFilterGroups: handleParseFilterGroups
    }
});
```

I have not tested the above, but it should work (remember to carry over any changes you have already made). I will keep this open to remind me to add a new multifilter-compatible demo to the pagination extension.

**Comment by in-session** [comment]
Good Morning Patrick,

I test your script and I get an error:
```
mixitup.js:525 Uncaught TypeError: Cannot add property filter, object is not extensible
at Object.extend (mixitup.js:525)
at mixitup.Mixer.parseFilterArgs (mixitup.js:7204)
at mixitup.Mixer.parseMultimixArgs (mixitup.js:7149)
at mixitup.Mixer.multimix (mixitup.js:8395)
at mixitup.Mixer.parseFilterGroups (mixitup-multifilter.js:1010)
at mixitup.FilterGroup.handleClick (mixitup-multifilter.js:415)
at HTMLFieldSetElement.self.handler (mixitup-multifilter.js:335) 
```

I believe I have no additional changes in the default script active.

Cheers Chris

**Comment by in-session** [comment]
Update - I test your changes also with the original example "programmatic-filtering-by-url", I get the same error.

**Comment by patrickkunka** [comment]
Apologies, I think the error is in the `handleParseFilterGroups` function I gave you. See corrected version below (original answer updated too). Let me know if this works.

```js
function handleParseFilterGroups(command) {
    var newPaginateCommand = new mixitup.CommandPaginate();
    
    newPaginateCommand.page = newPage;

    return {
        filter: command.filter,
        paginate: newPaginateCommand
    };
}
```

**Comment by in-session** [comment]
No problem, I'm grateful for any help. With your changes no error anymore :-) 

But I have to insert the pagination specifically with fieldset or so? Because the pages are not in the hash:
(page 2) 
index_copy.html#color=blue&shape=triangle

**Comment by patrickkunka** [comment]
Ah, I think I spotted the issue. Have updated the original answer again with some changes to `getGroupsState()` and `filterMixerByGroupsState()`.

Essentially,`groupsState.page` should have been an array to match the others properties and serialise/deserialise correctly.

Unfortunately I still haven't had a chance to test this out locally, but if that still doesn't work, please send me a link to your project and that will help.

**Comment by in-session** [comment]
Perfect now it works correctly 🥇 

Many thanks for you help

**Comment by in-session** [comment]
Small other think in this case.
How to remove the hash after sorting (not filtering). Because  after sorting decs/asc you need to go back on page 1.

**Comment by patrickkunka** [comment]
Hi - apologies for the delay, this wasn't quite as simple a problem to solve as I originally thought. I've now added a new demo of the above functionality to the latest MultiFilter version (v3.3.1) which you can download from your account.
