### ISSUE TITLE
Problem Items Disappears .

### ISSUE THREAD

**Issue by medabkari** [patrickkunka/mixitup#378]
Hi,
Sorry To Disturb you,

When I Work with The V2, The Console Work But My Last Section in the Html Document which is Contact Form Disappears in The Preview until I focus on it by clicking the link in the navbar.

This is the link to the Preview Screen of what Happened : (https://imgur.com/3q9vDqH) .

This Is a link to the preview when I focus on it : (https://imgur.com/tfcCcjZ) .

**Comment by medabkari** [comment]
That's how i worked with it : https://codepen.io/abcari/pen/MOYdGZ

**Comment by patrickkunka** [comment]
No problem. Unfortunately, I don't think that this has anything to do with MixItUp. I would need to see a real link to your project to confirm.

**Comment by medabkari** [comment]
okéy i'll code it in CodePen And Put It Here For you To See , and I Hope you help Me Out Of this , really I Need To Work with It .

**Comment by medabkari** [comment]
Hello , 

Sorry , i feel So Shy of you friend For This pro oPrblem , But really I need your help For This Plugin .

here is the Preview Of the template which has the problem : http://chairman-helen-16074.bitballoon.com/ .

So friend here in the preview when you get into it try to reach the contact us section which is the last section , if it appears try to press on arrow up or down or refresh the page and you'll see the problem that the last section can't display .

and here the code on codepen : (https://codepen.io/abcari/pen/QOjbBa) .

i put the code on codepen but the whole template is working on bitbaloon so try to get look , and please help me out . Thank You Very Much .

**Comment by in-session** [comment]
Hi, i'm not sure but based on V3 you need to add the class "controls" on your ul list.

Basic:


```
        <div class="controls">
            <button type="button" class="control" data-filter="all">All</button>
            <button type="button" class="control" data-filter=".green">Green</button>
            <button type="button" class="control" data-filter=".blue">Blue</button>
            <button type="button" class="control" data-filter=".pink">Pink</button>
            <button type="button" class="control" data-filter="none">None</button>

            <button type="button" class="control" data-sort="default:asc">Asc</button>
            <button type="button" class="control" data-sort="default:desc">Desc</button>
        </div>

        <div class="container">
            <div class="mix green"></div>
            <div class="mix green"></div>
            <div class="mix blue"></div>
            <div class="mix pink"></div>
            <div class="mix green"></div>
            <div class="mix blue"></div>
            <div class="mix pink"></div>
            <div class="mix blue"></div>

            <div class="gap"></div>
            <div class="gap"></div>
            <div class="gap"></div>
        </div>
```
And you can find here some selectors configurations: https://www.kunkalabs.com/mixitup/docs/configuration-object/ 

Cheers Chris

**Comment by medabkari** [comment]
Thanks for Your help Chris ,

I tried To Work With V3 but i Face A problem which is My Console didn't work anymore .

**Comment by in-session** [comment]
You can test:

V3
```
var mixer = mixitup('#mixit', {
    selectors: {
        target: '.mix',
	control: '.filter'
    }
});
```

V2
```
$('#mixit').mixItUp({
    selectors: {
        target: '.mix',
	control: '.filter'
    }
});

```

**Comment by patrickkunka** [comment]
Thanks for your help @in-session.

Hi @patreck-developer, thanks for the additional links.

I've looked at your template, but it appears to be working fine for me. I can't reproduce any sort of problem where the contact form disappears like in your screenshot.

Can you give me some steps to follow to reproduce the bug?

**Comment by medabkari** [comment]
hello , 

try the enter to the Preview i sent it to you and try to scroll down to contact form , and after try to refresh the page one time and if the contact form stays try to click on the array up or down and the contact form will disappears .

**Comment by medabkari** [comment]
thank @in-session  for your help but i tried to do it in js file but the problem still happening .

**Comment by in-session** [comment]
@patreck-developer I belive this is a problem of jquery.nicescroll.min.js, nicescroll cuts the last section

**Comment by patrickkunka** [comment]
Hello, I managed to recreate the issue. It is not caused by MixItUp, but by a jQuery scrolling plugin that is on your page.

**Comment by medabkari** [comment]
hello , Thank you Very Much For Your Help , Really I didn't Realize That , But I'm Really Sorry for Disturbing you . Thanks you Very Much And Sorry Again .
