### ISSUE TITLE
Pageination have to adjust

### ISSUE THREAD

**Issue by in-session** [patrickkunka/mixitup#382]
Better solution for pagination on mobile, because if are both truncation-marker visible one button is to much.

```
	pagination: {
		maxPagers: 5
 	},
```

![ashampoo_snap_2017 11 01_18h51m33s_001_](https://user-images.githubusercontent.com/16542619/32289101-226b4e2c-bf36-11e7-9ba9-9834f51a1a92.png)
![ashampoo_snap_2017 11 01_18h51m50s_002_](https://user-images.githubusercontent.com/16542619/32289102-228d5b5c-bf36-11e7-90ea-73a40bc83020.png)

**Comment by patrickkunka** [comment]
Unfortunately the minimum allowed value for `maxPagers` is 5, which ensures that the first, last and 2 padding pages are always available.

If you're struggling for horizontal space, I would suggest solving the issue with CSS.

You could reduce the size of the UI, hide the truncation markers, or hide everything apart form the prev/next buttons.

Alternatively, you can disable/hide the default controls completely, and build your own UI which interacts with mixitup via its API.
