### ISSUE TITLE
[MultiFilter] Reset button when using `parseOn: 'submit'`

### ISSUE THREAD

**Issue by heychris** [patrickkunka/mixitup#383]
Hello,

I am trying to get the MultiFilter to work with the reset button and the submit button (```'parseOn': 'submit'```), without much luck. Whenever I try to reset a filtered state the reset button will clear the control's state and classes however the actual items will remain unaffected. Clicking the submit button after the partial reset will correct the issue, but that route isn't ideal.

Any thoughts?
[Demo replicating the issue](http://staging.mvpdesign.com/mixitup-demo/)

**Comment by patrickkunka** [comment]
That is actually the expected behavior, although I can see that it is not intuitive. You can do the following to force an immediate reset when clicking on the reset button:

```js
var resetButton = document.querySelector('button[type="reset"]');

resetButton.addEventListener('click', function() {
    setTimeout(() => mixer.parseFilterGroups());
});
```
