### ISSUE TITLE
Toggle sort button

### ISSUE THREAD

**Issue by nolybom** [patrickkunka/mixitup#384]
Is it possible to combine data-toggle & data-sort?

**Comment by patrickkunka** [comment]
Unfortunately not.

I'm not sure how this would work? Remember that multiple toggles can be active simultaneously and their selectors are concatenated together to form your final filter (e.g. `'.category-1, .category-2'`). If each button had a sort command as well, the sort commands would have to be combined together as well, which isn't really possible, and definitely not intuitive.

If you need some specific kind of hybrid control button that does more than one thing, there's always the `.multimix()` API method which allows you to do multiple operations at once. You can create your own UI and bind it to multimix on click.

Hope that helps.

**Comment by nolybom** [comment]
Thank you.
In my specific case an desc-sorting doesn't really make sense so i am trying to just toggle the sort button. Somehow like you did on codepen:

https://codepen.io/patrickkunka/pen/wKWYrP

```js 
$(function(){
  var sortOrder = 'asc',
      $container = $('#Container'),
      $toggleSort = $('.toggle-sort');

  $container.mixItUp();

  $toggleSort.on('click', function() {
    switch (sortOrder) {
      case 'asc':
        sortOrder = 'desc';
        break;
      case 'desc':
        sortOrder = 'asc';
        break;
    }
    $container.mixItUp('sort', 'myorder:' + sortOrder);
  });
});
```

How about binding reset to the case 'asc' ? Would you please post a example code on how to achieve that? I think more people might be interested in stripping the UI and implement just one sorting button.

**Comment by patrickkunka** [comment]
Ah ok, I think I misunderstood what you're asking for.

The above code is still valid for MixItUp 3. Without jQuery and with the MixItUp 3 API, it would look like the following:

```js
var sortToggle = document.querySelector('.toggle-sort');
var mixer = mixitup('#Container');
var sortOrder = 'default:asc'; 

sortToggle.addEventListener('click', function() {
    switch(sortOrder) {
        case 'default:asc':
            sortOrder = 'default:desc';

            break;
        case 'default:desc':
            sortOrder = 'default:asc';

            break;
    }

    mixer.sort(sortOrder);
});
```

I've simplified it slightly so that sorting is based purely on the "default" order, and no custom sorting attributes are required.

Does that help?

**Comment by patrickkunka** [comment]
I was just looking at your other issue, and it seems you are using MixItUp MultiFilter. If you wanted to extend the above example so that you are also binding the MultiFilter reset button to a reset of the sorting order, you could do the following:

```js
var sortToggle = document.querySelector('.toggle-sort');
var resetButton = document.querySelector('button[type="reset"]');
var sortOrder = 'default:asc';
var isResetting = false;

var mixer = mixitup('#Container', {
    callbacks: {
        onParseFilterGroups: function(command) {
            if (isResetting) {
                command.sort = sortOrder = 'default:asc';

                isResetting = false;
            }

            return command;
        }
    }
});

var isResetting = false;

resetButton.addEventListener('click', function() {
    isResetting = true;
});

sortToggle.addEventListener('click', function() {
    switch(sortOrder) {
        case 'default:asc':
            sortOrder = 'default:desc';

            break;
        case 'default:desc':
            sortOrder = 'default:asc';

            break;
    }

    mixer.sort(sortOrder);
});
```

**Comment by nolybom** [comment]
Your assistance is very appreciated. Thank you very much.

Unfortunately the sorting is not persistent when toggling. It toggles the sorting for a moment to desc and then back to asc.

In my markup i had to rename my 'data-sort' attribute to 'data-final' and while debugging i recognised that when toggling the attribute data-sort="final:asc" doesn't change its state.
And yes i have changed of course 'default:asc' (etc.) to 'final:asc'.

--

Is there a way to not toggle between asc and desc but just toggle between asc and the original order when loaded?

This is because i have a list of items which are injected into the dom by another rule then the data-sorts logic (desc &asc). I would rather have the sorting button just toggle between asc and the original state when loaded. This is also because there are featured items which need to be listed first (as they are when loaded).

**Comment by nolybom** [comment]
Is there a way to not toggle between asc and desc but just toggle between asc and the original order when loaded?

This is because i have a list of items which are injected into the dom by another rule then the data-sorts logic (desc &asc). I would rather have the sorting button just toggle between asc and the original state when loaded. This is also because there are featured items which need to be listed first (as they are when loaded).

**Comment by patrickkunka** [comment]
`default:asc` is the original order, but once you insert new targets in the DOM, the original order is lost and overwritten. If you want to maintain a consistent order, don't sort by `default`, but add sorting attributes to your target elements (e.g. `<div class="mix" data-data-created="20171103">...</div>`), and always sort while inserting to ensure order is predictable (by using `.multimix()`).

E.g. 

```js
mixer.multimix({
    insert: [newEl1, newEl2, newEl3], // insert 3 new targets
    sort: 'date-created:asc' // ensure targets are pre-sorted on insertion
});
```
