### ISSUE TITLE
Show results of ${totalTargets} in a new div

### ISSUE THREAD

**Issue by in-session** [patrickkunka/mixitup#389]
Hi Patrick,

small question can you help me to add the ${totalTargets} to a new separate div.
So that the user get the QTY of the current targets, like the pagination but only with totalTargets.

Cheers Chris

**Comment by patrickkunka** [comment]
Best thing would be to create your div in the desired location, and get a reference to it. Then update its content via some custom javascript that is bound to a MixItUp callback:

```html
<div class="total-counter"></div>
```

```js
var totalCounter = document.querySelector('.total-counter');

function updateTotalCounter(state) {
    totalCounter.innerHTML = state.totalTargets; // or state.totalMatching?
}

var mixer = mixitup(container, {
    ...,
    callbacks: {
        onMixEnd: function(state) {
            updateTotalCounter(state);
        }    
    } 
});

// Also update it when you first create the mixer

var initialState = mixer.getState();

updateTotalCounter(initialState);
```
