### ISSUE TITLE
reset mixitup multifilter -> bootstrap-select 

### ISSUE THREAD

**Issue by nolybom** [patrickkunka/mixitup#391]
I am using bootstrap select in my UI and the reset button doesn't reset the filter.

Using a bazooka workaround:

`
var resetBtn = document.getElementById('resetFilter');
resetBtn.addEventListener('click', function() {
  mixer.forceRender();
});
`

I don't think this is the only meaningful way to do it. Everyone agrees? ;)

**Comment by patrickkunka** [comment]
I'm not quite sure what your issue is. Could you post a link?
