### ISSUE TITLE
Remove impossible inputs in multifilter after filtering

### ISSUE THREAD

**Issue by jklue** [patrickkunka/mixitup#393]
Is there a way to remove impossible inputs from data-filter-groups after each filter change?

In the screenflick below I select "Featured Projects" > "Arts Organizations" > "Tribal College." There are no results that match all three of those data filter groups, so I will show a "no results" message. Would there be a way to dynamically remove the "Tribal College" checkbox input if we know there are no results to show once we already have "Featured Projects" and "Arts Organizations" selected? This would give the user better visibility on what options are still available.

![remove-impossible-inputs](https://user-images.githubusercontent.com/5399943/33081828-3e6d5a48-cea9-11e7-8295-a66badb2ee76.gif)

**Comment by patrickkunka** [comment]
Hi Luke,

Great looking site! This would have be done via custom JavaScript on your side.

The best way to do this would be to add a custom callback function to `callbacks.onMixEnd`, which will provide you with the current state object, which contains a `show` property which is an array of all visible elements matching the current selection.

For each checkbox in your menu, you'll need to find out if its selector exists at least once in any of the visible targets. You'd do this by iterating through everything in `state.show` and calling `.matches(selector)` on it. If any of them match, you can immediately break and assume that the checkbox will yield further results.

If it doesn't, you can disable/grey out or hide the checkbox.

Its not particularly efficient, but this is the best way I can think of with a DOM-based approach. Let me know if you need any further guidance.

**Comment by jklue** [comment]
Thank you for the guidance--the show property makes it a lot easier to tackle! I'll let you know when the site goes live :)
