### ISSUE TITLE
Issues loading MixItUp extensions using ES6 modules and Webpack

### ISSUE THREAD

**Issue by jimblue** [patrickkunka/mixitup#394]
Hello,

I'm following the documentation to call the plugin programmatically:

```js
import mixitup from 'mixitup'
import mixitupPagination from '../mixitup-pagination'
mixitup.use(mixitupPagination)
```

But I always get this error in the console:

` Uncaught Error: [MixItUp Pagination] MixItUp core not found`

This is not happening when using Mixitup alone.

**Comment by patrickkunka** [comment]
You should only see this error if you include the extension via a `<script>` tag in your document. If you are building a modular project, you should not have any libraries being loaded via <script> tags.

What module bundling system (e.g. webpack) are you using?

**Comment by jimblue** [comment]
Yes I'm using webpack... I'm not using script tag to import it

**Comment by patrickkunka** [comment]
Thanks - do you know which version of webpack you're using? I'll try to see if I can reproduce the error.

**Comment by jimblue** [comment]
webpack: "^3.8"

**Comment by jimblue** [comment]
Have you been able to reproduce it?

**Comment by patrickkunka** [comment]
Have just had a chance to test this and all is working as expected for me.

Firstly, here's my `package.json`:

```json
{
    "name": "webpack-test",
    "version": "0.0.0",
    "private": true,
    "scripts": {
        "build": "./node_modules/.bin/webpack"
    },
    "devDependencies": {
        "webpack": "^3.8.0",
        "mixitup": "3.2.2",
        "babel-core": "^6.25.0",
        "babel-loader": "^7.1.1",
        "babel-preset-env": "1.6.1"
    }
}
```

Secondly, here's my `webpack.config.js`:

```js
const path = require('path');

module.exports = {
    entry: './src/main.js',
    output: {
        filename: 'app.js',
        path: path.resolve(__dirname, 'dist')
    },
    devtool: 'source-map',
    module: {
        rules: [
            {
                test: /\.js$/,
                exclude: /(node_modules)/,
                use: {
                    loader: 'babel-loader'
                }
            }
        ]
    }
};
```
This takes the following input of `/src/main.js`:

```js
import mixitup from 'mixitup';
import mixitupPagination from './mixitup-pagination';

mixitup.use(mixitupPagination);

console.log(mixitup);
```
And outputs a bundle to `/dist/app.js`, which console logs a reference to the `mixitup` factory function with the pagination extension successfully integrated.

Finally I have the following index.html page which loads the working bundle. 

```html
<html>
    <head>
        <title>Webpack Test</title>
    </head>
    <body>
        <script src="./dist/app.js"></script>
    </body>
</html>
```

On loading this page, the console log appears as expected with no errors, and I can successfully create instances of mixitup with pagination enabled. 

I hope that is helpful. I would double check that you are definitely not including anything other than your app bundle via a script tag in your HTML.

**Comment by jimblue** [comment]
Ok thank you for your help, I finally found the problem.

It was coming from my `.babelrc`:

```js
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "modules": false
      }
    ]
  ]
}
```

Passing modules to true fix it!

The doc from babel that help me for people having the same issue:

https://github.com/babel/babel/tree/master/packages/babel-preset-env#modules

**Comment by patrickkunka** [comment]
Oh glad you figured it out.

Out of interest, what was the reason you had `modules` set to `false`? Would be be good for me to understand what circumstances people would use that configuration option. 

A lot of libraries (like MixItUp) use a "UMD" module export, which relies on either a commonjs or AMD environment being present at runtime.

**Comment by jimblue** [comment]
Set modules to false ensure that import statements are left as is (opposed to transpiling them to require). Doing this give Webpack the ability to statically analyze the code to produce more efficient bundles...

**Comment by jimblue** [comment]
Further reading: https://github.com/babel/babel/tree/master/packages/babel-preset-env

**Comment by jimblue** [comment]
I don't know why pagination plugin isn't compatible with this option.
It's the only import I use that cause this problem.

**Comment by patrickkunka** [comment]
Ah ok, I understand. Unfortunately, the MixItUp source code doesn't use a standard module loading system internally, so I can see why that would happen. I'll see if I can make some changes to the UMD declaration to get around this, as sounds like a useful optimisation for the rest of your project.

**Comment by jimblue** [comment]
That would be awesome :)

**Comment by jimblue** [comment]
That made me think to this issue: https://github.com/meandmax/lory/blob/master/dist/lory.js

Looks like this libs use some automatic building method from webpack (probably an additional plugin) to create a UMD declaration.

And this is working with the modules option of babel 😎

**Comment by jimblue** [comment]
One more reason to make the move to webpack don't you think?
Plus es6, uglify-es, stylelint, UMD, optimisations... didn't you dream about it? 😛

**Comment by jimblue** [comment]
Plus the webpack is already done, it's simple as a copy past for you:

https://github.com/meandmax/lory

**Comment by jimblue** [comment]
Hey @patrickkunka any update about this?

**Comment by ghost** [comment]
Hi Jim. I'm afraid I don't have any plans to address this until the next major version where I will probably rewrite MixItUp in TypeScript. I can't give any particular ETA on this as I don't have a lot of time for side-projects at the moment.

**Comment by jimblue** [comment]
Ok no worries Patrick. Thanks for answering.

**Comment by jimblue** [comment]
With latest version of babel the above fix doesn't work anymore...
It could be nice if you could make a quick fix.
It's now impossible to load your plugin with bundler.

**Comment by jimblue** [comment]
When import pagination like this:

```js
import mixitup from 'mixitup'
import mixitupPagination from '../libs/mixitup/mixitup-pagination'
mixitup.use(mixitupPagination)

```
Getting this warning:

```bash
"export 'default' (imported as 'mixitupPagination') was not found in '../libs/mixitup/mixitup-pagination'
```

The only way I've found to pass this warning is to import pagination like this:

```js
import mixitup from 'mixitup'
import * as mixitupPagination from '../libs/mixitup/mixitup-pagination'
mixitup.use(mixitupPagination)
```

But it's still not working, mixitup fire an error in the console:

```bash
Uncaught Error: [MixItUp Pagination] MixItUp core not found
```

**Comment by jimblue** [comment]
I've try to export mixitup pagination like by modifying source code but it just don't work.

I need you help.

**Comment by jimblue** [comment]
Hello,

Have report this issue for more than 1 years, I tried to help with some hints but still no fix.

What a bad support for something I've paid for... I still can work with it for my website it's unacceptable.

Please come back with a fix, I don't need a typescript version 4, I just need something working now.

**Comment by patrickkunka** [comment]
Hi Jim

Apologies for the delay in response.

However, I've just tried to recreate the issues you're seeing using the latest babel, babel-preset-env, module:false, and webpack, and everything is working fine for me.

I've created a repo here to demonstrate a working setup, with the most stripped-down setup possible:

https://github.com/patrickkunka/mixitup-babel-test

If you build it and load up the index.html with a webserver, you'll see a functioning pagination demo, built with webpack and babel.

Please tell me what's different about your babel/webpack configuration.

**Comment by jimblue** [comment]
Hi Patrick,

Let me try your test and run a few test to check what you're saying.
I'm coming back to you asap.

Best.

**Comment by patrickkunka** [comment]
Thanks for understanding!

I'm hoping that the issues you're seeing might not be related to MixItUp but something else in your environment – but if you can help me figure out how we can tweak the repo above in order to recreate the errors you're seeing then that will be a good start.

**Comment by montagmorgens** [comment]
Hey @patrickkunka,

unfortunately, we get the same errors as above. Has there been any work done on this issue or any new recomendations?

**Comment by patrickkunka** [comment]
Hi there - were you able to test in the example repo I provided? If you could highlight any differences in integration that cause yours to fail I'd be more than happy to look into this.

**Comment by montagmorgens** [comment]
I didn't test the example repo. My webpack config for the babel-loader looks like
```
{
  test: /\.jsx?$/,
  loader: 'babel-loader',
  exclude: /node_modules\/(?!(dom7|swiper)\/).*/,
  options:
  {
    presets: [
      ['@babel/env',
      {
        targets:
        {
          browsers: ["> 0.5%", "last 2 versions", "Firefox ESR", "IE >= 11", "safari >= 7"]
        },
        useBuiltIns: 'usage',
        corejs: 3,
        exclude: ['transform-regenerator'],
        modules: false
      }]
    ],
    plugins: ['@babel/plugin-syntax-dynamic-import']
  }
}
```

**Comment by jimblue** [comment]
yeah pretty classic config, I got the almost same one. (I just don't exclude transform-regenerator)

**Comment by patrickkunka** [comment]
Hi @montagmorgens - thanks so much for sharing your config.

I was finally able to fully recreate the issue. It seems that previously, my .babelrc was being ignored by webpack and babel loader, so moving the preset config to the webpack config itself was the key.

So, the fix is actually very simple, we just need to ensure that the directory containing our MixItUp extensions is excluded, just as we exclude `node_modules`.

Here's my webpack.config.js now (i've removed anything that isn't relevant to the issue):

```js
const path = require('path');

module.exports = {
    entry: './src/index.js',
    output: {
        filename: 'bundle.js',
        path: path.resolve(__dirname, 'dist')
    },
    mode: "development",
    devtool: 'source-map',
    module: {
        rules: [
            {
                test: /\.js$/,
                // NB: the directory containing your mixitup extensions
                // must be excluded from transpilation
                exclude: /(node_modules|vendor)/,
                use: {
                    loader: 'babel-loader',
                    options: {
                        presets: [
                            [
                                '@babel/env',
                                {
                                    useBuiltIns: 'usage',
                                    corejs: 3,
                                    modules: false
                                }
                            ]
                        ]
                    }
                }
            }
        ]
    }
};
```

I've also updated the reproduction project, so you can test it there and see it working (or failing by removing the extra `vendor` exclude.

https://github.com/patrickkunka/mixitup-babel-test

Please let me know if this works for you (if either of you are still interested in using MixItUp extensions with ES modules).

**Comment by patrickkunka** [comment]
Have also updated the docs:
https://www.kunkalabs.com/mixitup-multifilter/docs/get-started/
https://www.kunkalabs.com/mixitup-pagination/docs/get-started/
