### ISSUE TITLE
Issue with Reset Button

### ISSUE THREAD

**Issue by briancools** [patrickkunka/mixitup#395]
Hello Patrick

I am integrating the MixItUp on one of my sites.
I work with logic 'or'.
I do not necessarily want to show the 'All' filter.
When my page is loaded, and I click on one of the filters, the 'all' filter (which is not visible) is still active, whereas it should be off.
The fact that it remains active, does not allow us to filter the content (because the 'all' is still active).

Suppose we find a solution to this, when I click on my reset button, I have to see all the content (so the filter 'all' must be reactivated), and so on.

How do I make sure that when I click on a filter (and not the 'all' filter), the 'all' filter turns off?

A link below to look at the problem more closely.

https://codepen.io/Finessebrands/pen/ooypEQ

**Comment by patrickkunka** [comment]
Hi Brian,

If I understand correctly, you are looking for something like the following functionality, where the "all" filter is deactivated whenever toggles are active:

https://demos.kunkalabs.com/mixitup/toggle-filtering-or-logic/

The toggling vs filtering functionality was greatly improved in MixItUp v3, so I would recommend upgrading your project to MixItUp 3.

You can find a migration guide from v2 here: 

https://www.kunkalabs.com/mixitup/migration-guide/

And more information on filtering and toggling here:

https://www.kunkalabs.com/tutorials/filtering-with-mixitup/
