### ISSUE TITLE
Is there a Mixitup 3 example with search filter?

### ISSUE THREAD

**Issue by robertUzias** [patrickkunka/mixitup#398]

**Comment by patrickkunka** [comment]
Have you seen this demo?

https://demos.kunkalabs.com/mixitup/filtering-by-text-input/

**Comment by robertUzias** [comment]
Oh yes. To be honest, I thought there was a demo similar to [this one (advanced multifilter)](https://codepen.io/patrickkunka/pen/KpVPWo) with mixitup 3. 

Is that very hard to archieve? A mixitup 3 gallery with search bar, multifilter and pagination?

**Comment by patrickkunka** [comment]
The multifilter extension has built in support for filtering by text input. There is a demo included in the multifilter zip file. You can mix and match whatever kind of input types you like.

The pagination extension can be easily applied to any multifilter project just as you would normally do.

Unfortunately there is currently no demo that shows all three features in use simultaneously, but you should be able to combine the various applicable demos together easily, without any custom code.

**Comment by maivdigital** [comment]
For anybody that looks into this feature with MixItUp v3 this is a gold find. This page shows sorting and multi filtering. This example code didn't quite work for me but it did serve as a great reference.

https://www.bostoen.be/assets/bower_components/mixitup-multifilter/demos/text-inputs/

**Comment by maivdigital** [comment]
Hey also I made this codepen.

This should help somebody.

https://codepen.io/mackDEV2/pen/rNmQBoM
