### ISSUE TITLE
It is possible to dinamically add filters to Mixitup?

### ISSUE THREAD

**Issue by robertUzias** [patrickkunka/mixitup#399]
Hello. I'm currently working with the demo "programmatic-filtering-by-url-with-pagination" from multifilter plugin and I'm willing to implement something related to this piece of code:

```js
// NB: You will need to rename the following keys to match the names of
// your project's filter groups – these should match those defined
// in your HTML.

var uiState = {
    color: mixer.getFilterGroupSelectors('color').map(getValueFromSelector),
    shape: mixer.getFilterGroupSelectors('shape').map(getValueFromSelector),
    size: mixer.getFilterGroupSelectors('size').map(getValueFromSelector)
};
```

Well, I need to add dinamically new clasifications. They come from database, for example: Squares, and Circles, Then if I add "Triangles" how can I make it work or add it automatically to this uiState?

Thanks, your plugin is awesome by the way.

**Comment by patrickkunka** [comment]
Hi,

That's fine - you'd firstly need to get a list of your filters from your DB, and provide it to your JavaScript. The most common approach would be to embed JSON into your HTML with a list of all categories when your page is rendered.

So let's say our JavaScript has access to an array of categories `filterCategories` that has been provided via JSON by a hypothetical back-end templating language:

```html
<script>
var filterCategories = {{@json(filter_categories)}}; // ["color", "shape", "size"]
</script>
```

The code you pasted above can now be changed to a dynamically populated "hash map":

```js
var uiState = {};

filterCategories.forEach(categorySlug => {
    const categoryValue = mixer.getFilterGroupSelectors(categorySlug).map(getValueFromSelector);

    uiState[categorySlug] = categoryValue;
});
```

We now have an object identical to the original one, but built up dynamically. You can apply the same pattern to anywhere else in the demo code where these might be hardcoded.
