### ISSUE TITLE
(Question) How can I prevent mixitup pagination/multifilter code from being stolen?

### ISSUE THREAD

**Issue by robertUzias** [patrickkunka/mixitup#403]
I know that with the "inspection" tool integrated in every browser it's a bit hard. I was wondering how, for example. if I upload a project with your plugins how can I protect them from being stolen/copied. Any advice? (Like you did on Kunkalabs)

**Comment by patrickkunka** [comment]
Unfortunately, there's really nothing we can do with JavaScript in this regard as the web is ultimately an open source platform and hopefully always will be. I really appreciate your concern, but please know you have no responsibility to do this as an owner of a premium extension!

Using some type of bundler (e.g. webpack) over script tags and globals will help to some extent by obfuscating and minifying the boundaries of the source code (and also not providing source maps in production). 

Ultimately however this is a problem I have to live with running a company selling JavaScript. Generally speaking, I hope that the benefits of legally owning an extension, and getting access to regular bug fixes, updates and demos is enough to convince people its worth buying over stealing. Over the past 4 years of doing this, I've found that developers and dev teams are great people and usually very happy to pay for something of quality which is well documented, and the people who would try to steal aren't the same people that would ever pay anyway!
