### ISSUE TITLE
Multiple MixItUp on 1 page

### ISSUE THREAD

**Issue by TELUS-Alexander** [patrickkunka/mixitup#405]
Hello,

Awesome plugin!

I have 2 MixItUp controls + items on a page. I notice that they are connected to each other. I would like for them to be entirely independent.

Which object configuration properties do i need to set and what conditions needs to be met in the html structure for this to work?

if you could point me to an example that would be amazing.

Thanks for your help.

**Comment by TELUS-Alexander** [comment]
ok i believe i have found the sound in the demo "MixItUp Demo - Multiple Mixers with Local Control Scoping"

Question, is there a way to initiate only 1 mixitup, using a class, or does each container need to be initiated as if it has a unique identifier, such as an id or data-ref="" attribute as in your example?

your example uses `[data-ref="container-1"]` and `[data-ref="container-2"]`, both containers are within the <div class="container" />

hope this makes sense, thanks for your help.

**Comment by patrickkunka** [comment]
Yes - i was going to direct you to that demo. You can use class names, ids, or any arbitrary data attribute to query and obtain references to your container elements. You just need to make sure you have a unique reference to each of the container elements you wish to instantiate MixItUp on, which is what you pass to the `mixitup()` factory function.

```js
var config = {
    scope: 'local'
};

mixitup(container1, config);
mixitup(container2, config); 
```

How we arrive at the `container1` and `container2` variables in the above example is not important. Querying by `data-ref` attribute in the demo simply provides a means of separating JavaScript selectors from styling selectors which I've found very useful in large projects as it allows us to refactor markup and styling without breaking JavaScript functionality, and vice-versa.

Another common scenario is where your page is constructed dynamically and you therefore have an unknown number of mixitup containers. In this case, you could give each of them same class name (e.g: 'container') and use `document.querySelectorAll('.container')` to obtain an array-like NodeList of all container elements. You can then iterate through the list in a loop, calling the mixitup factory function on each one, without the need for a unique identifier on each container.

However a component-based architecture is probably preferable in this case, where each component is responsible for obtaining its own container reference and instantiating its own instance of MixItUp.

Hope that helps.
