### ISSUE TITLE
Add Range Slider Demo to Core

### ISSUE THREAD

**Issue by patrickkunka** [patrickkunka/mixitup#406]

**Comment by HAkbariMoghadam** [comment]
I bought multi filter and paging component, any chance to give a deadline for implementing this issue for us? we really need this

**Comment by patrickkunka** [comment]
Done! Here you go:

https://demos.kunkalabs.com/mixitup/filtering-by-range/

Requires the latest v3.3.0: https://github.com/patrickkunka/mixitup/releases/tag/v3.3.0

Also, not tested yet but should be compatible with both the MultiFilter and Pagination extensions.

**Comment by HAkbariMoghadam** [comment]
Thank you very much for fast support :)

**Comment by adnanhaider80** [comment]
What if i want to add two different range attributes?
e.g Price Range selector & Guest Range selector
