### ISSUE TITLE
Need help with Bootstrap grid

### ISSUE THREAD

**Issue by lenamtl** [patrickkunka/mixitup#407]
Hi,

I need some guidance, I'm using Bootstrap3

I want to display 3 video cards per row so I'm using col-md-4 for each card 
The problem is when selecting a filter (click of a button)  it's show the card at the actual position then we see the card moving to the new position and while non wanted card disappear and I don't want to see this glitch ...

This is the main container 
`<div class="row " data-ref="container-1"> </div>`

and this is the content of one card (I have 18 cards)

```
<div class="mix myfilter1 myfilter2">	
	<div class="col-md-4">
		video card code here
	</div>
</div>

```

**Comment by lenamtl** [comment]
I have set the animation to false for now, I guess this is the only solution.

**Comment by patrickkunka** [comment]
Happy to look at this if you could provide a link or reproduction. Without looking at your CSS - you might want to make sure that you are not using float-based or nth-child-based styling, which is common in various grid frameworks.

Flexbox or inline-block is recommend over floats. Please see this tutorial for more information:

https://www.kunkalabs.com/tutorials/mixitup-grid-layouts/
