### ISSUE TITLE
Dropdown menu in item is blocked

### ISSUE THREAD

**Issue by vemaxlee** [patrickkunka/mixitup#409]
Dropdown menu in item is blocked, and bootstrap Popover is also blocked. Dropdown menu or Popover is generated by template. Everything else is normal. It's a headache. Is there any way to solve it? 

![ize_h26p v lws m_zs5tia](https://user-images.githubusercontent.com/13921287/34846877-8cc339c8-f754-11e7-9986-972e76e5700e.png)

![8 f 3h h o 3b ygtg9 r5](https://user-images.githubusercontent.com/13921287/34846840-6c0beb26-f754-11e7-9f45-d864822858c0.png)

The following is my CSS Style:
`/*----------------------------------------------------------------------
 *grid Container
---------------------------------------------------------------------- */

.gi-container {
    padding: 1rem .5rem;
    overflow: hidden;
}
/* Target Elements
---------------------------------------------------------------------- */

.mix {
    float: left;
    margin: 0 .5rem 1rem;
    background: #fff;
    border-radius: 2px;
    position: relative;
}

.mix:before {
    content: '';
    display: inline-block;
}

/* Grid Breakpoints
---------------------------------------------------------------------- */

/* 2 Columns */

.mix {
    width: calc(50% - 1rem);
}

/* 3 Columns */

@media screen and (min-width: 541px) {
    .mix {
        width: calc(100%/3 - 1rem);
    }
}

/* 4 Columns */

@media screen and (min-width: 961px) {
    .mix,
    .gap {
        width: calc(100%/4 - 1rem);
    }
}

/* 5 Columns */

@media screen and (min-width: 1281px) {
    .mix,
    .gap {
        width: calc(100%/5 - 1rem);
    }
}`

**Comment by patrickkunka** [comment]
Can you include a link? I'm not quite sure what you mean by blocked.

I suspect this is to do with the presence of the `data-toggle` attribute on your bootstrap dropdown. This is common problem for users of bootstrap and MixItUp. It can be fixed as per the solution in this issue:

https://github.com/patrickkunka/mixitup/issues/268

**Comment by vemaxlee** [comment]
@patrickkunka Thanks for your reply, My problem is that when placing a bootstrap dropdown menu in the item wrap, the menu is hidden behind the item wrapper when clicked it. But, just now I tested in official demo and  that the dropdown menu works fine, I suppose it's because of a own change in the style of the mixitup, or any other element in my page that has caused it to interfere. **It's not a problem with mixitup itself** . thanks again!
