### ISSUE TITLE
Multiple Instances, Same Controls - Mixitup 3

### ISSUE THREAD

**Issue by shahjehanali1** [patrickkunka/mixitup#410]
Can Any one help me to figure this out,,
How cab I use Multiple Instances and Same Controls

**Comment by lenamtl** [comment]
Hi,

For one control & multiple instances
You can use this demo (check the code source of the page) 
https://demos.kunkalabs.com/mixitup/multiple-instances-global-control-scoping/

To see all demos:
https://demos.kunkalabs.com/mixitup/

**Comment by shahjehanali1** [comment]
Hi!
@lenamtl 
I'm using custom controls

**Comment by patrickkunka** [comment]
If you're going via the API (I'm assuming you are if you've built your own controls), you just need to call the appropriate API method on each of your MixItUp instances.

For example, a custom filter button, that filters multiple mixers:

```js
var mixer1 = mixitup(container1);
var mixer2 = mixitup(container2);
var filterAllBtn = document.querySelectorAll('#filter-all');

filterAllBtn.addEventListener('click', function() {
    mixer1.filter('all');
    mixer2.filter('all');
});
```
