### ISSUE TITLE
Multifilter with url 

### ISSUE THREAD

**Issue by Kagayakashi** [patrickkunka/mixitup#411]
Hello, Patrick!
Im newbie in web programming and i using your plugin. By using your guide, now I have multifilter and that works fine, but how to add url changing for multifilter, something like this like this "page.com/#color=red + #type=boots +...." or another version.

Can you help me, please?

**Comment by patrickkunka** [comment]
Hi,

In the multifilter extension zip file, you'll find a directory called demos. In there you will find a demo called "programmatic filtering by URL" which does exactly what you are describing.
