### ISSUE TITLE
Text input search multivalue

### ISSUE THREAD

**Issue by Toubef** [patrickkunka/mixitup#413]
Hi,

Thanks for a great product.
Is there a way to use text input search with multiple values in search box like: 5, new, star

So it would search for all those values?

Thanks
Toube

**Comment by Toubef** [comment]
I got it working using searchkey|searchkey that works like and "and" operator but you can't specify any deeper conditons that way.

**Comment by patrickkunka** [comment]
Unfortunately searching by text input like this is very crude and you will always be limited by what you can express as a DOM selector.

One solution is to create a separate search field for each "dimension" you would like to search for, (e.g. one for color, one for name), and then concatenate the values together.

If you use the MultiFilter extension, you can build this kind of interface without any custom JavaScript.

Generally speaking however, I recommend if you want to do anything complex with text search, that you do it server side over an API, and return a list of matching IDs which you can then query the DOM with.
