### ISSUE TITLE
How to add dynamic elements in mixitup 3

### ISSUE THREAD

**Issue by shahjehanali1** [patrickkunka/mixitup#415]
Hi! Hope you fine?
I will add this dynamic elements in mixitup 3,
I need snippet
this Is my Code

> setTimeout(function(){
                 $.ajax({
                  url: "/assets/filmlist_2.php"+'?'+Math.random()*Math.random(),
                  dataType : 'html',
                  cache: false,
                }).done(function(responce) {
                  console.log("success");
                  $('#filmlist').html(responce);
                  mixer.append([responce]).then(state => {
                         console.log(state.totalShow);
                     });
                  $("#filmlist a").each(function(e) {
                    var bg = $(this).data('background');
                     $(this).css('background-image', 'url('+bg+')');
                  });
                })
                .fail(function() {
                  console.log("error");
                })
                .always(function() {
                  console.log("complete");
                });
               }, 3000);

**Comment by patrickkunkadazn** [comment]
Hi,

The `.append()` API methods expects any of the following:
- a single DOM element
- a list of one or DOM elements
- a jQuery object holding one or more elements
- an HTML string representing a single DOM element

If you send any of the above to the method, the corresponding targets will be inserted into your mixer after any existing targets.

In your example above, it looks like you are sending your API response directly into MixItUp. According to your $.ajax configuration, it seems like your API returns HTML. However, you are wrapping it in an array `[responce]` (sic) which will not work.

Can you provide an example of what the HTML looks like that your API returns?

If you are returning HTML representing multiple elements, you need to convert them into a list of DOM elements or a jQuery object before you send it to `append()`.

I hope that helps.

**Comment by patrickkunka** [comment]
Hi,

The `.append()` API method expects any of the following:

- a single DOM element
- a list of one or DOM elements
- a jQuery object holding one or more elements
- an HTML string representing a single DOM element

If you send any of the above to the method, the corresponding targets will be inserted into your mixer after any existing targets.

In your example above, it looks like you are sending your API response directly into MixItUp. According to your `$.ajax` configuration, it seems like your API returns HTML. However, you are wrapping it in an array `[responce]` (sic) which will not work.

Can you provide an example of what the HTML looks like that your API returns?

If you are returning HTML representing multiple elements, you need to convert them into a list of DOM elements or a jQuery object before you send them to `append()`.

I hope that helps.

**Comment by shahjehanali1** [comment]
>
function convertHTML ( html ) {
      var newHtml = $.trim( html ),
              $html = $(newHtml ),
              $empty = $();

      $html.each(function ( index, value ) {
          if ( value.nodeType === 1) {
              $empty = $empty.add ( this );
          }
      });

      return $empty;
  };
 setTimeout(function(){
                 $.ajax({
                  url: "/assets/filmlist_2.php"+'?'+Math.random()*Math.random(),
                  dataType : 'html',
                  cache: false,
                }).done(function(responce) {
                  console.log(responce);
                  // $('#filmlist').html(responce);
                  $html = convertHTML( responce );
                  $('#filmlist').html('');
                  // mixer.append* 
                  mixer.append($html)
                  .then(function(state) {
                      console.log(state.show[state.show.length - 1] === $html); // true
                  });
mixer.forceRefresh();
                  $("#filmlist a").each(function(e) {
                    var bg = $(this).data('background');
                     $(this).css('background-image', 'url('+bg+')');
                  });
                })
                .fail(function() {
                  console.log("error");
                })
                .always(function() {
                  console.log("complete");
                });
               }, 3000);
Above code fixed my problem

**Comment by shahjehanali1** [comment]
Now mixitup not working correctly :(
