### ISSUE TITLE
Filter search not resetting at browser back

### ISSUE THREAD

**Issue by ghost** [patrickkunka/mixitup#419]
We have a filter search using data-search-attribute. When searching, and then clicking on a link in an item, and then hitting the browser back button – the search string is still in the search input field. And the possibility to reset or perform another search is gone.

Javascripts
mixitup.min.3.js
mixitup-multifilter.min.3.js

Codepen (only html and javascript, not "working")
https://codepen.io/anon/pen/MQbxdy

**Comment by patrickkunka** [comment]
Hi,

Thanks for creating the GitHub issue.

I would need to see a working link to your project to fully understand the problem.

In the mean time, in order to reset and clear the values your form whenever you load your page, you can try adding the following (right before where you instantiate MixItUp:

```js
var controlsForm = document.querySelector('.controls'); // or whatever selector will match your <form>

controlsForm.reset(); // reset all fields within the form

// instantiate mixitup

var mixer = mixitup(containerEl, {
   ...
```

**Comment by ghost** [comment]
The page in question is https://www.vid.no/studier/

I could not get the extra code working, it resulted in a search filter that did not filter the items.

**Comment by patrickkunka** [comment]
Hi - thanks for the link.

Unfortunately the demo that you based your project on (Filtering by URL) is not compatible with the MultiFilter extension that you are using.

There is a separate version of this demo included in the MultiFilter extension which has been adapted to work with filter groups, which you should switch to.

However, this demo is not compatible with text input searching (specifically it will not accommodate the attribute selectors that searching by text input produces), so - be sure not to include the filter group containing your text input (this will make sense when you see the code in the demo). Let me know if you have any other questions.
