### ISSUE TITLE
Filter search not search when typing multiple words

### ISSUE THREAD

**Issue by ghost** [patrickkunka/mixitup#420]
We have a filter search using data-search-attribute. When searching for an item with multiple words, the search result disappears (nothing found) when typing more than one word.

E.g. when typing "two words", the item with the data-search defined as data-search="two-words" wont appear as a result. Typing only "two" will make it appear. I have also tried data-search="two words" on the item. Returing no results when typing "two words" in the the filter search input.

Javascripts
mixitup.min.3.js
mixitup-multifilter.min.3.js

Codepen (only html and javascript, not "working")
https://codepen.io/anon/pen/MQbxdy

**Comment by patrickkunka** [comment]
Unfortunately this type of searching (using DOM selectors) is very limited. It's best suited to very simple keyword searching. If you need to do anything else more complex you should do it server side over an API with a real database search.

However, it will probably help to understand what's going on, as what you are trying to do *should* work (I've just confirmed this with the "Text Inputs" demo).

When we type something into the search field:
```
"foo"
```

That is then converted into a dynamically generated DOM selector:
```
[data-search*="foo"]
```

Which matches elements with a data-search attribute containing the characters "foo", e.g.:
```html
<div data-search="foo"></div>
```

So, in your case you are searching for two words:
```
"foo bar"
```

Which yields:
```
[data-search*="foo bar"]
```

So as long as your html contains the following (exactly those two words in that order, with a real space character in between):
```html
<div data-search="foo bar"></div>
```

It will match that item.

If you're having trouble, you can always console log the active filter selector via the `onMixEnd` callback, and test it yourself using `document.querySelectorAll('[data-search*="two words"]');` and see what comes back.

**Comment by ghost** [comment]
Thank you for explaining. It works with the exact match and a real space between.

**Comment by patrickkunka** [comment]
Great
