### ISSUE TITLE
Filters apply to newly added DOM elements

### ISSUE THREAD

**Issue by sensaetions** [patrickkunka/mixitup#423]
Hello @patrickkunka,

I'm using mixitup to filter blog categories. The filter functions correctly the first time as the blog thumbnails are already present in the DOM. However, I have a "Load more" button that fetches new blog thumbnails via AJAX, and then are added to the DOM. The filters *did not* apply to these newly added thumbnails. How can the filters watch for newly created DOM elements and apply to them?

Thanks in advance.

**Comment by patrickkunka** [comment]
Hi,

How are you adding your new elements to the DOM?

If you use one of MixItUp's insertion methods (.insert(), .append(), .prepend()), your active filter should be respected, so I'm assuming you're using not, and are manipulating the DOM without MixItUp's knowledge.

You can actually see this feature working on our home page demo. When you click the "+" button, it appends a target to the container using a random colour. If that colour is not the active filter, you will not see the target.

**Comment by jeffnhorner** [comment]
HI @patrickkunka,

I'm running into a similar issue. I am using the easyPaginate plugin to put a image limit on a page. On initial page load, the mixer works great and filters the images properly. However, once I use the easyPaginate navigation to go to the next 15 images, the mixer/filtering does not work properly. 

Any advice?

Thanks in advance!

**Comment by patrickkunka** [comment]
Hi @jhorner32, I doubt MixItUp is compatible with the easyPaginate plugin. We have our own extension to manage this type of functionality. https://www.kunkalabs.com/mixitup-pagination/
