### ISSUE TITLE
MultiFilter active class not being set

### ISSUE THREAD

**Issue by tidy** [patrickkunka/mixitup#424]
When using just mixitup core with data-filter controls, when I set a filter, that control gets class= 'mixitup-control-active' added to it.

However, when I add code to enable mixitup multifilter, this no longer happens. Instead, as I select different data-filter controls, just the word class gets added to each. So all previous selections and the current end up with the class attribute added with no value.

I'm relying on an active class being added so that I can set certain text on the page with javascript based on the current filters.

Here is the markup I am using for the controls (also using Bootstrap):
```
<form  data-filter-group="destination">
                <div class="wrap clearfix">
                    <button class="btn btn-block btn-filter btn-destination dropdown-toggle" type="button" id="destination" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Destination <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="destination">
                        <li data-mixitup-control data-filter=".dublin">Dublin</li>
                        <li data-mixitup-control data-filter=".cork">Cork</li>
                        <li data-mixitup-control data-filter=".galway">Galway</li>
                        <li class="all"><button type="reset" class="btn-reset">All</button></li>
                    </ul>
                </div>
            </form>
```

Here is the mixitup config:
```
var mixer = mixitup('#mixitup', {
      multifilter: {
        enable: true
      },
      selectors: {
        control: '[data-mixitup-control]'
      },
      callbacks: {
        onMixEnd: function(state) {
            window.console.log(state.activeFilter.selector);
        }
      }
    });
  ```

Am I doing something wrong or is this a bug? Thanks.

**Comment by patrickkunka** [comment]
Hi, do you have a link to your project?

**Comment by tidy** [comment]
Thanks for the quick reply Patrick. I do have a link but cannot share it publicly as it's under construction. I'll send you the link directly though via the contact form on your site.

**Comment by patrickkunka** [comment]
Hi Tidy,

Thanks for the link. You are doing everything right - this was a bug (or more accurately another conflict with bootstrap).

I've now added a work around and pushed a new version of the extension (v3.3.3) which you can download from your account.

Please let me know if that works for you.

**Comment by tidy** [comment]
Yes, that works great now! Thanks so much for the instant turnaround on this - not at all expected but very much appreciated :)

**Comment by kulikonch** [comment]
Good afternoon! I use bootstrap 4 and I have a small problem: when "all" is selected, if you click any button (callback etc.), the mixer blocks are collapsed and the button is assigned the "mixitup-control-active" class.
Is there a solution to such a problem?
Yours faithfully, Dmitry
site: https://osnova39.ru/uslugi/stroitelstvo-domov-pod-kluch-kaliningrad/proekty-domov/

**Comment by patrickkunka** [comment]
@kulikonch have you seen this issue: https://github.com/patrickkunka/mixitup/issues/268 ?

Which buttons should I click on your site to reproduce the problem?
