### ISSUE TITLE
Sort by string 

### ISSUE THREAD

**Issue by Lieneke** [patrickkunka/mixitup#427]
Sorting by name:asc or name:desc with a missing attribute on some items gives the error r.tolowercase is not a function and o.tolowercase is not a function. I temporary fixed this by adding .toString() before the toLowerCase().

**Comment by patrickkunka** [comment]
All possible sorting attributes must be present on all target elements in order for MixItUp to sort. A warning should be thrown in the console if any attributes are missing. Did you see the warning?
