### ISSUE TITLE
Sorting on alphanumeric name

### ISSUE THREAD

**Issue by AtmanCore** [patrickkunka/mixitup#428]
Name range
Basement Installation 01 to Basement Installation 105 (105 enteries)
Flexispan-1 to Flexispan-4 (4 enteries)

It doesn't sort naturally on alphanumeric values

**Comment by patrickkunka** [comment]
MixItUp uses native JavaScript sort. If you are going to sort over a large numeric name, ensure your numeric values are correctly padded. E.g:

```
basement-installation-001
basement-installation-033
basement-installation-105
```

Unfortunately, I can't see what the issue is your Flexispan example.

To test your values, you can use array sort in the console:

```js
['Flexispan-04', 'Flexispan-01', 'Flexispan-10'].sort()

// ["Flexispan-01", "Flexispan-04", "Flexispan-10"]
```
