### ISSUE TITLE
V2 CDN

### ISSUE THREAD

**Issue by manattweb** [patrickkunka/mixitup#429]
It looks like you guys removed the CDN for V2 and that has broken several pages one of my WordPress sites.

https://cdn.cloudcanvas.website/wp-content/cc-assets/js/mixitup.min.js 

The file from GitHub is generating an error: SyntaxError: expected expression, got '<' refernecing 
jquery.mixitup.js:7.

Any chance you can re-instate that CDN link or look into what's causing the error on the V2 file?

**Comment by patrickkunka** [comment]
Hi,

Sorry I'm not familiar with that URL. It looks more like a privately hosted wordpress site than a public facing CDN.

If you need a V2 CDN you can use cdnjs:

https://cdnjs.com/libraries/mixitup
