### ISSUE TITLE
Hash Navigation with MultiFilter + Pagination + Text Search 

### ISSUE THREAD

**Issue by conorseed** [patrickkunka/mixitup#430]
**Setup:** 
I have both multifilter and pagination extensions. Hash navigation is enabled and working, as per the "programmatic-filtering-by-url-with-pagination" demo supplied with the multifilter extension. 

I have the below issue on my local dev environment, as well as the development site here: / link removed as no longer valid /

I did not want to create a jsfiddle, as the issue includes both your premium extensions and I wasn't sure the best way to link them to the project.

**The issue:** 
When I reload the page with hash navigation for text search, I get the following errors:
`mixitup.min.js:17 Uncaught DOMException: Failed to execute 'matches' on 'Element': '.data-business*' is not a valid selector.`

It results in any other filter selection not rendering also.

**Desired Result:**
That I can filter by text, region select and service select simultaneously, with the hash updating as I go. Then, if I copy that url into a new tab and load it, it sets the filters according to the hash.

**Comment by patrickkunka** [comment]
Hi,

Unfortunately that demo is not compatible with text search (or any attribute based query selector). Without heavily adapting demo, the best solution would be to exclude your text search filter group from the hash generator code.

There is a part of the code where you will have replaced the filter group names from the demo with your own. Simply omit the search group here.

Let me know if that works

**Comment by conorseed** [comment]
Thanks @patrickkunka 😄That does solve the issue of the errors and not working, but it's a shame that it's not compatible with attribute based query selectors. I'd love to have that functionality.

**Comment by patrickkunka** [comment]
The issue is the following two functions `getValueFromSelector()` and `getSelectorFromValue()` in the demo. They both expect only class-based attributes, and attempt to clean up special characters for a cleaner, more readable URL.

In order to adapt them to handle any kind of selector (but with a less clean URL), we can replace them with the following:

```
function getValueFromSelector(selector) {
    return encodeURIComponent(selector)
}

function getSelectorFromValue(value) {
    return decodeURLComponent(value);
}
```
Have tested this, and it seems to work. Please let me know how you get on.

**Comment by conorseed** [comment]
@patrickkunka brilliant. That works 😄 You're an absolute legend.

**Comment by patrickkunka** [comment]
Great, glad it worked!

**Comment by sjclark** [comment]
@conorseed don't suppose you ever figured out a way to do this with nicer URLs? Think I'm in your exact situation (using data-attributes for the filters).

Ended up running with this for the getValue;
```
function getValueFromSelector(selector) {
    console.log(selector); // [data-ages~='adults']
    return selector.split("'")[1]; //#age=adults
}
```

But can't seem to get the Selector to load from the url properly the other way around 😂 (even thought the console logged result is the same)
```
function getSelectorFromValue(value) {
    console.log(value);
    value = '[data-' + 'age' + '~=\'' + value + '\']';
    return value;
    // [data-ages~='adults']
}
```

**Comment by conorseed** [comment]
@sjclark hey :) I wish I could help but this project was so long ago I have absolutely no idea haha. 
It might mean making your own issue but I'm sure @patrickkunka would be willing to help!

**Comment by sjclark** [comment]
Thought I may as well leave my (very) hacky solution in case someone else comes across this (like I did).

First issue was that it will parse too many `=` symbols, as it's parsed for the keys and the data-attribute. Easiest way is just to sub in another character: 
`output += key + '@';`
`var pair = group.split('@');`

And then in terms of getting the value:
```
function getValueFromSelector(selector) {
    console.log(selector + ' (selector)');
    return selector.split('\'')[1];}
```
And setting I just lazied out and hardcoded each call:
```
function getSelectorFromValueOne(value) {
    var parent = "ages"
    value = '[data-' + parent + '~=\'' + value +'\']';
    console.log(value)
    return value;
}
function getSelectorFromValueTwo(value) {
    var parent = "dates"
    value = '[data-' + parent + '~=\'' + value +'\']';
    console.log(value)
    return value;
}
```

Which basically allows something like `http://domain.test/page#age@adults,kids&dates@Nov-2,Dec-2`

Downside is the hash symbol now shows all the time unfortunately.
