### ISSUE TITLE
[MixItUp MultiFilter] Filter groups do not read initial values on load

### ISSUE THREAD

**Issue by tlygnersjo** [patrickkunka/mixitup#431]
Hi,

I'm trying to implement MixItUp and MultiFilter. Everything works except that when i filter something and go to another subpage and hit back button in browser. The browser remembers the selected options for filter but it is not getting filtered.

How will i solve that? I can't seem to find any docs about this (maybe i should use load filter in some way but i'm not sure how).

**Filters:**
```
<fieldset data-filter-group="" class="filter-group col-12 col-xs-12 col-sm-4 col-md-4 col-lg-4 col-xlg-4">
  <select>
    <option value="">All types</option>
    <option value=".id-17">Type 1</option>
    <option value=".id-18">Type 2</option>
    <option value=".id-19">Type 3</option>
  </select>
</fieldset>

<fieldset data-filter-group="" class="filter-group">
  <select>
    <option value="">All brands</option>
    <option value=".id-13">Brand 1</option>
    <option value=".id-14">Brand 2</option>
    <option value=".id-15">Brand 3</option>
  </select>
</fieldset>

<fieldset data-filter-group="" class="filter-group">
  <select>
    <option value="">All countries</option>
    <option value=".id-90">USA</option>
    <option value=".id-91">United Kingdom</option>
    <option value=".id-92">Germany</option>
  </select>
</fieldset>
```

**Types**
```
<div class="types">
  <div class="type id-13 id-18 id-91">
    <a href="#">
      Type 1
    </a>
  </div>

  <div class="type id-15 id-92">
    <a href="#">
      Type 2
    </a>
  </div>

  <div class="type id-17 id-90">
    <a href="#">
      Type 3
    </a>
  </div>

  <div class="type id-14 id-15 id-18 id-91">
    <a href="#">
      Type 4
    </a>
  </div>
</div>
```

**MixItUp**
```
if( typeof mixitup  === 'function') {
  var container = '.types';
  var selectors = '.type';

  if( $(container).length ) {
    var mixer = mixitup( container, {
      selectors: {
        target: selectors
      },
      animation: {
        enable: false
      },
      multifilter: {
          enable: true
      }
    });
  }
}
```

**Comment by patrickkunka** [comment]
Hi, thanks for raising this.

This looks like an oversight - the filter groups should really be reading in any preset initial values on load, but currently they only react to change events and expect the initial values to be equivalent to 'all'.

I will open an issue to address this, but in the mean time - you can use this workaround to force a change event on each input on init:

```js
var containerEl = document.querySelector('.container');

// Create a multifilter enabled mixer with animations disabled

var mixer = mixitup(containerEl, {
    multifilter: {
        enable: true
    },
    animation: {
        enable: false
    }
});

// Obtain an array of each `select` within a filter group

var selects = Array.from(document.querySelectorAll('[data-filter-group] select'));

function initSelect(select) {
    // Dispatch a `change` event from the select
    var ev = new CustomEvent('change', {
        bubbles: true
    });

    select.dispatchEvent(ev);
}

// Iterate through each select, calling the `initSelect` function

selects.forEach(initSelect);

// Re-enable animations after initial filter

mixer.configure({
    animation: {
        enable: true
    }
});
```

**Comment by tlygnersjo** [comment]
Hi Patrick,

Thanks for a quick response!

Thanks seems to almost work. The problem now is that if i select multiple filter and go to another subpage and then back again and select a different option in one filter it won't update the result based on all filters (only the clicked one). Any chance you've got a solution for that as well?


Thanks in advance!

**Comment by tlygnersjo** [comment]
Any idea how this can be solved?

I don't want to rush you but I'm about to go live with this project so it would be great if the filter could be fixed before the launch.

**Comment by patrickkunka** [comment]
Can you provide a link and steps for a reproduction?

**Comment by tlygnersjo** [comment]
Ignore my last answer (it was a cache related problem), it seems to work now with the code you provided.

Thank so much for your help.

Have a nice weekend!

**Comment by ghost** [comment]
Noting that if we set initial load values through the markup, any "reset" button click will reset to those initial values, rather than clearing the form.

Best current approach should still be considered programmatic JS-based, rather than markup based, eg:

```js
var containerEl = document.querySelector('.container');

var mixer = mixitup(containerEl, {
    multifilter: {
        enable: true
    },
    animation: {
        enable: false,
        effects: 'fade translateZ(-100px)'
    }
});

mixer.setFilterGroupSelectors('shape', '.circle');
mixer.setFilterGroupSelectors('size', '.small');

mixer.parseFilterGroups();

mixer.configure({
    animation: {
        enable: true
    }
});
```

**Comment by patrickkunka** [comment]
Have investigated fixing this and it seems there are too many potentially unintended edge cases that could arise.  If anyone needs this functionality, the best approach would be to always manually parse your filter group inputs before mixer instantiation, and manually set any active selectors per group as needed, per the solution above.
