### ISSUE TITLE
URL/hashtag function removes first character

### ISSUE THREAD

**Issue by danielbenjamins** [patrickkunka/mixitup#436]
I have this weird issue that when I use the URL/hashtag function, it removes the first character of the filter.

So when I click on a filter, instead of **http://myurl.local/#eighteen** it shows **http://myurl.local/#ighteen** in my address bar and the filter is not working. Hence the missing "e", the first character.

My filter: <div class="filter filter-eighteen" data-filter="eighteen"><span>2018</span></div>
The matching div: <div class="publication-item mix eighteen">My content</div>

I used the exact same code on a different website last week without any problems.

Any suggestions?

**Comment by patrickkunka** [comment]
Hi and thanks for this ticket. It looks like its probably resulting from an error in one of the regular expressions in the demo designed to remove the first `.` character from a class name, but it unintentionally removes any first character (if the selector does not start with a `.`)

In the source code of the demo, you will see this functon:

```js
function setHash(state) {
    var selector = state.activeFilter.selector;
    var newHash = '#' + selector.replace(/^./g, '');

    if (selector === targetSelector && window.location.hash) {
        // Equivalent to filter "all", remove the hash

        history.pushState(null, document.title, window.location.pathname); // or history.replaceState()
    } else if (newHash !== window.location.hash && selector !== targetSelector) {
        // Change the hash

        history.pushState(null, document.title, window.location.pathname + newHash); // or history.replaceState()
    }
}
```

On the third line of the function, please change `selector.replace(/^./g, '')` to `selector.replace(/^\./g, '')`.

Please let me know if that works. I will push a new version of the demo with the corrected expression in the mean time.

**Comment by danielbenjamins** [comment]
That worked for me, thank you!

**Comment by patrickkunka** [comment]
Demo has been fixed.
