### ISSUE TITLE
Search and special danish char

### ISSUE THREAD

**Issue by johannesdb** [patrickkunka/mixitup#439]
Hi

on this site, www.udstillerguide.dk/demo, I have used mixitup multifilter extension.

It works as expected unless there is a special char in the search string.

For example if I search for "Fræs" there is no results eventhough there should be as one of the items is called "Fræs&Ræs cykler". I am using the value from data-name when searching for a match.

What am I doing wrong?

Regards Johannes

**Comment by patrickkunka** [comment]
Hi there.

Version 3.3.4 of the MultiFilter extension implements a "diacritics map" which maps non-ascii characters to their ascii equivalents to make searching less brittle. This is standard practice for any search engine, as well as lowercasing all characters, and the stripping out non-word characters such as "&".

For more information, see this issue: https://github.com/patrickkunka/mixitup/issues/402

For example, your item "Fræs&Ræs cykler" would be queried as:

```
[data-navn*="fraes raes cykler"]
```

This does mean however that if you expect to have special characters in your content you must implement the same logic on the server-side to sanitise all searchable attributes. You should be able to find a generic function to do this for whatever language/framework you are using on the back-end.

Your HTML is currently:

```html
<div class="et_pb_post et_pb_has_overlay element mix cykler-og-biler" data-navn="fræs&amp;ræs cykler">
   ...
</div>
```

But it would need to be rendered as

```html
<div class="et_pb_post et_pb_has_overlay element mix cykler-og-biler" data-navn="fraes raes cykler">
   ...
</div>
```

You will also need to upgrade to v3.3.4 of MixItUp MultiFilter, as you are currently using using v3.3.0.

Thanks

**Comment by johannesdb** [comment]
Perfect! Thanks!

**Comment by johannesdb** [comment]
Just to say a propper thank you: I was able to fix the problem in less than an hour :-) Perfect!

Thank you again for a superb product and support!

**Comment by gutdingwillweilehaben** [comment]
Hi,
Is there also a solution for German (ä,ö,ü) and French (é, à, è,...) special characters?
It would be perfect to use `data-navn="büro"` for text search.

**Comment by patrickkunka** [comment]
Its the same solution as above - it's not language specific. You just need to strip out and replace all non ascii characters on the back-end. MultiFilter will transform `ü` to `u` automatically, so you just need to make sure your markup matches the sanitised version of any query.

**Comment by Scopestyle** [comment]
> Its the same solution as above - it's not language specific. You just need to strip out and replace all non ascii characters on the back-end. MultiFilter will transform `ü` to `u` automatically, so you just need to make sure your markup matches the sanitised version of any query.

This comment described the error in my logic, with German characters normally the umlauts are not transformed like this. A normal text sanitizer would transform text like this: ä > ae, ü > ue, ö > oe. So I had to write my own sanitizer to change the characters like this: ä > a, ü > u, ö > o. This is the only way this works. I hope this helps someone looking for a similar solution.
