### ISSUE TITLE
[MixItUp MultiFilter] Configuring one or more filter groups to use "AND" logic

### ISSUE THREAD

**Issue by kyloknight** [patrickkunka/mixitup#440]
Current Code:
```
var mixer2 = mixitup(containerEl, {
  controls: {
    enable: true,
    live: true,
    toggleDefault: 'all',
    toggleLogic: 'and',
  },
  multifilter: {
    enable: true
  },
  animation: {
    effects: 'fade translateZ(-100px)'
  }
});
```

From how I understand this in the documentation, "and" should be removing options not adding them on like "or" does. Setting "and" does exactly what "or" does.

HTML looks like this:

```
<form class="controls">
  <fieldset data-filter-group="" class="checkbox-group">
    <div class="checkbox">
      <input type="checkbox" value=".example"><label class="checkbox-label">Example Title</label>
    </div>
    <div class="checkbox">
      <input type="checkbox" value=".example2"><label class="checkbox-label">Example Title 2</label>
    </div>
  </fieldset>
</form>

<article class="mix example"></article>
<article class="mix example2"></article>
<article class="mix example example2"></article>
```

So in the above example situation, if both example and example2 are ticked only the third article should show, but this does not happen.

**Comment by patrickkunka** [comment]
Hi there,

Looking at your code, the problem appears to be that you are using the MultiFilter extension with standard MixItUp core configuration options.

When using MultiFilter, you need to configure your filtering logic using the `multifilter` configuration object, which exposes several new configuration options specific to the extension.

This is documented here:

https://www.kunkalabs.com/mixitup-multifilter/docs/configuration-object/

If you want to set all your groups to "and" logic, you would set the `multifilter.logicWithinGroup` property to `'and'`.

```js
ar mixer2 = mixitup(containerEl, {
  controls: {
    enable: true,
    live: true,
    toggleDefault: 'all'
  },
  multifilter: {
    enable: true,
    logicWithinGroup: 'and'
  },
  animation: {
    effects: 'fade translateZ(-100px)'
  }
});
```

If you only want a particular group to use "and" logic, you can simpy add a `data-logic` attribute to the individual group's fieldset, which will override the default configuration for that group:

e.g: 
```html
<fieldset data-filter-group data-logic="and"> ... </fieldset>
```

This is documented here: https://www.kunkalabs.com/mixitup-multifilter/docs/get-started/ under "Configuring Filter Group Logic"

I hope that helps.

**Comment by kyloknight** [comment]
Thanks for that! Yes I did notice that, but I only wanted it for a particular group as I multiple groups that need to use "or" and only one for "and". Thanks a lot!
