### ISSUE TITLE
Sorting special characters

### ISSUE THREAD

**Issue by johannesdb** [patrickkunka/mixitup#441]
Hi,

when sorting danish characters æ, ø  and å the sorting order is wrong.

The sorting is å, æ and ø but should be æ, ø and å.
Furthermore aa should be sorted as å

Where can I correct that?

**Comment by patrickkunka** [comment]
Hi, as discussed in https://github.com/patrickkunka/mixitup/issues/439 special characters are converted to standard ascii characters and sorted accordingly, which explains the behavior you're experiencing.

JavaScript knows nothing about the order of characters in the Danish alphabet, nor does your server.

One solution would be to prefix the contents of your sorting attributes with a number, based off the position of the first character in the danish alphabet. For example, `data-sort="29-foo-bar"`. This is custom functionality that you would have to implement on the server side and unrelated to mixitup.

I hope that helps.

**Comment by johannesdb** [comment]
Thanks for the answer. Ø and Å is a bit tricky as iconv converts them to o and a - but wordpress' normalizer converts them to oe and aa which is the propper way to convert them according to danish standards.

Check with sorting! I will try that :-)
