### ISSUE TITLE
[MixItUp Sorting] Sometimes at sorting all things are flying up till fully sorted

### ISSUE THREAD

**Issue by odanijel** [patrickkunka/mixitup#442]
Hello i have a code that I am using it in a way with database API and Infinite scroll.js. I have added some filters, when I call a filter I reset mixitup and than set new data in. But sometimes happend to elements just fly around, till final stage of animation and than reassemble in correct way. Code of mixser is under, code of infinite scroll is at the bottom. 

    dataholder.mixer = mixitup(controls_container, {
        selectors: {
            //target: '[data-ref="item"]' // Query targets with an attribute selector to keep our JS and styling classes seperate
            target: '.mixitup-elements'
        },
        animation:{
            effects: 'fade',
            //effectsOut: 'fade',
            //effectsIn: 'fade',
            duration: 250,
            nudge: true,
            reverseOut: false
        },
        layout: {
            siblingBefore: document.querySelector('[data-ref="first-gap"]') // Ensure the first "gap" element is known to mixitup incase of insertion into an empty container
            //containerClassName: 'mixitup-elements'
        },
        data: {
            //dirtyCheck: true,
            uidKey: 'file_token' // Our data model must have a unique id. In this case, its key is 'id'

        },
        debug: {
            enable: true,
            showWarnings: true
        },
        render: { // We must provide a target render function in case we need to render new items not in the initial dataset (not used in this demo)
            target: function(item) {
                return "some_render";
            }
        }
    });

Infinite scroll code:

    container_infinite.on( 'load.infiniteScroll', function( event, response ) {

        jQuery('.infinite-scroll-last').text('End of content.');
        infScroll.hideStatusEventElements();

        console.log(response);

        if(dataHolder.filter_active) {
            dataHolder.dataset=null;
            dataHolder.filter_active = 0;
        }

        if(response.length > 0) {
            if(dataHolder.dataset === null) {
                dataHolder.dataset = response;
            } else {
                dataHolder.dataset = dataHolder.dataset.concat(response);
            }

            try {
                dataHolder.mixer.dataset(dataHolder.dataset).then(
                    function (state)
                    {
                        if(response.length < lxdata.limit) {
                            dataHolder.last_page = 1;
                            jQuery('.mixitup-container').infiniteScroll('lastPageReached');
                        }
                    }
                );
            } catch(err) {
                console.log(err);
            }

        } else {
            if(dataHolder.dataset === null) {
                dataHolder.mixer.dataset([]);
                jQuery('.infinite-scroll-last').text('No profiles for this criteria.');
            }
            dataHolder.last_page = 1;
            jQuery('.mixitup-container').infiniteScroll('lastPageReached');
        }

        dataHolder.filter_active = 0;
    });

**Comment by patrickkunka** [comment]
Unfortunately MixItUp is not compatible with infinite scroll.

If you want to show or add items on scroll you have two options.

You can use the append() API method attached to a throttled scroll handler. This is the best option if you are ajaxing items in over an API.

If all items already exist in the DOM however, you can use the pagination extension, and increase the page limit by a regular increment as the user scrolls down. There is a demo included in the extension showing this functionality.

Fundamentally though, you must only interact with the contents of a MixItUp container using the MixItUp API, as MixItUp has no way of knowing if other arbitrary libraries are manipulating the target elements, and this will result in a corrupted state.

**Comment by odanijel** [comment]
I see, acctually append is not good for me, since when filter is triggered I get new set of data that is valid from that on. I dont have acctually problem with Inifinite scroll that part works problem is when calling sometimes it does not sort correcty. I would send you image how it looks to some private mail.

Sometimes work perfect but sometimes happens that glitch.

    dataHolder.mixer.dataset(dataHolder.dataset).then(
                function (state)
                {
                    if(response.length < lxdata.limit) {
                        dataHolder.last_page = 1;
                        jQuery('.mixitup-container').infiniteScroll('lastPageReached');
                    }
                }
            );

Nevertheless thank you for your time.
