### ISSUE TITLE
React integration with MixItUp Dataset

### ISSUE THREAD

**Issue by koentjev** [patrickkunka/mixitup#443]
Thanks for the great work patrickkunka!

According to your docs I should be able to return an element in the render function.
Could you give soms advice on how to render a React element for each item? 
I've tried rendering the elements using React and return their references but the error function is thrown.

Roughly I tried this.
```
window.mixer = mixitup(this.gridElement, { //this.gridElement holds a reference to the container div
    data: {
        uidKey: 'id'
    },
    render: {
        target: this.renderMixTile
    }
});

renderMixTile(item){
    return this.gridItems[item.id].element;
}

registerGridItems(gridItems){ // called when all items are rendered by react
  if(gridItems.length == 0){
    return false;
  }
  this.gridItems = gridItems;
  //this.gridItems [201] = {id: 201; element: [reference to element 201 rendered by React]}
  //this.gridItems [202] = {id: 202; element: [reference to element 202 rendered by React]}
  //etc

  if(window.mixer!==undefined){

  window.mixer.dataset(this.props.articles)
  .then(function(state) {
      console.log("showing" ,state.totalShow," items" );
  }).catch(console.log("error"));
```

Resulting in the catch function being called....

Please get me up to speed on combining this fine lib with React.

Regards,
Koen

**Comment by patrickkunka** [comment]
Hi there,

Sorry for the delay in response.

It is possible to integrate MixItUp with React, but not in the most seamless way. I had originally hoped to build an extension that would make this easier, but there were some issues regarding React's virtual event delegation model that I couldn't overcome, so if you do want to integrate MixItUp with a react component, you'll still need to work fairly closely with the DOM.

Looking at your example - I can't see your render method, but I'm assuming you're having React render your grid items in JSX first. This won't work as you must delegate all control of the DOM to MixItUp from the mixitup container element downwards. React should not know about what is happening inside the container, or you will get diffing errors as React's expected version of the DOM will not be in sync with what MixItUp is doing and vice versa.

So, a typical React integration will look something like this:

```jsx
class MyComponent extends React.Component {
    constructor(props) {
        super(props);

        this.setContainerRef = this.setContainerRef.bind(this);
    }

    setContainerRef(element) {
        this.containerElement = element;
    }

    componentDidMount() {
        this.mixer = mixitup(this.containerElement, {
            selectors: {
                target: '[data-article]'
            }
            data: {
                uidKey: 'id',
                dirtyCheck: true // if you expect your targets' data to change
            },
            render: {
                target: MyComponent.renderTargetHtml
            }
        });

        // render the initial targets on mount (no animation)

        this.mixer.dataset(this.props.articles, false);
    }

    componentDidUpdate() {
        // The props have changed and the component has updated, call
        // dataset with the new data:
        this.mixer.dataset(this.props.articles);
    }

    render() {
        // Render an empty container element on which we will instantiate MixItUp
        return (
            <div>
                <div class="container" ref={this.setContainerRef}/>
            </div>
        );
    }

    static renderTargetHtml(item) {
        // An example target render function, returning a string
        return (`
            <div class="target" data-article id="${item.id}">${item.content}</div>
        `);
    }
}
```
Note that the render function returns a string. You could return a new DOM element too (in memory), but a string is a bit more JSX-like.

Unfortunately it's not possible to simply return a React component constructor, or JSX as of now, although this was my original intention. I was working on an extension to make this possible, but I ran into issues as I mentioned above.

Let me know if that works for you!

**Comment by koentjev** [comment]
Thanks Patrick. 
Sorry for my late response as well.
I'm actually looking for a way to let React be in charge of rendering the tiles and then leaving them as is or inform mixitup about changes it makes. 
Unfortunately that is not possible. Thanks for thinking with me here.

**Comment by matteomanzo** [comment]
Hello Patrick,
I was trying to make MixitUp working with React 16 and thanks to you I am now able to have an initialized container with the items I want, but I cannot bind the buttons that will filter my results. Any tips? Thanks a lot

**Comment by matteomanzo** [comment]
Any news on rendering JSX?

**Comment by patrickkunka** [comment]
Hi Matteo, this will most likely be in the next major version of MixitUp now, which I hope to start working on sometime this year.

**Comment by matteomanzo** [comment]
Great to hear that! Awesome plugin by the way!

**Comment by koentjev** [comment]
I am really looking forward to that as well Patrick.

**Comment by jeffceriello** [comment]
Hi Patrick! Any news on this?

**Comment by 7iomka** [comment]
Any news?
