### ISSUE TITLE
Possible to register multiple Filter?

### ISSUE THREAD

**Issue by harispepic** [patrickkunka/mixitup#446]
Hello patrickkunka 

How can I make a multiple registerFilter?

Like this:
```
mixitup.Mixer.registerFilter('testResultEvaluateHideShow', 'range', this.filterAreaResult.bind(this));
mixitup.Mixer.registerFilter('testResultEvaluateHideShow', 'range', this.filterPriceResult.bind(this));
```

**Comment by patrickkunka** [comment]
Hi Haris,

Ideally, if you need to filter by multiple criteria (e.g. multiple range sliders), you should provide a single function to MixItUp that does everything. This could be composed of multiple functions internally (filterAreaResult, filterPriceResult), but ideally you can create a single entry point into all your logic, and provide that as a single `registerFilter` call.

Alternatively, the 2nd `'range'` argument, in your example is simply a way of ensuring that each plugin/extension can only register a filter once, and could be bypassed by providing unique names for each call, e.g. `range1`, `range2`. However, I would recommend the first solution over this.
