### ISSUE TITLE
toggleLogic 'and' for dropdown filters

### ISSUE THREAD

**Issue by lentilz** [patrickkunka/mixitup#449]
I have a list of over 200 mix elements(of US companies) with two filters: State and Industries. I want to be able to filter to see all companies from a given state, and narrow down by industry and vice versa. Currently each dropdown change filters the entire mixer instance instead of just the active elements.

Below is the mixer config and dropdown filter markup:
```
// mixItUp init
var mixer = mixitup($container, {controls: {
    toggleLogic: 'and'
  },
  pagination: {
    limit: paginationLimit,
    hidePageListIfSinglePage: true
  },
  callbacks: {
    onMixStart: function(state, futureState){
      $mixFail.addClass('hide');
    },
    onMixFail: function(state){
      console.log('mix fail');
    }
  }
});

filterSelect.on('change', function(){
    var $this = jQuery(this).val();
    mixer.filter( $this );
});
```

**The Markup:**
```
<select name="company-states" class="js-mixFilter-select">
   <option value="all">Filter by State</option>
    <option value=".cat-{state_slug}" name="{state_name}">{state_name}</option> // this * 50
</select>

<select name="company-industries" class="js-mixFilter-select">
   <option value="all">Filter by Industry</option>
    <option value=".cat-{industry_slug}" name="{industry_name}">{industry_name}</option> // this for ~ 10 industries
</select>
```
Based on your [toggle-filtering-and-logic example](https://demos.kunkalabs.com/mixitup/toggle-filtering-and-logic/), I was able to get the above to work if I switch from dropdowns to buttons with the ` data-toggle` attribute and the two filters worked! 

So now I am wondering if the use of `mixer.filter( $this );` doesnt account for any other active controls? And is there a way to mimic the behavior of `data-toggle` when using dropdowns instead of buttons to drilldown on the active filter?

**Comment by patrickkunka** [comment]
Hi there and apologies for the long delay in response.

I believe what you're looking for is the `.toggleOn()` and `.toggleOff()` API methods. You would need to programmatically call these methods as items in your dropdowns are selected and deselected.

More information is available in the API methods docs:

https://www.kunkalabs.com/mixitup/docs/api-methods/

Alternatively, if you dont want to write the UI logic yourself, the [multifilter extension](https://www.kunkalabs.com/mixitup-multifilter/) supports select dropdowns out of the box with multiple filter groups.

Please let me know if that works.
