### ISSUE TITLE
[MixItUp MultiFilter] selects with jquery ui selectmenu()

### ISSUE THREAD

**Issue by konsumkuenstler** [patrickkunka/mixitup#451]
Hi and thanks for this great plugin!

Ive purchased the multifilter extension which works fine so far. Now Im using two select fields to filter two categories and want to use jquery ui selectmenu() with it which almost works

html

    <fieldset data-filter-group="foo">
        <select id="foofilter">
            <option value="">Please Choose</option>
            <option value=".red">red</option>
            <option value=".blue">blue</option>			
        </select>
    </fieldset>

    <fieldset data-filter-group="bar">
        <select id="barfilter">
            <option value="">Please Choose</option>
            <option value=".small">small</option>
            <option value=".big">big</option>			
        </select>
    </fieldset>

script

    var containerEl = document.querySelector('#mixWrapper');
	var fooSelect = $('#foofilter');
    var barSelect = $('#barfilter');
    
    var mixer = mixitup(containerEl, {
        multifilter: {
            enable: true
        }
    });
	
    $( "#foofilter, #barfilter" ).selectmenu({
        select: function( event, ui ) {
            var filterString = fooSelect).val() + barSelect.val();
            mixer.filter(filterString);
        }
    });

As soon as it comes to the "please choose" or empty value nothing happens. If I decide to insert "all" for each "please choose" I get all items for both groups instead of "all" for the selected group. I tried to use the API methods like getFilterGroupSelectors(). But when I use

    mixer.getFilterGroupSelectors('foo');

I get an uncaugt error: [MixItUp MultiFilter] No filter group could be found with the name "foo".

What can I do to get the "all" for the selected group only?

**Comment by ghost** [comment]
Hi there, have you tried without the jquery plugin to start with (e.g. just native select options, like in the demo)?

You shouldn't need to use any custom code (like what you are doing in the `select` callback), as the point of the multifilter extension is that it will handle all changes, logic and concatenation for you. As long as the select plugin you are using emits a native 'change' event, (i.e, it respects the API of a `<select>` element), then you should be fine.

I would recommend getting your project working as desired with native elements first, and then adding the plugin on top.

**Comment by konsumkuenstler** [comment]
> I would recommend getting your project working as desired with native elements first, and then adding the plugin on top. 

Yes, thats exactly what Ive did. Sometimes its good to have a nice styled select like jquerys selectmenu provides. And the select callback is the way to trigger the change event with it. 

I solved it by adding ".all" to each item and just call them with "Please Choose". So in this case I filter "all" for each group as desired.

**Comment by patrickkunka** [comment]
Ok great. If all working now, will close.
