### ISSUE TITLE
Elements disappearing after clicking on an item. 

### ISSUE THREAD

**Issue by rakewell** [patrickkunka/mixitup#456]
http://54.196.225.133/

if you scroll down to software categories and click on an item in the mixitup list (e.g Payroll) you will notice that all the items disappear. Does anyone know how I can stop this from happening? Any ideas would be appreciated.

**Comment by kodzuru** [comment]
Have the same problem. See that page. In another tabs all work fine, but "Все страны" all elements dissapear.[https://bankrot.gov.by/SamplePages](url)
Add target="_blank" to html in browser and watch.
[before click](https://puu.sh/AV4bR/0e8060b9fd.png)  and [after click](https://puu.sh/AV4cQ/e3391469a4.png)

**Comment by patrickkunka** [comment]
Kodzuru's link appears to be working for me and I can no longer access Rakewell's IP. Closing for now. If this is still an issue for either you provide new working links / steps to reproduce.
