### ISSUE TITLE
Filter none if no checkbox is checked

### ISSUE THREAD

**Issue by shyam-singh-zz** [patrickkunka/mixitup#457]
Hi Patrick,

I have configured **MixItUp MultiFilter** in one of my project and I am stuck with a particular problem. I want no result to be shown when all the checkboxes are unchecked and in order to achieve that, I am counting the number of checkboxes checked on checkbox change event and if no checkbox is checked, I am triggering filter('none') but it's not working. What it does is shows no results and then again shows complete results as on page load and I have no clue as to how to prevent multiple filter calls on one checkbox check/uncheck event.

The link to the page where it's currently implemented is [http://delhigrainmerchant.com/beta/category/wholesale-trader/rice-trader](http://delhigrainmerchant.com/beta/category/wholesale-trader/rice-trader)

Thanks and regards,

**Comment by patrickkunka** [comment]
Hi, apologies for the delayed response.

I think what you are looking for is the `controls.toggleDefault` configuration option. By default, this is set to `'all'`, but you would want to set it to `'none'`. This is a configuration from MixItUp core, but it is also respected by the MultiFilter extension. This is described in the MultiFilter getting started guide:

https://www.kunkalabs.com/mixitup-multifilter/docs/get-started/

```js
var mixer = mixitup(container, {
    mulfilter: {
        enable: true
    },
    controls: {
        toggleDefault: 'none'
    }
});
```

Hope that helps.
