### ISSUE TITLE
Issue with hover effects in Wordpress using MixItUp

### ISSUE THREAD

**Issue by jamesyesjames** [patrickkunka/mixitup#458]
Hello,
Thanks for your script - have used it on a few sites without issue however I'm just building a new site which uses a reflection.js script and some css for shadows. When you hover over the product images a second image is show of the same product. All was working fine but now I have added MixItUp sometimes when I load the page (normal refresh) the sizes are all messed up (reflections are too large and the second image on hover comes up huge!). 
Any ideas on how I might fix it?

http://creativegoldlondon.com/wp/signature-iphone/

Many thanks once again,
James

**Comment by jamesyesjames** [comment]
I changed Script version to V3 and now works fine - lovely script... :)

**Comment by patrickkunka** [comment]
Great, glad you figure it out.
