### ISSUE TITLE
First animation works but not the subsequent ones

### ISSUE THREAD

**Issue by laurentbertin** [patrickkunka/mixitup#461]
Hi,

I've a problem I can't resolve, I tried everything I found on the doc and google without success.

The first fade animation when filtering works, but then it just disappear / appear in a instant.

Example here  : https://clean.hypnoscient.fr/contenus/

Thanks

**Comment by patrickkunka** [comment]
Hi there - looks like your project is working fine, so guessing you already figured this out. However I did notice you are using MixItUp v2. You might want to upgrade to the latest version (v3), and then you can take advantage of all the document and demos at kunkalabs.com/mixitup, plus various GitHub issues here

There is a migration guide here which you may find useful: https://www.kunkalabs.com/mixitup/migration-guide/

**Comment by laurentbertin** [comment]
Hi,

It's working fine downgrading to MixItUp 2. MixItUp 3 is a pain with flex and doesn't work with floats. But it works and that's enough for now.

I will migrate though for Ajax but something is working in MixItUp 2 that does not in 3 (with floats).
