### ISSUE TITLE
Keyword Search Auto Recommendation

### ISSUE THREAD

**Issue by bolivarln** [patrickkunka/mixitup#464]
I'm using an older version of mixitup and wanted to know if if there is a way to generate recommendations as users type into the search box. This is probably a basic question, but if I could be directed on which part of the code where this would lie and any tutorials. Below is my website and the use case.

https://www.sustainabilityconsortium.org/product-sustainability/productfinder/

Version Number: v2.1.11

**Comment by patrickkunka** [comment]
Hi, mixitup only deals with filtering and sorting, so this type of thing would be the responsibility of your own custom ui code or some kind of autocomplete ui plugin. Having said that, searching by wilcard dom selectors (which is how it is done in the mixitup 3 demo and multifilter extension) is a very poor way of searching, and if someone wants to do anything complex (like autocomplete) i will always recommend a server-side solution instead.

**Comment by bolivarln** [comment]
Is there any way to implement an auto complete plugin with MixItUp? Are there any examples or tutorials using wordpress?

What I need isn't too complex. I have a list of products that I'm sorting with MixItUp. I need to auto populate in the search box as they type. About 150 products, that all have keywords.
