### ISSUE TITLE
Have radio buttons show filtered item (from disqus comment)

### ISSUE THREAD

**Issue by Ricky55** [patrickkunka/mixitup#465]
Hi I'm using the multi filter with radio buttons very similar to one of your included demos.

I am filtering on load but I can't seem to work out how to make the radio button checked on load to reflect the category thats been loaded.

I could use checked on the radio button but the clear / reset button doesn't clear the checked state.

Can you please point me in the right direction?

The link
https://jaybe-dev.uk/test.php

**Comment by Ricky55** [comment]
I might not even need the multi filter on that example but I also want to do it here

https://www.jaybe.com/products/folding-beds/

But if you use the first example to keep it simple.

**Comment by Ricky55** [comment]
Have you had the chance to look at this mate ?

**Comment by patrickkunkadazn** [comment]
Hi Ricky,

Apologies for the delay as I'm currently on vacation, I've just looked at this. Unfortunately it isn't currently possible to set load values and have it work perfectly with the MultiFilter extension (see https://github.com/patrickkunka/mixitup/issues/431).

The best approach currently, is to programmatically set your desired initial values via JavaScript using the `setFilterGroupSelectors()` API method.

Here is an adapted version of the multifilter "radios" demo.
```
var mixer = mixitup('.container', {
    multifilter: {
        enable: true
    },
    animation: {
        enable: false, // temporarily disable animations during load phase
        effects: 'fade translateZ(-100px)'
    }
});

// Set a load selector for filter group you wish to set an initial value for
mixer.setFilterGroupSelectors('shape', '.circle');
mixer.setFilterGroupSelectors('size', '.small');

// Tell MixItUp to re-filter based on the new values
mixer.parseFilterGroups();

// Re-enable animations
mixer.configure({
    animation: {
        enable: true
    }
});
```

Note that in the above example, filter groups are referenced by name (e.g. shape, size). In order for the above to work, you will also need to "name" your filter groups in your HTML. This is as simple as providing a value for the `data-filter-group` attribute in each of your filter groups and is described [here](https://www.kunkalabs.com/mixitup-multifilter/docs/get-started/) under "Named Filter Groups". 

In your case it would be something like `<fieldset data-filter-group="product-range"> ...` and then you would call the API like `mixer.setFilterGroupSelectors('product-range', '.accessories')`;

I hope that all makes sense.

**Comment by patrickkunka** [comment]
Hi Ricky,

Apologies for the delay as I'm currently on vacation, I've just looked at this. Unfortunately it isn't currently possible to set load values and have it work perfectly with the MultiFilter extension (see https://github.com/patrickkunka/mixitup/issues/431).

The best approach currently, is to programmatically set your desired initial values via JavaScript using the `setFilterGroupSelectors()` API method.

Here is an adapted version of the multifilter "radios" demo.

```js
var mixer = mixitup('.container', {
    multifilter: {
        enable: true
    },
    animation: {
        enable: false, // temporarily disable animations during load phase
        effects: 'fade translateZ(-100px)'
    }
});

// Set a load selector for filter group you wish to set an initial value for
mixer.setFilterGroupSelectors('shape', '.circle');
mixer.setFilterGroupSelectors('size', '.small');

// Tell MixItUp to re-filter based on the new values
mixer.parseFilterGroups();

// Re-enable animations
mixer.configure({
    animation: {
        enable: true
    }
});
```

Note that in the above example, filter groups are referenced by name (e.g. shape, size). In order for the above to work, you will also need to "name" your filter groups in your HTML. This is as simple as providing a value for the `data-filter-group` attribute in each of your filter groups and is described [here](https://www.kunkalabs.com/mixitup-multifilter/docs/get-started/) under "Named Filter Groups". 

In your case it would be something like `<fieldset data-filter-group="product-range"> ...` and then you would call the API like `mixer.setFilterGroupSelectors('product-range', '.accessories')`;

I hope that all makes sense.

**Comment by Ricky55** [comment]
Yes it does I'll work into my project. Thanks and sorry to disturb your holiday (sorry vacation.)

**Comment by savyasachips** [comment]
How to use the reset logic with all the results to be displayed when none of the check-boxes are checked?

Thanks in advance.

**Comment by patrickkunka** [comment]
Hi - the default behaviour of the multifilter extension is to show all items when no check-boxes are checked. Could you provide more detail?
