### ISSUE TITLE
[Mixitup Sort] Sort methods does not work with custom collection

### ISSUE THREAD

**Issue by GillianPerard** [patrickkunka/mixitup#466]
Hi, 

When I try to sort my collection using the "**Sorting via an element collection**", it throws an error in the console.

`Uncaught TypeError: Cannot read property 'el' of undefined
    at mixitup.Mixer.filterOperation (mixitup.js:5689)
    at mixitup.Mixer.getOperation (mixitup.js:8521)
    at mixitup.Mixer.multimix (mixitup.js:8410)
    at mixitup.Mixer.sort (mixitup.js:8205)
    at HTMLButtonElement.sort ((index):80)`

Take a look to this jsfiddle: [https://jsfiddle.net/2ast1wg8/4/](url)
You could see the filter (using the Toggle Filter button) works but the sort (using the Sort button) does not.

Did I make something wrong or is a bug ?

**Comment by patrickkunka** [comment]
Hi there, this is a bug I'm afraid. There's a pr open for a fix here https://github.com/patrickkunka/mixitup/pull/447 but the author seems to have gone awol. I'll get it finished myself and merged into the next release asap, but in the meantime please use the dist file in  the PR.

**Comment by GillianPerard** [comment]
Thank you for answering so quickly. I wait you do the new release. :).

**Comment by patrickkunka** [comment]
This has been fixed in https://github.com/patrickkunka/mixitup/releases/tag/v3.3.1

Please let me know if its working for you.

**Comment by GillianPerard** [comment]
It works well now. Thanks a lot :+1: .
