### ISSUE TITLE
Internet explorer 11 and Dataset api

### ISSUE THREAD

**Issue by premhameed** [patrickkunka/mixitup#467]
Thanks for the nice plugin, unfortunately the data set api property is not working in IE 11 it was throwing error 'Object doesn't support property or method ' and I used https://github.com/paulmillr/es6-shim and https://github.com/es-shims/es5-shim to fixed it.

**Comment by patrickkunka** [comment]
Everything is the MixItUp distribution file is polyfilled for IE8 and above. Are you sure that the issue isn't in your own implementation somewhere? Do you have a line number or stack trace pointing to where the exception was thrown from?

**Comment by premhameed** [comment]
Thanks for the quick response 
I am using angularjs and this is from one of my controller
`

$scope.init = function() {



    $http({
            url: _spPageContextInfo.webAbsoluteUrl + "/_api/web/lists/getbytitle('OurBlog')/Items?$select=*",
            method: "GET",
            cache: false,
            headers: {
                "accept": "application/json;odata=verbose",
                "content-Type": "application/json;odata=verbose"
            }
        })
        .then(function successCallback(response) {

            $scope.blogposts = response.data.d.results;

            return mixer.dataset(response.data.d.results);


        }).then(function(state) {
            console.log('fetched ' + state.activeDataset.length + ' items');

        })
        .catch(console.error.bind(console));



};`

**Comment by premhameed** [comment]
and it is throwing error on angularjs and mixitup min 18:3732

**Comment by patrickkunka** [comment]
Hi again - I found one instance where Array.from wasn't using the polyfilled version in a dataset method. This has now been fixed in the latest release https://github.com/patrickkunka/mixitup/releases/tag/v3.3.1

Please let me know if that works for you. You will still need a Polyfill for ES6 promise.

**Comment by premhameed** [comment]
Thanks Patrick.
I will check and get back to you.
now I have a different issue, I am using angularjs with three different pages. I am using mixitup on my homepage. When it's loading the homepage on the first time mixitup dataset is working perfectly. If I navigate to another page and when I come back to the home page again it is not showing anything.No error and the mixitup is not loading at all. Any thoughts?

**Comment by premhameed** [comment]
What is the best way to use Mixitup with angularjs

**Comment by ghost** [comment]
Hello @premhameed - it is difficult to say without a link to your app. One thing I would say is make sure you are destroying your MixItUp instance when your angular component is removed from the document.

Unfortunately I am not familiar with angular so can not comment on the best to do an integration.

**Comment by premhameed** [comment]
Destroying the mixitup instance is fixed my issue. Thanks a million.
