### ISSUE TITLE
Help Hiding Filters

### ISSUE THREAD

**Issue by lear2000** [patrickkunka/mixitup#468]
Is it possible to hide filters that are not being used? IE: 
Left Side is flavor, right side is types of alcohol

There can be 1 flavor chosen. Then Multiple alcohols.

possible to hide the filters not in use?
in my screen shot
https://screenshots.firefox.com/hJ6PvQKPeCQXjWwL/staging.spindrift.flywheelsites.com

I have selected cucumber but burbon is not available for this yet it still shows when clicked

**Comment by patrickkunka** [comment]
Hi there,

As this type of functionality is very custom to your project, it is not included in MixItUp. 

You would therefore need to write some custom JavaScript to do this. MixItUp provides several APIs which will be helpful here.

Firstly, the onMixEnd callback which you can use to perform arbitrary functionality at the end of any operation.

Secondly, the state object which contains information about the currently active filters, etc. The state object is provided to all callbacks as an argument.

I would suggest checking the value of your first select, then querying the dom for the compound selector of that value, plus each value in your second select. For any query that returns 0 elements, you can temporarily hide that option from the dropdown. Or if there are elements, reshow it (in case it was hidden previously).

I hope that helps.

**Comment by lear2000** [comment]
err.. any tips?
im stuck. im sure it will answer a ton of peoples questions trying to do the same thing
im looping thru, but then not sure how to compare the other field
`             var showmen = state.show;
             for (var i = showmen.length - 1; i >= 0; i--) {
             	var showmenclass = showmen[i].className;
             }`

**Comment by ghost** [comment]
OK sure - here's a simple example with two selects options.

```html
<select name="menu-1">
    <option value=".option-1">Option 1</option>
    <option value=".option-1">Option 2</option>
    <option value=".option-1">Option 3</option>
</select>

<select name="menu-2">
    <option value=".option-a">Option A</option>
    <option value=".option-b">Option B</option>
    <option value=".option-c">Option C</option>
</select>
```

```js
const menu1 = document.querySelector('[name="menu-1"]');
const menu2 = document.querySelector('[name="menu-2"]');

const handleMenu1Change = () => {
   const menu1Selector = menu1.value;
   const menu2Options = Array.from(menu2.options);

   menu2Options.forEach(menu2Option => {
       // create a "compound" selector for matching any target containing both values
       const compoundSelector = '.mix' + menu1Selector + menu2Option.value;
       // Test to see if any targets exist with the selector
       const matchingTargets = document.querySelectorAll(compoundSelector);
       // If no targets exist, disable the option, otherwise enable it
       menu2Option.disabled = matchingTargets.length === 0;
   });
};

menu1.addEventListener('change', handleMenu1Change);
```

Not tested, but hopefully you get the idea.
