### ISSUE TITLE
Toggle buttons does not respond

### ISSUE THREAD

**Issue by Sebastian-Nielsen** [patrickkunka/mixitup#470]
Please see: https://stackoverflow.com/questions/52707617/mixitup-toggle-buttons-does-not-respond 

Minimum example that shows how the toggle buttons not responding: 
https://codepen.io/sebastian-nielsen/pen/jeyNzJ 

This might not be a bug, but perhaps just me being inable to code it properly due to the lack of proper documentation.

**Comment by ghost** [comment]
You seem to be using MixItUp v2. All of the documentation on https://www.kunkalabs.com/mixitup is for v3. Please upgrade to v3 and let me know if this is still an issue.

https://www.kunkalabs.com/mixitup/migration-guide/
https://www.kunkalabs.com/tutorials/filtering-with-mixitup/
https://demos.kunkalabs.com/mixitup/toggle-filtering-or-logic/
https://demos.kunkalabs.com/mixitup/toggle-filtering-and-logic/

**Comment by Sebastian-Nielsen** [comment]
After updating to the newest version nothing works at all, and I am getting the following error: 

> [MixitUp] Invalid configuration object property "filter"

https://codepen.io/sebastian-nielsen/pen/jeyNzJ 

By the way my objective is to get the toggle buttons working, I don't really care about the filter buttons, I only had them in the codepen to show that I could get that working but not the toggle buttons. Now, as you can see in the codepen, neither the filter nor toggle buttons work.

**Comment by patrickkunka** [comment]
That's correct and expected, again you are mixing the v2 and v3 APIs.

All you need is:

```js

var mixer = mixitup('#mix-wrapper', {
    controls: {
	toggleLogic: 'and'
    }
});
```

Also, please remove:

```css
.mix {
  display: none;
}
```

from your CSS, this is needed for v2 only.

Your html is good.

All working correctly now after those changes.
