### ISSUE TITLE
Filtering by minimum/maximum numeric range

### ISSUE THREAD

**Issue by thomashpb** [patrickkunka/mixitup#473]
Hi there - 

Is it possible to filter by number values? For example, could I filter out all entities with a "cost" field that equals greater than $500? 

Thanks!

thomashpb

**Comment by patrickkunka** [comment]
Hello,

Yes this is possible, but you need to create a "plugin" which applies an additional constraint or "filter" to all matching elements, before MixItUp then shows or hides content.

This is how the range slider demo works here: https://demos.kunkalabs.com/mixitup/filtering-by-range/
Source code here: https://github.com/patrickkunka/mixitup/blob/v3/demos/filtering-by-range/index.html

You could easily replace the range slider inputs with a text or number field which sets your max/min values. The way it works is as follows:
- You would add a new custom data attribute (e.g. data-cost) to each of your targets
- Your plugin's filter function will receive a reference to that element
- Parse its cost value
- Compare it with your current range
- Return `true` or `false` based on whether it should be shown or not.

Hope that makes sense. Will close for now, but let me know if you have additional questions.
