### ISSUE TITLE
Working example of mutlifilter with multiple select elements and filtering by URL?

### ISSUE THREAD

**Issue by pierrerocket** [patrickkunka/mixitup#475]
Trying to piece together bits from multiple pieces of the demo is getting me nowhere fast.  Been playing with this on and off for multiple days.  I'm the first to admit my JS skills suck.   I can kinda piece together stuff here and there and get it to work sometimes but in reality I don't understand how or why any of this works.  And I sure as heck don't know how to troubleshoot things when they dont work.  So my apologies.  I have a page with mixitup on it.  I have three selects, that all just select filters (no sorting options).  

My abominable JS looks like this:

`            // As we have no server-side application or routes, we will use
            // a URL "hash" for this demo, but we chould just as easily use
            // a URL route segment.

            // As we will use the target selector in several parts of the demo,
            // we will declare it as a variable here.

            var targetSelector = '.mix';

            /**
             * Reads a hash from the URL (if present), and converts it into a class
             * selector string. E.g "#green" -> ".green". Otherwise, defaults
             * to the targetSelector, equivalent to "all"
             *
             * @return {string}
             */

            function getSelectorFromHash() {
                var hash = window.location.hash.replace(/^#/g, '');

                var selector = hash ? '.' + hash : targetSelector;

                return selector;
            }

            /**
             * Updates the URL whenever the current filter changes.
             *
             * @param   {mixitup.State} state
             * @return  {void}
             */

            function setHash(state) {
                var selector = state.activeFilter.selector;
                var newHash = '#' + selector.replace(/^\./g, '');

                if (selector === targetSelector && window.location.hash) {
                    // Equivalent to filter "all", remove the hash

                    history.pushState(null, document.title, window.location.pathname); // or history.replaceState()
                } else if (newHash !== window.location.hash && selector !== targetSelector) {
                    // Change the hash

                    history.pushState(null, document.title, window.location.pathname + newHash); // or history.replaceState()
                }
            }

            // In this example, we must bind 'change' event handlers to
            // our <select> elements, then interact with the mixer via
            // its .filter() and .sort() API methods.

            var containerEl = document.querySelector('.mixitup',  { multifilter: {
                enable: true
            }});

            var industryFilter = document.querySelector('.industry-filter');
            var channelFilter = document.querySelector('.channel-filter');
            var displaystructureFilter = document.querySelector('.displaystructure-filter');

            if (containerEl) {

            // Instantiate and configure the mixer

            var mixer = mixitup(containerEl, {
                selectors: {
                    target: targetSelector
                },
                load: {
                    filter: getSelectorFromHash() // Ensure that the mixer's initial filter matches the URL on startup
                },
                callbacks: {
                    onMixEnd: setHash // Call the setHash() method at the end of each operation
                }
            });

                industryFilter.addEventListener('change', function() {
                    var selector = industryFilter.value;

                    mixer.filter(selector);
                });

                channelFilter.addEventListener('change', function() {
                    var selector = channelFilter.value;

                    mixer.filter(selector);
                });

                displaystructureFilter.addEventListener('change', function() {
                    var selector = displaystructureFilter.value;

                    mixer.filter(selector);
                });

                jQuery(document).ready(function ($) {

                    //only allow one select on sample gallery filter
                    $(".filtercontrols").find("select").change(function(){
                        $('.filtercontrols select').not(this).val(".all");
                    });

                })
            }`

Right now this all MOSTLY works.  The filtering with the selects works fine.  
If I change a select the URL updates with the hash.
If I open a new window/tab, and put in the URL with a hash it DOES filter based on that hash.  However the relevant select dropdown doesn't show the current filter.
If I change a hash in the url bar and hit enter nothing happens. (only works on initial load?)

Any help you can give me would be much appreciated.

**Comment by patrickkunka** [comment]
Hi Pierre,

Apologies for the delay in response.

You've mentioned that you're using the MultiFilter extension, but it seems that the demo you've based your integration on is using MixItUp core only (e.g. "vanilla" mixitup with no extensions).

The advantage of using the MultiFilter extension is that UI such as select dropdowns are handled for you internally, so you don't need to write any custom logic to bind change events or programmatically update the select option values (which is what your example is missing).

So firstly I would recommend getting a basic implementation with select dropdowns working based on the "selects" demo that is included with the MultiFilter extension.

Then, you can use the "Programmatic Filtering by URL" demo (also included in MultiFilter) to add only the URL-based filtering functionality.

I hope that helps.

**Comment by schlindibus** [comment]
Hi Mr Kunka ;)

"Then, you can use the "Programmatic Filtering by URL" demo (also included in MultiFilter) to add only the URL-based filtering functionality."

Where can i  dee that demo about the MultiFilters in URL?
