### ISSUE TITLE
Way not to do anything

### ISSUE THREAD

**Issue by tsarma** [patrickkunka/mixitup#476]
How can i disable some filter, ie to do nothing when clicked. May be this question is little bit abstract, so let me explain with screen shot of filter I've set up.

![screen shot 2018-11-29 at 14 19 42](https://user-images.githubusercontent.com/683894/49224512-e598fd00-f3e1-11e8-81a3-d144e8e8b300.png)

I've set up my mixitup version 3.3.1 with `toggleLogic: 'and'` and filtering is working as expected. I wanted mixitup to do nothing (ie. dont add class `mixitup-control-active` and don't filter) when I click any filter with `(0)` at the end (e.g Daily(0), Monthly(0) etc.. ) . I tried to add an event listener to all the filters and capture the events (preventDefault, stopPropagation) but this did not disable the mixitup. How can I disable mixitup filtering in such condition.

**Comment by patrickkunka** [comment]
The best way to do this might be to use `<button>` elements for your filter controls, and add a `disabled` attribute to any button with zero at the end of its text content. A disabled attribute will prevent any click events being dispatched from the element, and you might also want to hook into the `:disabled` psuedo-class in CSS to grey them out or something.

Hope that helps.
