### ISSUE TITLE
is this a multifilter? 

### ISSUE THREAD

**Issue by nandoblanco** [patrickkunka/mixitup#478]
I have 2 groups of filters (checkboxes) 1 for date and 1 for category, 

I'd like the date filter to only filter the categories checked or all if none and I'd like the category filter to only filter dates checked or all if none...  would this be considered multifilter?

**Comment by patrickkunka** [comment]
Yes - the easiest way to build this UI would be with the MultiFilter extension. Each one of your groups would be considered a multifilter "filter group", and the behaviour you described is the default behaviour.

You could built it without the multifilter extension, but it would require a considerable amount of custom JavaScript - both for binding form events, and also for concatenating selectors. With the multifilter extension, you get this out of the box.

Hope that helps.
