### ISSUE TITLE
Combine with HideSeek

### ISSUE THREAD

**Issue by danielbenjamins** [patrickkunka/mixitup#479]
Just trying to figure out if I have to change something in my MixItUp or HideSeek settings. Please see my question on their GitHub: https://github.com/vdw/HideSeek/issues/65

**Comment by patrickkunka** [comment]
Hi John,

I've had a look at your issue. Are you using the "filtering by URL" custom JS by any chance?

e.g: https://demos.kunkalabs.com/mixitup/filtering-by-url/

I can't think of any other reason why adding a hash to the URL would interfere with MixItUp. If so I would carefully through any custom JS to see at what point the interference is happening.

Out of the box - MixItUp doesn't know or care about the URL, so if there is an issue on our side it will be in that demo code.

Also If you could share a link to the bug or a reproduction, I can better assist, although I can't guarantee for support for third-party software.

**Comment by danielbenjamins** [comment]
I wasn't aware there's a text filtering option available in MixItUp. I enabled it, removed HideSeek and everything is working smoothly now. Thanks!
