### ISSUE TITLE
[MixItUp MultiFilter] Programmatically set filter group values on load (radios)

### ISSUE THREAD

**Issue by Easylancer** [patrickkunka/mixitup#480]
Hello.
I use 2 radio groups. How to make the default selected first radio buttons from each group when page loading. And so that they have the property checked (so that my css style will be applied to them). The screenshot is attached. Thank! 
![d9d85aaa39fce589623f1bdbce55f37af4faa2bee1e3180f0cf752e174846c0a](https://user-images.githubusercontent.com/41316102/50742207-d5621200-1218-11e9-9acb-5a4efebb7d22.jpg)

**Comment by Scopestyle** [comment]
You can set active states on page load:
```
$(function(){
  $('#Container').mixItUp({
    load: {
      filter: '.category-1,.category-2'
    }
  });
});
```

**Comment by patrickkunka** [comment]
Hi @Easylancer,

When using the MultiFilter extension, which I assume you are - MixItUp doesn't know how to break up compound list of selectors and apply them correct to the individual filter groups, so unfortunately @Scopestyle's example above won't work.

You'll need to use the programmatic filter API for multifilter:

```js
var containerEl = document.querySelector('.container');

var mixer = mixitup(containerEl, {
    multifilter: {
        enable: true
    },
    animation: {
        enable: false
    }
});

mixer.setFilterGroupSelectors('shape', '.square');
mixer.setFilterGroupSelectors('color', '.green');

mixer.parseFilterGroups();

mixer.configure({
    animation: {
        enable: true
    }
});
```

You're essentially telling MultiFilter exactly what to do on a per-group basis like this. Also note that animations are disabled and the re-enable after the initial filtering.

**Comment by Easylancer** [comment]
Patrick, thank you very much. Works!
