### ISSUE TITLE
Issue in reset the filter

### ISSUE THREAD

**Issue by savyasachips** [patrickkunka/mixitup#482]
I am using mixitup multifilter but I am struck at the point where I need to display all the results when none of the checkboxes are checked.

Can you please help me.

**Comment by Scopestyle** [comment]
Try this example, provided in the demo files:
`<button type="reset" class="control control-text">Reset</button>`

**Comment by savyasachips** [comment]
Hi @Scopestyle , I am calling same multifilter function in my page repeatedly with different set of results(which would be displayed one after the other) without page reload. When I use the reset button, filtering is working properly but not the callback function with alert call.

**Comment by patrickkunka** [comment]
Hi again - I just responded in another issue, but as I said there - the default behaviour of multifilter is to show all items when no filters are selected, so I must be misunderstanding your question. Are you able to share some code or a link to your project?

If you take a look at the the "checkboxes" demo included in the MultiFilter package, you'll see that all results are shown when you uncheck all filters, and that checkboxes are cleared when the reset button is clicked.

**Comment by savyasachips** [comment]
Hi Patrick,
I am using the below code in script tag of my jsp.

var containerEl = document.querySelector(".block"+val);

		 var mixer = mixitup(containerEl, {
		     multifilter: {
		         enable: true
		     },
		     animation: {
		         effects: 'fade translateZ(-100px)'
		     },
		       callbacks: {
		         onMixFail: function(state) {
		             alert('Sorry no products match your selections, click clear filters to view full range!');
		         }} 
		 }); 
		 var SupCheckBoxList = document.getElementById("SupCheckBox").value;
		 var SupCBList_array = SupCheckBoxList.split('|');
		 for(var i = 0; i < SupCBList_array.length; i++) {
			 mixer.setFilterGroupSelectors('Spl'+SupCBList_array[i], '');
		 }
		 mixer.parseFilterGroups();
		 mixer.configure({
		     animation: {
		         enable: true
		     }
		 });

In my page, based on dropdown value(var "val") selected , result set will change. Hence I have modified the containerElement variable of multi-filter plug-in to be dynamically set and called when the dropdown value is changed. 

With the above modifications in the plug-in call function, I am able to get the filter functionality and reset results too. 

But the only problem with the plugin is , when there is no result for a checkbox value( say "United Kingdom") it throws error msg of callback function which is correct behavior, but when I call the plugin for different set of results where "United Kingdom" has values in results set, I get the result along with the error message which make no sense. 

So what I need here is , when I reset (re-configure) the plugin when dropdown value selected, I want to reset  "state" value in onMixFail: function(state) so that it won't show old error msgs of previous plug-in call.

**Comment by patrickkunka** [comment]
Hi @savyasachips. 

Thanks for the additional info. That helps a lot. Are you able to share a link to a reproduction of the issue? Definitely the `onMixFail` callback should not be triggering if there are results found so I'd like to see it happening and do some deeper debugging.

**Comment by patrickkunka** [comment]
Closing for now due to inactivity, but let me know if still an issue and happy to reopen.
