### ISSUE TITLE
multiple sliders with mixitup 

### ISSUE THREAD

**Issue by Sybrenb** [patrickkunka/mixitup#484]
https://jsfiddle.net/34y58od2/2/

Thank you for that example of multiple sliders with mixitup fourroses.. Just what I needed for my project. Appreciate it. 

I'm stuggeling to remove the

>  'setInterval(function(){ handleRangeInputChange(); }, 1500);'

. It would be nice to just filter the grid after the value of the slider changes.

@patrickkunka

_Originally posted by @Sybrenb in https://github.com/patrickkunka/mixitup/issues/477#issuecomment-455182992_

**Comment by patrickkunka** [comment]
I'm hoping this is resolved in my last comment on: https://github.com/patrickkunka/mixitup/issues/477

Thanks

**Comment by Sybrenb** [comment]
Thank you
