### ISSUE TITLE
Reset filters

### ISSUE THREAD

**Issue by fourroses666** [patrickkunka/mixitup#485]
I would like to show a message when there are no results.
It works when I add the following to the container:

```
<div id="no-result">
	<p>No results found..</p>
	<button type="reset" data-filter="all" class="control control-text">Reset filters</button>
</div>
```

Add:
```
var no-results = document.getElementById("no-results");
    no-results.style.display = "none";
```

And my callback;
```
callbacks: {
	onParseFilterGroups: handleParseFilterGroups,
	//onMixEnd: setHash
	onMixEnd: function(state){
		if(state.hasFailed){  
			no-result.style.display = "block";
		}
		else{
			no-result.style.display = "none";
		}
	},
}
```
How can I combine it with the setHash, it fails or I'm not doing it correct.
And my second question is if its possible when using the Reset button also to reset the selected filters.
They keep being active while the filter is reset.

Any help is highly appreciated.

**Comment by Sybrenb** [comment]
var aantal_autos;
	
	$("body").on('DOMSubtreeModified', ".mixitup-page-stats", function() {
		aantal_autos = $('.mixitup-page-stats').text();
		if (aantal_autos == '0'){
			
			$("#no-results").css("display", "block");
			$(".mixitup-page-list").css("display", "none");
			
		}else{
			$("#no-results").css("display", "none");
			$(".mixitup-page-list").css("display", "block");
			
		}
	});

**Comment by fourroses666** [comment]
Thx,

I have fixed it with CSS. Seems there is added a class to the container (and pagination)
