### ISSUE TITLE
animation not working

### ISSUE THREAD

**Issue by jnaklaas** [patrickkunka/mixitup#488]
Filtering works as expected, animation is not working though. Is it possible some of my custom css is preventing animations from being executed?

I made a similar setup (using bootstrap grid) that works, animations included. Here's my js code:

```js
import mixitup from 'mixitup';
export default {
  init() {
    mixitup('.projecten',{
        animation: {
            enable: true,
            effects: 'fade',
            easing: 'ease-in-out',
            duration: 300,
        },
    });
  },
};
```

The targets (`.mix`) do not have custom css styling, they do have a child element with a hover transition on the `top` property. Removing the transition didn't solve the issue though.

**Comment by patrickkunka** [comment]
Hello, everything looks good in the code. I'd need to see a link to a reproduction or your project to debug this properly.

**Comment by jnaklaas** [comment]
I've set up a staging server at http://probambe.webhosting.be/projecten/

**Comment by patrickkunka** [comment]
Hi again - I've taken a look but this is a really weird one. I need to set some breakpoint on your site - would you be able to upload a version with unminified JavaScript? Thanks

**Comment by patrickkunka** [comment]
Closing for now due to inactivity but let me know if still an issue and I'll be happy to reopen.
