### ISSUE TITLE
Two instances of mixitup on the same page? Is it possible?

### ISSUE THREAD

**Issue by fmkatz** [patrickkunka/mixitup#49]
I tried setting up two "grids", "#Grid1" and "#Grid2", with their own sort buttons and lists of elements to mix. 
If I call mixitup on each, only the first call takes effect.  (Either works, but not both together.)

Is this just the way it is, or is there a right way to do this that I am missing?

**Comment by TUSHAR4541** [comment]
Here is a demo having multiple instances of Mixitup on the same page
http://jsfiddle.net/00s7fgny/

**Comment by rokobuljan** [comment]
**Even better** without adding useless classes and stuff...
Simply reference the desired mix container  using `data-mix="#mixerContainerId"` 

`<div class="filters_and_sorters" data-mix="#container2">`
and for the mix Container
`<div id="container2">`

jQuery:

```
$("[data-mix]").each(function(){
  var $self = $(this), // Element with buttons
      $filt = $self.find("[data-filter]"), // data-filter buttons
      $sort = $self.find("[data-sort]"),   // data-sort buttons
      $mix  = $($self.data("mix")); // Container to mix
  $mix.mixItUp({ 
    selectors: {
      filter: $filt,
      sort: $sort
    }
  });
});
```

[Fixed Fiddle demo](http://jsfiddle.net/00s7fgny/5/)

(BTW... would be nice to see that improved in the "plugin" core...)

**Comment by AnkitPandey007** [comment]
Hey please find my code-pen link-
It's working fine for **Issue with multiple mixitup on same page**
[https://codepen.io/AnkitPandey007/pen/qVWKLj](https://codepen.io/AnkitPandey007/pen/qVWKLj)

**Comment by patrickkunka** [comment]
Fyi, this is improved in v3 with the controls.scope option.
https://demos.kunkalabs.com/mixitup/multiple-instances-local-control-scoping/

**Comment by setarehz** [comment]
hi
I had the same problem thank you @rokobuljan it works perfectly!
