### ISSUE TITLE
Issues with third-party webflow examples on iOS Safari

### ISSUE THREAD

**Issue by den82** [patrickkunka/mixitup#492]
A good script, but it it doesn't work on tablets at least ipad mini. Could you explain to me why? The reason is not to in a resolution, because it works testing in different resolutions. For example try to use this example on ipad https://mixitup-multifilter-examples.webflow.io/multifilter-checkboxes . Nothing happens. How can I fix it?

**Comment by patrickkunka** [comment]
Hello,

MixItUp should be fully compatible with Safari on iOS, and all other major browsers on desktop and mobile devices.

The link that you have provided is not an official mixitup demo and was created by a third party, so its possible that it contains issues unrelated to mixitup.

I would recommend that you test the following demos on your device:

https://demos.kunkalabs.com/mixitup/

These are the official demos and have been tested across all devices and browsers.

If you have issues with any of these demos, please let me know and I'll be happy to help.

**Comment by patrickkunka** [comment]
Closing for now but let me know if you've experienced any of the same issues with the official demos and happy to reopen and look into it.
