### ISSUE TITLE
Is this possible to speed up the script?

### ISSUE THREAD

**Issue by den82** [patrickkunka/mixitup#495]
I have a catalogue of 3000 items and I use pagination, but I have to wait till all the items will be displayed before I get possibility to use pages. Is there any ways to speed up the script?

**Comment by patrickkunka** [comment]
Generally I wouldn't recommend using MixItUp with a dataset this large. If you are you are reading and looping over these entries from a database in real-time (not cached, not rendered to static files), this will firstly cause a large server-side overhead on page render, let alone issues on the client-side side.

On the client side, you could take the approach in the following demo to avoid having your browser render/paint 3000 items on page load:

https://demos.kunkalabs.com/mixitup/loading-animation/

1. Style all mixitup targets as `visibility: hidden` by default
2. Initialise your Mixer with `filter: 'none'`
3. Once initialised, add a `mixitup-ready` class to the container, to remove the `visibility: hidden` style.
4. Load your first page `mixer.filter('all')`

You can disable, adjust animations as needed.
