### ISSUE TITLE
mixer not recognised in repeated AJAX call

### ISSUE THREAD

**Issue by danjothebanjo** [patrickkunka/mixitup#496]
Hi Patrick,

I'm using your very groovy mixitup plugin to filter some content that is pulled into a container in the page via an AJAX call.

The instance is initiated in the AJAX success callback via an external function:

function carouselMix() {

	//remove mixitup if it already exists
	
	if (typeof mixer !== 'undefined') {
	   mixer.destroy();
	} else {
		console.log("no mixer found");
	}
	
	var mixer = mixitup('.sortable-list', {
	    callbacks: {
	        onMixClick: function(state, originalEvent) {
				console.log('The control "' + this.innerText + '" was clicked');
				},	
	        onMixEnd: function (state) {
	            carouselSlide();
	            console.log('mix complete');
	        }
	    },
	    debug: {
	        enable: true
	    }
	});
	
	console.log(mixer);

}

The mixer gets set up fine the first time around - but when I run the AJAX call again mixer variable isn't found and so can't be destroyed and I get a warning message in the browser console - WARNING: This element already has an active MixItUp instance. The provided configuration object will be ignored. If you wish to perform additional methods on this instance, please create a reference.

I've tried running the destroy script outside the AJAX call on a different button to test and again the mixer variable isn't found.

Where am I going wrong?

**Comment by patrickkunka** [comment]
Sounds like a common JS function scoping problem. I would recommend making sure your `mixer` variable is created in a parent scope to both your instantiation code and your destroy code, so that both functions have access to the same variable and can destroy and overwrite the reference as needed.

E.g.:

```js
var mixer = null;

function handleSuccess() {
    if (mixer !== null) mixer.destroy();
    
    mixer = mixitup('.sortable-list', {
       ...
    });
}
```
