### ISSUE TITLE
filter by button and text input

### ISSUE THREAD

**Issue by markgonz** [patrickkunka/mixitup#497]
I am struggling to figure out how to filter by buttons and text input at the same time. For example: click filter button to show a matched group and then enter input to further filter on that matched group. Alternatively, type in text to filter and then use buttons to further filter.  I found an old example here: https://codepen.io/patrickkunka/pen/KpVPWo, but that is using the old version of mixitup.

**Comment by patrickkunka** [comment]
Hi Mark, I already responded to you by email a while ago, but just going to copy in my response here too so I can close this off:

You should be able to do what you need with the multifilter extension.

You need to create one or more filter groups with buttons, and one or more filter groups with text inputs. You can then combine the filter groups as needed.

The two demos in the multifilter package to look at would be "filters" and "text-inputs". You will see that the filtering UI for each of these demos is broken up into filter groups, each one targeting a specific category.

We can combine different types of UI as follows (for example, buttons for color, and text for shape):

```html
<fieldset data-filter-group class="control-group">
    <label class="control-group-label">Color</label>

    <button type="button" class="control control-color" data-filter=".green">Green</button>
    <button type="button" class="control control-color" data-filter=".blue">Blue</button>
    <button type="button" class="control control-color" data-filter=".pink">Pink</button>
</fieldset>

<fieldset data-filter-group class="text-input-wrapper">
    <input type="text" data-search-attribute="data-shape" placeholder="Search by shape"/>
</fieldset>
```

If you click "Green", you can then type "circle" to narrow down your selection, or alternatively, you can type "circle" first, and then click "green", for the same output. From your question, this appears to be what you are looking for.
