### ISSUE TITLE
Mixitup + Bootstrap 4 Dropdown (data-toggle collides)

### ISSUE THREAD

**Issue by navtsi** [patrickkunka/mixitup#498]
I have a navigation with Dropdowns (generated by Bootstrap 4) in the header, and a mixitup list in the the main content area of a page with ».mix« selector. If I click on the dropdown in the header, the also get the »mixitup-control-active« class. I think the data-toggle or other data- attribute from Bootstrap will collide with data- attributes from Mixitup.

It looks like is the data-toggle attribute. This is also used in Bootstrap. Please change title of it (data-togle-mix…).

**Comment by patrickkunka** [comment]
https://github.com/patrickkunka/mixitup/issues/268
