### ISSUE TITLE
Toggle + Select filters logic within and between + Reset  everything in Select Filter field??

### ISSUE THREAD

**Issue by Domzw** [patrickkunka/mixitup#500]
@patrickkunka 
I'm creating a prototype and have hit a wall -- wondering if what I'm trying to implement is even possible...
Can you create a reset inside a `<select>` as an `<option>`  so that  when selected it resets all filters and sort attributes — in my case this would be filters within a select field and toggle button filters + sort attributes in a select field. 
If so how is this implemented so that
 1) Items are filtered by the select filter AND toggle filter  while using OR _within_ the toggle filter group?
2) These items are sorted by the sort select element
3) All  3 fields can be cleared with one button implemented as an option under select filter 

Not a developer so hoping that all makes sense...

**Comment by patrickkunka** [comment]
Hi @Domzw - I just responded to you in a separate issue, but I will copy my response in here again for you:

The multifilter extension expects all <option> within a select to be filter controls, so unfortunately, having a global reset button in here would not work.

You could have a "local" reset option, (e.g. with a value of .mix) which would essentially reset its own filter group only, but as far as reseting all form inputs for the whole mixer, you would need to use an actual reset button for that: <button type="reset">Reset</button>.
