### ISSUE TITLE
Please Help: Custom selects - Select2 + MixItUp

### ISSUE THREAD

**Issue by Domzw** [patrickkunka/mixitup#501]
Wondering if it is possible to combine [Select2](https://select2.org/) or [another method](https://freefrontend.com/css-select-boxes/) of  fully customizing a select field with MixItUp3?

They all seem to achieve styling by replacing the `<option>` fields with a `<span>` or `<div>` element. I assume this is why when I used the **Select2** plugin the "selectfilter" stopped working BUT the toggle button and sort field were okay(?)

Is there a way to use MixItUp simultaneously with one of these methods or does MixItUp rely specifically on having "active" "visible" option fields and if the plugin/ script replaces them it won't work?

CC: @patrickkunka @c33s @LukasDrgon

**Comment by patrickkunka** [comment]
Hi @Domzw,

Yes its possible to integrate MultiFilter with a custom styled select plugin, but the plugin that you use must:
- Have an underlying `<select>` element that exists in the DOM even after the plugin has created its own elements (as you say, usually this is hidden by CSS, and divs or spans are then used for style-ability)
- Emit a native `change` event when you change the value of the select

This basically means that the plugin must follow the standard API for a select element, and MixItUp can treat it as if it was a standard select element. Some plugins do and some don't.

I actually have a plugin which does what you are looking for and which I can say for sure will work will work with MixItUp, which you might be interested in:

https://github.com/patrickkunka/easydropdown

Some demos here also: https://demos.kunkalabs.com/easydropdown/

**Comment by Domzw** [comment]
@patrickkunka Thanks so much for your response! This works perfectly!!!🙌🏾🙌🏾:D

**Comment by patrickkunka** [comment]
Great!

**Comment by Domzw** [comment]
@patrickkunka  Update: When easy drop down is implemented - my `<select>` filter only works sometimes i.e. will work after loading the page stop showing after filters are reset or randomly just stop. and my `<select>` sort field does not work at all. Everything was fine around 3am and now at 5pm its glitching, I'm not a developer so perhaps I implemented something wrong? Took out CSS that I should not have?
