### ISSUE TITLE
Mixitup Multifilter All Option

### ISSUE THREAD

**Issue by ghost** [patrickkunka/mixitup#505]
Is there an option for all when using multifilter plugin?
https://www.kunkalabs.com/mixitup-multifilter/

I know that if none of the options are selected, then it is selected as all I am just wondering if something like this would also work:

```
<input type="checkbox" value="all"/>
<label>All</label>
```

**Comment by ghost** [comment]
I tested this and this doesnt work, I am looking for a solution

**Comment by patrickkunka** [comment]
Please use `.mix` (or whatever your default selector is) when using MultiFilter. `all` is an alias for your default selector. MultiFilter is not currently smart enough to convert alias back to selectors.
