### ISSUE TITLE
Using hash with multiple containers

### ISSUE THREAD

**Issue by ghost** [patrickkunka/mixitup#506]
I was reading your response to this question #286 and I was able to get the containers work. 

I tried to use the hash method (also found through here) with these containers and I did this: 
```
var mixers = itemContainers.map(container => mixitup(container, config));
mixers.forEach(function (item) {
            window.onhashchange = function () {
                var selector = getSelectorFromHash();

                if (selector === item.getState().activeFilter.selector) return; // no change

                item.filter(selector);
            };
        });

```

The problem is that  if I change the hash, the old filter still applies. 
so example.com/#filter-1 
then I change to example.com/#filter-2
and the filter gives filter-1 and filter-2

is the above the best way to do the hash filtering?

**Comment by patrickkunka** [comment]
I wouldn't recommend URL based filtering with multiple mixers/containers on the page.

You should either have one mixer which writes to and reads from the URL, or none.

If you have several mixers which are all trying to update the URL, I don't know how you would avoid collisions. Perhaps I have misunderstood though, and all your mixers have the same content and behaviour?

If you have an example link I can look at I'd be happy to better understand what you're trying to do with this. Will close for now, but let me know if you want me to reopen.
