### ISSUE TITLE
Multiple container and sort

### ISSUE THREAD

**Issue by ghost** [patrickkunka/mixitup#507]
I used this method to initialize mixer for multiple containers and have one controller for all of them

```
const itemContainers = Array.from(document.querySelectorAll('.mixitup-item-container'));
 const config = {
            selectors: {
                target: targetSelector
            },
            load: {
                sort: 'total_students:asc'
            },
           multifilter: {
                enable: true
            },
 };
const mixers = itemContainers.map(container => mixitup(container, config));
```

this sort by total_students but when I use a button to filter: 

```
 <fieldset data-filter-group>
                                                <button type="button" data-sort="total_students:asc">Sort</button>
                                                <button type="button" data-sort="total_students:desc">Sort</button>

                                            </fieldset>
```

it does not sort anything, any ideas how to fix this?

**Comment by patrickkunka** [comment]
Hi there - your sort controls should not be inside a multifilter filter group, as they are not concerned with filtering.

Sort buttons should exist outside of all filter groups. Please see the "filters" demo in the MultiFilter package file as a reference. Notice the sort controls sit along side the filter groups.

If you want the same sort controls to control multiple containers, you will also need to enable "global" control scoping:

https://demos.kunkalabs.com/mixitup/multiple-instances-global-control-scoping/

Hope that helps.
