### ISSUE TITLE
Dynamic data in vue js

### ISSUE THREAD

**Issue by jongbonga** [patrickkunka/mixitup#509]
Struggling to integrate MixItUp 3 with VueJS with ajax data.
it works fine using the dataset API but the problem is I have a component for my item so I cannot use the `render target` method

How do I make it work with this setup?

```
data() {
    return {
        mixer: null,
        items: null
    };
},
created() {
    Api.get_all_items().then(all_items => {
        this.items = all_items;
    });
},
mounted() {
    this.mixer = mixitup(this.$refs.itemContainer);
}
```

**Comment by patrickkunka** [comment]
Hi there, unfortunately the only option is to use built-in render API need to let MixItUp manipulate the DOM directly, effectively owning all DOM inside the container (which itself could live inside a vue component. There are no specific bindings for Vue (or React, or any other framework at present), that would allow you use a component as your target elements.
