### ISSUE TITLE
How to filter multiple classes on load?

### ISSUE THREAD

**Issue by adil15** [patrickkunka/mixitup#511]
For example I have :

<div class="class1"></div>
<div class="class2"></div>
<div class="class3"></div>
<div class="class4"></div>

I want to filter class1, class2, and class4 on load

I have tried using load: {
filter: '.class1', '.class2', '.class4'
}
but this doesnt work. How can I achieve this?

**Comment by patrickkunka** [comment]
You're almost there but you need to provide a single string: `'.class1, .class2, .class4'`
