### ISSUE TITLE
Search to URL

### ISSUE THREAD

**Issue by Sybrenb** [patrickkunka/mixitup#514]
I'm using this search option in the mixitup filter: (https://demos.kunkalabs.com/mixitup/filtering-by-text-input/)

I want to add the result in the url like: https://example.com/#search=example. Is this possible?

**Comment by patrickkunka** [comment]
Hi @Sybrenb - this functionality isn't part of MixItUp - but you could easily create some custom code to generate and populate your URL hash segment as part of the existing `keyup` handler code.

You'd also need to adapt the demo a bit to:
- Read from and parse the URL on page load
- If a search segment is found, throw the search value into the input field
- and, provide that value to mixitup as its initial filter value:
```js
const initialSearchValue = ... // code to parse URL hash segment

// Set search field value as value provided by URL, or fallback to empty string
inputSearch.value = initialSearchValue || '';

// If initial search value found, create an initial selector based on it, or fallback to 'all'
const mixer = mixitup({
    load: {
        filter: initialSearchValue ? '[class*="' + searchValue + '"]' : 'all'
    }
});
```

Hope that makes sense.

**Comment by patrickkunka** [comment]
Closing for now, but let me know if you need more information.
