### ISSUE TITLE
add a second state without filter selector

### ISSUE THREAD

**Issue by gcoutino** [patrickkunka/mixitup#517]
Hi, i was looking for an example to add a selector (state) when the user select other option, for example:
<fieldset data-filter-group class="control-group">
    <label class="control-group-label">Color</label>

    <button type="button" class="control control-color" data-filter=".green">Green</button>
    <button type="button" class="control control-color" data-filter=".blue">Blue</button>
    <button type="button" class="control control-color" data-filter=".pink">Pink</button>
    <button type="button" class="control control-color hidden" data-filter=".red">Red</button>
</fieldset>

I have this RED button in the markup to add the class to some options, but I wont show it in the page, but I need to display the Red matching products when the Pink one is selected, I found something similar with the "comand"function, but this override the mix filter results. I need to only showing both matching products (red and pink) when the Pink is selected, with no Red filter display. Any suggestion? 

Thanks

**Comment by patrickkunka** [comment]
If you need to show or hide your control buttons based on which filter is selected, you can do this by hooking into the onMixEnd callback, and checking the state.activeFilter.selector to determine the current filter and which controls should be hidden or shown. This requires writing a small amount of custom JavaScript.

If you need to actually adjust your filter results based on which filter is selected, it might be better just to add a "red" classname to every "pink" product. That way whenever you filter by "pink", it will show all the "red" items too. I'm not sure if this is what you want, but that would be very easy to achieve purely by adjusting your HTML.

If you want to do anything more complex, you would need to create your own control event handlers, and then manually create your desired DOM selector string and send it to MixItUp via its API (e.g. `mixer.filter('.red, .pink')`.

I hope that helps.

**Comment by gcoutino** [comment]
Thanks, just adjusted the HTML. thanks so much. !
