### ISSUE TITLE
Multi Filter - added selector

### ISSUE THREAD

**Issue by hp0071** [patrickkunka/mixitup#519]
Hi Patrick!

Absolutely love Mixitup. Question:

I have it all working with 3 select elements that are being queried through MF. All works but one of the selects is 'location' and includes the option 'everywhere'. When the user chooses another location I want the 'everywhere' items to also show up IF the other two conditions have been matched. How do I ensure this happens?

**CURRENT SCRIPT (works as expected)**

```
<script>
var containerEl = document.querySelector('#database');

var mixer = mixitup(containerEl, {
selectors: {
target: '.mix'
},
multifilter: {
enable: true
},
animation: {
duration: 250,
nudge: true,
reverseOut: true
}
});

</script>
```

**THE LOCATION SELECT**

```
  <fieldset data-filter-group>

<?php $categories = get_categories('taxonomy=loc');
 
  $select = "<select autocomplete='off' name='cat' id='loca' class='postform select-filter last'>";
  $select.= "<option value=''>Location</option>";
 
  foreach($categories as $category){
    if($category->count > 0){
  $catwithdot .= $category->slug;
	
        $select.= "<option value='".$catwithdot."'>".$category->name."</option>";
    }
  }
  
  $select.= "</select>"; ?>
 
  <?php echo $select; ?>
  </fieldset>

```

Thank you!

**Comment by hp0071** [comment]
Any help? Thank you!

**Comment by patrickkunka** [comment]
Hi @hp0071 

If I'm understanding the question correctly, it sounds like this kind of logic isn't possible simply using the MultiFilter UI, as you basically end up with a final selector string exactly represents the concatenation of your various choices.

Perhaps one solution would be to monitor the values of your three selects with custom JavaScript change event listeners, and when the three options are in the exact state that you describe above, you could then manually transform the DOM selector string before it is sent to the mixer to be filtered against.

You can do this with the `callbacks.onParseFilterGroups` configuration option, which allows you to provide a function which will receive the newly constructed "filter command" object on every change to your filter groups UI, allows you to modify it, and then returns it back to mixitup.

```js
var mixer = mixitup(containerEl, {
    callbacks: {
        onParseFilterGroups: function(command) {
            console.log(command.filter.selector); // e.g: '.green.large, .blue.large'

            // do some custom logic... then adjust the output as needed

            command.filter.selector += ', .red.large'; // e.g: '.green.large, .blue.large, .red.large'

            return command;
        }
    }
});
```
