### ISSUE TITLE
Changing the data-logic attribute

### ISSUE THREAD

**Issue by efuson** [patrickkunka/mixitup#520]
I wrote a couple functions to change the data-logic attribute from 'and' to 'or' and vise-versa. 

document.getElementById("toggleand").onclick = function() { 
	$('fieldset').attr( 'data-logic', 'and' );
	var d = document.getElementById("toggleand");
	d.className += " mixitup-control-active";
	$("#toggleor").removeClass('mixitup-control-active');
};	
	

document.getElementById("toggleor").onclick = function () { 	
	$('fieldset').attr( 'data-logic', 'or' );
	var d = document.getElementById("toggleor");
		d.className += " mixitup-control-active";
	$("#toggleand").removeClass('mixitup-control-active');

The code works and changes the data-logic attribute, but the functionality of the filtering doesn't seem to change. Is there a better way to change the logic on button press?

**Comment by patrickkunka** [comment]
Unfortunately the control group logic is parsed once when your controls are first queried by mixitup, so changing the attributes later on will have no effect.

If you want to change the logic at runtime you can use the configure API, bound to your button click:

```js
mixer.configure({
    multifilter: {
        logicWithinGroups: 'and',
        logicBetweenGroups: 'or'
    }
})
```

This will change the logic for your whole instance, unlike the data-logic attribute which overrides these settings per group.

**Comment by efuson** [comment]
Sorry for my lack of knowledge, how would I bind the config to a button click? I've tried a couple ways but it doesn't seem to be working.

**Comment by patrickkunka** [comment]
Assuming your two buttons have some sort of selectable attribute (e.g. an ID, which they appear to from your example above), you could do the following:

```js
var toggleAndButton = document.querySelector('#toggleand');
var toggleOrButton = document.querySelector('#toggleor');

toggleAndButton.addEventListener('click', function() {
    mixer.configure({
        multifilter: {
            logicWithinGroups: 'and',
        }
    })
});

toggleOrButton.addEventListener('click', function() {
    mixer.configure({
        multifilter: {
            logicWithinGroups: 'or',
        }
    })
});
```

This would change the "logic within groups" as the name suggests. Hopefully this is what you want.  As per my initial example, you can also change the "logic between groups", and change both options at once.

**Comment by efuson** [comment]
That worked perfectly, thanks so much!
