### ISSUE TITLE
HTML init

### ISSUE THREAD

**Issue by nfq** [patrickkunka/mixitup#521]
Hi,

Is it possible to init MitItUp via HTML, similar to Isotope?

Thanks

**Comment by patrickkunka** [comment]
This isn't possible at the moment I'm afraid. At a minimum, you need at least the following JavaScript somewhere in your document:

```js
const mixer = mixitup('.container');
```

**Comment by nfq** [comment]
Thanks Patrick. Something I'd consider as a feature. Is really useful IMO if you have multiple instances in the same document, this way removing the need to have complex forEach loops on multiple Mixitup instances.
