### ISSUE TITLE
[mixitup Multifilter] Using Multifilter data-filter controls with url hash (not data-toggle)

### ISSUE THREAD

**Issue by Alshie** [patrickkunka/mixitup#523]
Hello,

I'm unable to get filtering by url working in conjunction with multifilter whilst using data-filter controls.

There is a demo included in the multi filter extension ("programmatic filtering by URL") that adapts the standard filtering by URL demo for usage with MultiFilter. I have edited this to use data-filter and it also stops working.

is it not possible to use url has with `data-filter` rather than `data-toggle`?

Changing my code to have toggle controls works fine.

It looks like getFilterGroupSelectors('color') does not return an array of active selectors if the controls are `data-filters`

recreate: in demo included in the multi filter extension ("programmatic filtering by URL") change the data-toggle controls to data-filter.

Thanks!

**Comment by patrickkunka** [comment]
Hi there - thanks for reporting this. This is a bug that somehow remained unnoticed for a long time!

I've just released a fix in MultiFilter v3.3.5 which you can download from your account.

Please let me know if it works for you.

**Comment by Alshie** [comment]
Hi there!

Yes this is now fixed, thank you :)
