### ISSUE TITLE
Wrong Email on my account on KunkaLabs (website)

### ISSUE THREAD

**Issue by shgzon** [patrickkunka/mixitup#525]
Hi Patrick,

I have sort of a personal issue. I used the wrong email address purchasing the license. I want it to link to my own email address. Could you please change that.

PM me for details. Please tried contacting you multiple ways already.

Thanks in advance,

With kind regards,
Stef

**Comment by patrickkunka** [comment]
All sorted now and have replied to your original email - thanks for the reminder.
