### ISSUE TITLE
How to remove headings of multifilter groups

### ISSUE THREAD

**Issue by kbrookes** [patrickkunka/mixitup#528]
I've got MixItUp and MultiFilter working quite nicely (great plugin!) but have run into a bit of trouble.

My basic structure is like this:

```.filter-container
  .item-group
     .group-heading
     .mix
     .mix
     .mix
     .mix
     .mix

  .item-group
     .group-heading
     .mix
     .mix
     .mix
     .mix
     .mix

  .item-group
     .group-heading
     .mix
     .mix
     .mix
     .mix
     .mix
```

I have two filter controls going, which are operating in 'and' mode.

The individual .mix items are filtering beautifully, but when I wind up with .item-groups that have no visible .mix items, the headings remain (of course).

I have partially solved this by making the .group-headings .mix items as well, using a de-duped list of the classes that are present on .mix items within their group... but we still wind up with some instances where the .group-heading has both classes, but none of the .mix items within the group do.

And at this point I'm stumped if there's a way to do this with MixItUp - is it possible to hide the entire .item-group if all of the .mix elements are hidden?

**Comment by patrickkunka** [comment]
Hi there,

I think your approach so far is valid. I'm afraid there isn't any other specific approach I can recommend. I suspect it could be solved with more specific query selector strings, or custom runtime JavaScript.

If this is still an issue let me know and if possible share a link to your project and I can reopen.

**Comment by kbrookes** [comment]
Hi Patrick, thanks for getting back to me.

We did wind up going down the javascript route, using the mixEnd callback. I'll paste my code here in case anyone else ever needs it:

`jQuery(document).ready(function($) {
			
			var containerEl = document.querySelector('.filtr-container');

			var mixer = mixitup(containerEl, {
			    multifilter: {
			        enable: true
			    },
			});

			
			
			jQuery('.filtr-container').on('mixEnd', function(e) {
				jQuery(' .people-archive__group').each(function(i, el) {
					if (jQuery(el).find('.expertise-single__people-col:visible').size() == 0) {
						jQuery(el).find('h2').animate({ height: '0', opacity: '0' });
					} else {
						jQuery(el).find('h2').animate({ height: '100%', opacity: '1' });
					}
				});
			});
		});`
