### ISSUE TITLE
An operation was requested but the MixItUp instance was busy. The operation was rejected because the queue is full or queuing is disabled. 

### ISSUE THREAD

**Issue by mazhar4399** [patrickkunka/mixitup#529]
I m using MixItUp library on my website. its work fine if i click slowly but problem occur on that time when i click speedily  or double click speedily  .then i getting warning

 "An operation was requested but the MixItUp instance was busy. The operation was rejected because the queue is full or queuing is disabled. "

here is the code that i m apply.

		<div class="">	<div class="controls">
			
			<label class="" style="padding-right: 0px !important;">
				<input type="checkbox" data-mixitup-control class="control" data-toggle=".gem" >Gem
			</label>
			<label class="" style="padding-right: 0px !important;">
				<input type="checkbox" data-mixitup-control class="control" data-toggle=".beach" >beach
			</label>
			
			<label class="" style="padding-right: 0px !important;">
				<input type="checkbox" data-mixitup-control class="control" data-toggle=".school" >skolan
			</label>
		</div></div>

    <div class="containerss" id="containerss">
		
          
            <button style="float:left" class="mix beach">Andersbergsringen</button>
            <button style="float:left" class="mix beach school gem">LinehedsVägen</button>
            <button style="float:left" class="mix school">Waldemar</button>
            <button style="float:left" class="mix school">Simo</button>
            <button style="float:left" class="mix gem">Vallos</button>
            <button style="float:left" class="mix school">laholmsvägen</button>
            <button style="float:left" class="mix gem beach">Haverdal</button>
            <button style="float:left" class="mix school gem">Mascusgaton</button>

            <div class="gap"></div>
            <div class="gap"></div>
            <div class="gap"></div>
        </div>

<script src="http://mrtestdemo.utv3.hemsidor.nu/wp-content/themes/betheme-child/mixitup.min.js"></script>
<script>
            var containerEl = document.querySelector('#containerss');

            var mixer = mixitup(containerEl, {
                controls: {
                    toggleLogic: 'and'
                },selectors: {
        target: '.mix'
    },
animation: {
queueLimit:1,
duration: 10
}
            });
        </script>

**Comment by patrickkunka** [comment]
Hi Mazhar, this warning means that given your animation duration, MixItUp cannot process operations quicker than you are triggering them. All operations go into a queue, with a limit of 1 (as per your configuration), and when that limit is met, the warning is shown.

You simply need to increase your queue limit to a reasonable amount (e.g 5).

```js
var mixer = mixitup(containerEl, {
    animation: {
        queueLimit:5,
        ...
    }
}); 
```
