### ISSUE TITLE
Their is a way to add list of "filters" and "remove"(X) button?

### ISSUE THREAD

**Issue by Ezra-Siton-UIX** [patrickkunka/mixitup#530]
![image](https://user-images.githubusercontent.com/16711871/70045963-b8bb8f00-15cd-11ea-921a-92c182a5c74c.png)

The idea/behavior:
https://www.carmax.com/cars/all

By mixitup-multifilter

**Comment by patrickkunka** [comment]
Hi Ezra,

By default, MixItUp includes UI for simple buttons only. If you want to do anything more complex, you can do so - but you need to create the UI, custom logic, and handle events yourself - which would control MixItUp via its API.

**Comment by Ezra-Siton-UIX** [comment]
Thanks.
