### ISSUE TITLE
No animation when filtering

### ISSUE THREAD

**Issue by LukeHW** [patrickkunka/mixitup#533]
Hi! I have been working with MixItUp for a couple of days and have run across a couple issues: when choosing a filter there is no animation between the elements, but it does sort them correctly and it places them correctly. I have combated the "weird moment" where it is supposed to do the animation (but doesn't giving a second or two delay between filters) by disabling it in configuration.

                    <script type="text/javascript" src="Mixitup/mixitup.min.js"></script>
			<script type="text/javascript">
				var config = {
					animation: {
						enable: false
					}			
				};
				var mixer = mixitup('#portfoliolist', config);
			</script>

I believe this has to do with the way I represent my elements in CSS. The only solution I have been able to find is that the HEIGHT of the elements may effect the animation. My elements have their own animation, so I tried to contain each one in a div and filtered them that way. I can provide more information if needed.

     #portfoliolist .portfolio {
	  -webkit-box-sizing: border-box;
	  -moz-box-sizing: border-box;
	  -o-box-sizing: border-box;
	  width:23%;
	  margin:1%;
	  float:left;
	  overflow:hidden;
    }

	.portfolio-wrapper {
		position: relative !important;
		background: #666;
		cursor:pointer;
	}

	.portfolio img {
		max-width:100%;
		position: relative;
		top: 0;
    -webkit-transition: all 600ms cubic-bezier(0.645, 0.045, 0.355, 1);
    transition:         all 600ms cubic-bezier(0.645, 0.045, 0.355, 1);		
	}
	
	.portfolio .label {
		position: absolute;
		width: 100%;
		height:50px;
		bottom:-50px;
    -webkit-transition: all 300ms cubic-bezier(0.645, 0.045, 0.355, 1);
    transition:         all 300ms cubic-bezier(0.645, 0.045, 0.355, 1);
	}

		.portfolio .label-bg {
			background: #add8e6;
			width: 100%;
			height:100%;
			position: absolute;
			top:0;
			left:0;
		}
	
		.portfolio .label-text {
			color:#fff;
			position: relative;
			z-index:500;
			padding:5px 8px;
		}
			
			.portfolio .text-category {
				display:block;
				font-size:9px;
			}
	
	.portfolio:hover .label {
             bottom: 0;
        }
	.portfolio:hover img {
            top:-30px;
       }

**Comment by LukeHW** [comment]
I'm certain now that the issue is with the "float: left" value in my portfoliolist .portfolio declaration. Although, changing that value to something like "display: inline" makes the mixitup animation return, but then my elements come out wonky (background of elements become large -- stretch up the the other side of the container and stack up on top of each other like a monolith, rather than in the default grid formation) unfortunately.

**Comment by LukeHW** [comment]
I have resolved my issue. The elements that I was using with MixItUp were wrapped in a separate div tag, which ended up taking up the width of the parent container. I removed the separate div tags (which fixed my width issue) from my elements and then replaced "float:left" with "display:inline-block".

**Comment by patrickkunka** [comment]
Thanks for the info Luke and glad you sorted it out. Yes floats are not recommend for MixItUp layouts. Sounds like your found the correct solution (inline-block on the target parent elements).
