### ISSUE TITLE
MultiFilter - mixitup-container-failed when i initialize MixItUp

### ISSUE THREAD

**Issue by Baferas** [patrickkunka/mixitup#535]
Hello, let me start by saying that MixItUp is a great plugin.

I have incorporated MultiFilters into my project but as soon as i press any filter, MixItUp adds the 'mixitup-container-failed' class into my main mix-container.

How can i debug this? Where can i get more information about error messages/causes? 

I should also probably mention that i build my entire collection page by consuming a JSON, the entire page is build with JavaScript. MixItUp is initialized **after** the collection and each mix HTML is built and appended into the mix-container.

Halp! :)

**Comment by Baferas** [comment]
Cancel that, i found the error, it had nothing to do with MixItUp, it was during the creation of the collection, it was my code :)

**Comment by patrickkunka** [comment]
Glad you sorted it out, thanks for the update.
