### ISSUE TITLE
Multifilter clear toggles

### ISSUE THREAD

**Issue by HoneyNutz** [patrickkunka/mixitup#536]
I am having some trouble with unfiltering a toggle switch in the multifilter.  

I currently have 2 filter groups, one is a set of toggles and one is a straight filter item.  On page load, the page loads a single element (instructions), The user then clicks away to see content.  However, when I clear a multifilter toggle it defaults to state "all" so it is showing that instructional element again along with my other content -- instead of  my filter default which is everything else but not that one element.  I assume toggleDefault should load everything but that one element, but I am not seeing how it would work.

**Comment by patrickkunka** [comment]
Clearing multifilter (with a native reset button - I assume) will have the effect of resetting the values of each input to an empty value - multifilter filter will then parse the resulting `change` event, and see that nothing is selected.

If you want to reset to a specific state, you would need to create a custom button e.g: `<button type="button">...</button>` (not type="reset"), which when clicked, calls the `setFilterGroupSelectors()` API, setting each filter group to a desired value as needed.

For example:

```js
myResetButton.addEventListener('click', () => {
    mixer.setFilterGroupSelectors('myFilterGroup1', []); // Reset each group as needed
    mixer.setFilterGroupSelectors('myFilterGroup2', []);
    mixer.setFilterGroupSelectors('myToggleGroup', ['.instructions']); // For the group which you wish to reset to a specific initial value, provide its selector

   mixer.parseFilterGroups(); // tell mixitup to parse the new selectors and re-filter
});
```
