### ISSUE TITLE
Pagination: .mixitup-control-active is a shared class between pagination controls and filter controls

### ISSUE THREAD

**Issue by kctdfh** [patrickkunka/mixitup#549]
Hey! 

So I'm trying to have my active filter have a red border-bottom (which I'm achieving with ::after) but want my active page indicator to be my .mixitup-control with a red background.

Currently, this seems impossible because .mixitup-control-active applies to both the active filter and the active page indicator.

Would be best if we separate these two as such: 
--> .mixitup-control-active applies to active filters
--> mixitup-pagination-control-active applies to active page numbers

<img width="759" alt="2020-05-11 16_59_10-Pagination in tabs" src="https://user-images.githubusercontent.com/28873487/81611368-ebea2180-93a8-11ea-8883-1d513a4c3d50.png">

As you can see above, the indicator is the same on both the active filter and active page

<img width="401" alt="2020-05-11 10_26_26-FilmFolk - Figma" src="https://user-images.githubusercontent.com/28873487/81611369-ed1b4e80-93a8-11ea-8dd1-270bafd6ac80.png">

The design specs require the pagination to be solid red and the filter indicator to be an underline

**Comment by patrickkunka** [comment]
Hi there,

Given you already have a specific element that your pagination controls live inside (e.g: `<div class="mixitup-page-list"></div>`)

You can use a child selector to target them:

```css
.mixitup-page-list .mixitup-control-active {
   /* your custom styles here */
}
```
