### ISSUE TITLE
multifilter not filtering on page load with url # 

### ISSUE THREAD

**Issue by pottermel** [patrickkunka/mixitup#550]
Hi,
I am using multifilter (v3.3.6) and am using both a url parameter and hashes - for example (mysite.com/products.aspx?Category=1#brand=abc). I am having an issue with the page updating to the url hashes. The check box updates, but the actual items displayed don't update upon load. As you can see in the code, I added window.location.search in some of the code under the "var newHash = '#' + serializeUiState(uiState);". Do I need to add this somewhere else to get the items to update? Attached is my code
[test.txt](https://github.com/patrickkunka/mixitup/files/4624704/test.txt)

**Comment by patrickkunka** [comment]
Hi Pottermel,

If it's possible to link me your site where I can reproduce the issue that would be really helpful.

**Comment by pottermel** [comment]
Hi Patrick,
You should be able to view the site here. I do notice now that I have to press enter twice for the checkbox to change when going directly from the url. With this, only items that start with MapleWave should show.
http://www2live/products/Cat.aspx?Category=Storage#brand=MapleWave

Thanks,
...................................................................................................
Melissa Potter

**Comment by pottermel** [comment]
Hi Patrick,
Just wanted to make sure you were able to access the site and were able to reproduce the issue.

**Comment by pottermel** [comment]
Hi, I have narrowed it down to being an issue with the pagination when it's unlimited items on a page

**Comment by pottermel** [comment]
Hi, I figured out that I had to change the order of the filter groups and it seems to be working now.
