### ISSUE TITLE
Your website SSL certificates have expired

### ISSUE THREAD

**Issue by benneic** [patrickkunka/mixitup#591]
Just a heads up that your SSL certificates on the `kunkalabs.com` domains have expired and your customers are getting security warnings when visiting the websites.

![image](https://user-images.githubusercontent.com/965281/143792456-ccd2b8a3-b30d-412a-8c02-8eb01a0884ae.png)

**Comment by patrickkunka** [comment]
Thanks so much for the heads up - fixed now!
