### ISSUE TITLE
Option to disable fading on load

### ISSUE THREAD

**Issue by m-radzikowski** [patrickkunka/mixitup#70]
When MixItUp is creating content of list fades in for the "transitionSpeed" time. I don't want to disable animations and set transitionSpeed to 0, but I would like to disable fading on load and have all items visible and active as soon as posible.

**Comment by hemant2586** [comment]
You can disable animations for loading, and then enable for subsequent operations as below

$('#Container').mixItUp({
    animation: {
        enable: false       
    },
    callbacks: {
        onMixLoad: function(){
            $(this).mixItUp('setOptions', {
                animation: {
                    enable: true    
                },
            });
        }
    }
});

**Comment by patrickkunka** [comment]
FYI, what the OP describes is now the default behavior in v3.
