### ISSUE TITLE
Issuer with filter

### ISSUE THREAD

**Issue by n1ckfury** [patrickkunka/mixitup#80]
Hi, 

I used this tutorial to use mixitup : http://www.queness.com/post/14577/create-a-simple-responsive-portfolio-page-with-filtering-and-hover-effect

For some reason when I click on one of the button, it filters the items, the move but then come back to their places with all the different items.

Here's the js: 

```
$(function () {     
    var filterList = {      
        init: function () {         
            $('#portfolio-list').mixitup({
                targetSelector: '.portfolio-item',
                filterSelector: '.filter',
                effects: ['fade'],
                easing: 'snap',
                onMixEnd: filterList.hoverEffect()
            });                         
        },          
        hoverEffect: function () {          
            // Simple parallax effect
            $('#portfolio-list .portfolio-item').hover(
                function () {
                    $(this).find('.label').stop().animate({bottom: 0}, 200, 'easeOutQuad');
                    $(this).find('img').stop().animate({top: 0}, 500, 'easeOutQuad');               
                },
                function () {
                    $(this).find('.label').stop().animate({bottom: 0}, 200, 'easeInQuad');
                    $(this).find('img').stop().animate({top: 0}, 300, 'easeOutQuad');                               
                }       
            );                          
        }
    };              
    filterList.init();      
}); 
```

The HTML : 

```
             <nav class="vertical-dot-navbar">
        <a class="filter active" data-filter="cnpt wbie igpy mnvo">ALL</a>
        <a class="filter" data-filter="cnpt">CAMPAIGN+PRINT</a>
        <a class="filter" data-filter="wbie">WEB+INTERACTIVE</a>
        <a class="filter" data-filter="igpy">IMAGING+PHOTOGRAPHY</a>
        <a class="filter" data-filter="mnvo">MOTION+VIDEO</a>
        <div class="effect"></div>
      </nav>  

  <div id="portfolio-list">         

      <div class="span4 portfolio-item cnpt" data-cat="cnpt">
        <div class="mask2"> 
          <a href="" rel=""><img src="../2k14/assets/anna_sm.png" alt=""></a> 
        </div>
        <div class="inside">
          <hgroup>
            <h2>Anna</h2>
          </hgroup>
          <div class="entry-content">
            <p>Its rounded edges, right angles and uniform stroke weight create
            unity throughout the typeface. Anna gives the sci-fi world a more elegant font.
            </p>
            <a class="more-link" href="#">view project</a> 
          </div>
        </div>
      </div>
```

Can anybody help me out and tell me what's wrong?

**Comment by breadadams** [comment]
I just ran into what I _think_ is this issue (I was searching all over for "mixitup items jumping", etc.). Turns out one of the parent divs of the items I was filtering wasn't floated correctly and therefore the calculations done in JS weren't "correct".

Just a note for anyone who might run into this, check your css! 😸

**Comment by alilishan-omniphics** [comment]
Anybody got a solution for this? 
@breadadams how about you?
Iam going over and over my css fixing floats but still happens ><

**Comment by patrickkunka** [comment]
@alilishan-omniphics This is a very old issue so I suspect whatever issue you're having is not relevant to this thread. If you're having issue with layout, I would recommend using one of the demos as a starting point and then adapting it to your design as needed:

https://demos.kunkalabs.com/mixitup/

As you add in features, check to see at what point the layout becomes broken and that should help you understand the cause of the problem.

Generally speaking, floats are not recommended for use with MixItUp, and flexbox or inline-block is preferred. More information here: 

https://www.kunkalabs.com/tutorials/mixitup-grid-layouts/

Hope that helps.
