### ISSUE TITLE
Mixitup + Select2

### ISSUE THREAD

**Issue by Grawl** [patrickkunka/mixitup#91]
Currently I am developing a system to filter things through Select2 and Mixitup. It's a two good plugins, but they cannot work together as a team. It's hard.

**Comment by amerigeau** [comment]
Hi,
You could do this like this :
- install mixitup normaly
- install select2 on your select
- use event data of select2 :
`$('#mySelect2').on('select2:select', function (e) {
    var data = e.params.data;
});`
- insert in this code the call of mixitup like this :
`jQuery('#s_boutiques').on('select2:select', function (e) {
	    var data = e.params.data;
	    mixer.filter(data.id);
	});`
I have used data.id in my case but it could change.
Hope it will help :)
